### ISSUE TITLE
White screen inside plugin when checking for e107_INIT

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#2633] opened 2017-05-13 14:24 UTC
Got some strange installed plugin behaviour.
If i put this "standard check" on the beggining of the main plugin file:
` if (!defined('e107_INIT')) { exit; }`
the file simply exits, because e107_INIT isn't there, which is weird, since plugin is installed and all ok.
It will only work if i put this instead of previous code:
```
 if (!defined('e107_INIT'))
  	{
  		require_once("../../class2.php");
  	}
```

Does anyone has experienced this same issue?

**Comment by tgtje** [comment] 2017-05-13 23:04
not familiar with this piece of code, likely is how plugin (file) works or needs to work. If it is kind of a redirection than yes the bottom one would be needed (to make sure it (redir..) loads class2.. ( my 2 cents)

**Comment by Moc** [comment] 2017-05-14 07:59
You need to use the second example. It's related to SEF URLs.

**Comment by rica-carv** [comment] 2017-05-14 11:14
@Moc It's weird, since i got SEF URL's disabled in htaccess....
I'm starting to get even more dissapointed by SEF URL's.... 😡

**Comment by CaMer0n** [comment] 2017-05-16 21:45
@rica-carv If your plugin uses e_url.php then it may include your plugin file from inside index.php. The second piece of code makes sure that class2.php is not loaded twice and from an incorrect path.

**Comment by CaMer0n** [comment] 2017-05-16 21:45
Closing this because it is not a bug.

**Closed by CaMer0n** 2017-05-16 21:45 UTC

**Comment by rica-carv** [comment] 2017-05-17 18:28
@CaMer0n Well, my plugin has no e_url.php file, so i wonder where it does include for the first time the class2.php file....
I do have 5 e_*.php files in it (e_header, e_menu, e_module, e_shortcode, e_update), but none loads the class2.php file....

**Comment by CaMer0n** [comment] 2017-05-24 19:44
@rica-carv Does this url cause problems for you? (with Chatbox installed of course)
/e107_plugins/chatbox_menu/chat.php

**Comment by rica-carv** [comment] 2017-05-25 18:49
@CaMer0n No, just got a screen with the header (Chatbox (all posts)) and the moderate chatbox button, so i think it's ok...
