### ISSUE TITLE
Social admin config white page

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#1667] opened 2016-05-22 06:48 UTC
A made the latest Github update. The social admin config white page, don't work.

**Comment by Moc** [comment] 2016-05-22 10:49
Please update from Github again and see if the issue is fixed

**Comment by fizi** [comment] 2016-05-22 11:51
Don't work e107_plugins/social/admin_config.php , white page (500 error).

**Comment by tgtje** [comment] 2016-05-22 12:31
Was social a;ready running ? If so please empty cache; use tools/database scan plugin for changes..
Just synced with latest files. no issues

**Comment by fizi** [comment] 2016-05-22 12:42
I made it but don't work.

**Comment by Moc** [comment] 2016-05-22 12:48
Please check your server's Apache error log, the 500 error should give more information there. You can find this log in your hosting's control panel.

**Comment by fizi** [comment] 2016-05-22 13:34
This is in the log:
PHP Parse error:  syntax error, unexpected '.', expecting ')' in /chroot/home/.../.../html/testsite/e107_plugins/social/admin_config.php on line 76, referer: http://.../.../e107_admin/admin.php

**Comment by Moc** [comment] 2016-05-22 14:06
Should be fixed now. Please update with the latest files from Github and let me know.

**Closed** 2016-05-22 14:06 UTC
Labels: awaiting feedback, testing required

**Comment by fizi** [comment] 2016-05-22 14:11
I tested and work. Thanks.

**Comment by Moc** [comment] 2016-05-22 14:12
:+1:
