### ISSUE TITLE
PHP 8.2 Fatal Error if you log as another user from admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4999] opened 2023-05-19 11:39 UTC
## Bug Description
Functionality Log in as in User Manager fails 

`Fatal error: Uncaught Error: Undefined constant "ADMIN" in ***/class2.php:1308 Stack trace: #0 ***/handlers/user_model.php(655): getperms('0', '0') #1 ***/handlers/user_model.php(523): e_user_model->checkAdminPerms('0') #2 ***/handlers/user_model.php(2094): e_user_model->isMainAdmin() #3 ***/handlers/user_model.php(2065): e_user->loadAs() #4 ***/handlers/user_model.php(1790): e_user->load() #5 ***/handlers/e107_class.php(1215): e_user->__construct() #6 ***/handlers/e107_class.php(2129): e107::getObject('e_user') #7 ***/class2.php(1556): e107::getUser() #8 ***/class2.php(666): init_session() #9 ***/index.php(58): require_once('/data/c/c/cc63e...') #10 {main} thrown in ***/class2.php on line 1308`
 

## How to Reproduce
1. Be a main admin (ID 1)
2. Select user - in my case with admin rights to one plugin
3. Select Log as this user
4. Leave admin area

## Expected Behavior
Working site?

 Thanks

**Comment by Deltik** [comment] 2023-05-20 01:15
This is a duplicate of https://github.com/e107inc/e107/issues/4918, which was fixed by https://github.com/e107inc/e107/commit/fbcef7a3c6e8ba6a42d6aa9692127ff843cede17.

**Closed by Deltik** 2023-05-20 01:15 UTC
Labels: type: bug
