### ISSUE TITLE
List new plugin work wrong

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#2049] opened 2016-11-20 18:05 UTC
The list new plugin work wrong. The right menuarea go into the left content (only on this page)....and the expandit don't work.
Thanks! 
![list](https://cloud.githubusercontent.com/assets/86780/20465024/3c0a5cb2-af54-11e6-9116-ba34f5237de9.jpg)

**Comment by Jimmi08** [comment] 2016-11-21 07:57
@fizi if there is problem with Links plugin, give me more information.

**Comment by rica-carv** [comment] 2016-11-21 09:37
@fizi @Jimmi08 It might be missing HTML closing tags, i've experienced this issue with other plugins, and most of the time it was missing HTML closing tags....

**Comment by fizi** [comment] 2016-11-21 16:09
This is my site: http://fizithemes.hu/e107_plugins/list_new/list.php 
I yesterday upgraded to v2 and I try configure all thinks what previously worked. I use latest Github version. This problem only on the list new page, other page no this problem.
I have other problems too, but then I write them to another location. :(

**Comment by rica-carv** [comment] 2016-11-21 18:02
@fizi Language issue?
I've got a strange behaviour from your site:
When i first visited your link above, the display was mixed up, but on any other page it was right.
Further more, if you change the language to English, you get your list page correctly rendered, so i think it must be something related to the Hungrian version of the list page.....

**Comment by rica-carv** [comment] 2016-11-21 19:59
Are you using the unaltered language files?

**Comment by fizi** [comment] 2016-11-21 20:11
I use original English files and I made Hungarian files for plugin (I made it from admin are and I made manually) the problem same. I tried that delete hungarian files the problem same. :(

**Comment by rica-carv** [comment] 2016-11-21 20:18
Check these ones:
e107_themes/fizithemes_2016/languages/Hungarian.php 
e107_plugins/donation/languages/Hungarian.php 
e107_plugins/facebookbox/languages/Hungarian.php 
e107_plugins/googlead_menu/languages/Hungarian.php 
e107_plugins/googlead2_menu/languages/Hungarian.php

**Comment by Jimmi08** [comment] 2016-11-21 20:21
My guess is that something in chatbox in Hungarian is breaking output of this plugin. It get broken in this place:
![image](https://cloud.githubusercontent.com/assets/5429548/20499135/6037fb94-b030-11e6-820c-06bcb0cec3a8.png)

There is nothing similar in English, so it works.

**Comment by rica-carv** [comment] 2016-11-21 20:25
More weird is why the chatbox is different in both languages...
That [link] tag was written by the chatbox poster, right?

**Comment by rica-carv** [comment] 2016-11-21 20:26
It might be a failure of the [link] bbcode... try to recreate it on the english chatbox...

**Comment by fizi** [comment] 2016-11-21 20:46
so...I recreated chatbox message with link on English language. The problem appears. I delete the message with link. No problem. After this I delete chatbox message on the Hungarian language and page appears normally.
So...rica-carv said - probable the [link] bbcode is wrong.
Thanks for the quick and selfless help!

**Comment by rica-carv** [comment] 2016-11-21 20:51
Supposedly, the [link] bbcode should have an url in it, it's not supposed to be empty....
Further more, in your chat it seems to be used empty, so i dunno what haapens when bbcodes are entered like that in chatbox....

Another thing, that might be also translation related, your page title in Hungary is only "Fizi Themes", while in english turns out "List New Items - Fizi Themes".....

**Comment by fizi** [comment] 2016-11-21 21:04
I don't know why the title different. I upgraded my website from v1.04 to v2.1.3 and I work on that the site work normally, because the upgrade not made all thinks right. :(

**Comment by Jimmi08** [comment] 2016-11-22 07:40
@fizi missing title is translation problem. You should use Hungarian pack from here: https://github.com/yesszus/e107-v2.x-Language-Packs/releases
I suppose, that your download plugin doesn't work because you are missing SEF URL values. You can generate them or switch to use old way (with ?id=) in URL preferencies.
I suppose, that your forum plugin doesn't work because htaccess issues. 
(My advice would be to install fresh / not updated e107 and use database you have upgraded ).

**Comment by fizi** [comment] 2016-11-22 15:59
I wanted my site to upgrade the old to the new system, because in it a lot of news, forum posts, etc.. Now I back to the old system. The more I put my questions in the e107 Q & A page.

**Comment by rica-carv** [comment] 2016-11-22 17:42
@fizi I'm currently struglling to have my site on v2.x, but currently got it working with an upgraded v1.4 to v2.x, but it still has some errors, so i decided on a clean v2.x install and start form there & migrate all the data to it. It's hard work, but it can be donne, if you already have a v2.x upgraded database....

**Comment by Moc** [comment] 2016-11-22 17:50
Some comments:

- If there is indeed a confirmed issue with the link BBcode, then please post steps to replicate. Is this only happening when using the Hungarian language pack? 

- Please report individual issues with v1 to v2 upgrading on Github. This way we can solve them and make the upgrade process smoother for everyone, without the need to manually mess with the database. Doing manual changes on the database is not recommended at all, since it may cause severe functionality issues as well as weird bugs which are not truly bugs but rather a consequence of incorrect database modifications. 

- Please keep this Github issue as clean as possible. Stick to one problem and open up a new issue for another problem. Discussions should take place on Gitter (the chatroom). I am asking this in order for us (the contributors/developers/support) to be able to quickly review each issue so we can efficiently make improvements. Otherwise I'll have to scan through all the posts each time I open up the issue again. Thanks! 👍

**Comment by fizi** [comment] 2016-11-22 18:14
Ok! I wrote my problems into the e107 Q & A. The [link] problem appears in English and foreign language. If I put the link into the chatbox (the link URL changed with [link]) and I step on the list new page (list category and items of news - the right menuarea go into the left area.

**Comment by Moc** [comment] 2016-11-23 18:51
> Ok! I wrote my problems into the e107 Q & A.

It is better to post these up on Github (here), but in separate issues for each of your problems. After quickly reading through them I see that most of them are not related.

**Comment by fizi** [comment] 2016-11-23 19:17
Ok!
The [link) failure is still failure.

**Comment by rica-carv** [comment] 2016-11-23 19:21
Have you tryed to post in your chatbox a complete link bbcode: [link]www.google.com[/link]

Just to see what happens....

**Comment by fizi** [comment] 2016-11-23 20:00
I tried the URL directly put into the chatbox and Replace clickable URLs?: enabled on the admin area. In this way the URL changed to [link] (I put this text on admin area for change the URL, but I can give for it -Link- .....this is not the sortcode, this is the text change).

**Comment by Jimmi08** [comment] 2018-01-08 11:17
Could you test if this is still problem?

**Comment by fizi** [comment] 2018-01-08 16:07
This problem solved. (it does not belong here, just note that the plugin is not multilingual)

**Closed** 2018-02-28 13:55 UTC
Labels: awaiting feedback
