### ISSUE TITLE
Response time is too high when visiting Admin area (first time after logging in)

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#2818] opened 2017-10-13 17:14 UTC
As far as I know, it is because of checking available updates for installed plugins. But it has a bad impact on the user experience. I think we should schedule these kind of tasks with Cron. Furthermore, it would be good to have a core pref for enabling/disabling it as in the case of core updates: "Check for e107 updates once/day".

**Comment by CaMer0n** [comment] 2017-10-13 23:51
I agree, the problem is that very few people use or even set up the cron mechanism, so we cannot rely on that. However, we might be able to offset the timing of the lookups by checking the 'last login' time. 
I'm open to suggestions.

**Comment by lonalore** [comment] 2017-10-14 07:11
What about an internal cron handler? By default, it could work by checking at the end of each e107 request to see when cron last ran and if it has been too long, processing the cron tasks as part of that request. This internal cron handler could be switched off if a user want to use or set up a cron deamon or external cron handler. There would be a core pref, e.g:

**Run internal cron handler every:**
- Never (I use cron daemon or external cron handler)
- 1 hour
- 3 hours
- 6 hours
- 12 hours
- 1 day
- 1 week

**Comment by rica-carv** [comment] 2017-10-14 12:17
Didn't php 5.4 has [assynchronous php runs](https://www.phproundtable.com/episode/asynchronous-php)?
Or is it only v7?

**Comment by CaMer0n** [comment] 2017-10-14 20:45
@lonalore The problem with this over cron is that the script can timeout after 30 seconds, no?

**Comment by CaMer0n** [comment] 2017-10-15 01:01
How about we run the upgrade-check scripts via ajax after the login has occurred?

**Comment by lonalore** [comment] 2017-10-15 07:18
@CaMer0n PHP time limit can be overriden with `set_time_limit()` in most cases (almost always). Anyway, 28-29 seconds (depending on how much time page rendering takes) should be enough to run cron jobs. If you call `cron.php` manually (with the correct token of course), it will run in a few seconds. Furthermore, we really need some way to run cron tasks even if the user did not set it up (as daemon). I have met such a solution already in other systems. Other systems also use an internal cron handler (Drupal, WordPress).

Running upgrade-check scripts via ajax should solve this (slow Admin pages) issue, but it's not a solution to run cron jobs.

**Comment by CaMer0n** [comment] 2017-10-15 20:25
Yes, I used to do this with v1.x.  We can place a check inside class2 or the header and then maybe load via Ajax so it doesn't slow down the user experience when it runs.

**Comment by rica-carv** [comment] 2017-10-17 16:20
https://medium.com/async-php/multi-process-php-94a4e5a4be05

**Comment by CaMer0n** [comment] 2017-10-23 23:14
I believe we should first benchmark the login so we know exactly what is causing the long delay. It could be the scanning of files, or of the database.

**Comment by CaMer0n** [comment] 2017-11-07 16:05
@lonalore I believe the problem could be the plugin/theme updates. Would you mind adding this to admin_shortcodes.php at line 1389? Does it help?

	function sc_admin_addon_updates()
	{
		return null;

If so, maybe it could be done with ajax after login.

**Comment by CaMer0n** [comment] 2017-11-16 01:59
@lonalore I have moved the core database update to ajax. I don't think it was the whole problem, but part of it.  Please re-test. Thank you.

**Comment by lonalore** [comment] 2017-11-16 08:44
It's better, but it's still very slow. After clearing cache and re-visiting admin dashboard, it's very slow for the first time (takes 10-15 sec).

Btw I did a small modification in order to hide empty **li** element:
![kepernyokep_2017-11-16_09-30-36](https://user-images.githubusercontent.com/6043821/32881779-992af800-cab2-11e7-8be2-85e81bd25bcd.png)

**Comment by lonalore** [comment] 2017-11-16 08:56
If I disable `{ADMIN_ADDON_UPDATES}` shortcode, dashboard loads under 1-2 sec.

![kepernyokep_2017-11-16_09-54-34](https://user-images.githubusercontent.com/6043821/32882366-6aacf8d2-cab4-11e7-80e0-3feb1bd0e524.png)

**Comment by CaMer0n** [comment] 2017-11-16 20:43
Indeed, this is the main issue. I need to give it the same treatment.

**Comment by CaMer0n** [comment] 2017-11-16 22:23
@lonalore Please try again. I did similar for the addons check. If you find a way to add a slideDown animation when it is added, that would be great!

**Comment by lonalore** [comment] 2017-11-24 18:49
Much better! Dashboar load time is about ~1 sec now.

**Comment by CaMer0n** [comment] 2017-12-02 18:31
Closing! Thanks @lonalore !

**Closed by CaMer0n** 2017-12-02 18:31 UTC
Labels: bug
