### ISSUE TITLE
Problems installing E107 V2.1.2 on PHP 7.1

### ISSUE THREAD

**Issue by joosthv** [e107inc/e107#2145] opened 2016-12-13 20:56 UTC
Dear all, 

Today I tried installing a new and fresh version of E107 on my ftp. 

All fine but after filling in the admin details, i click next to step 6, i get a blanc page showing http error 500. 

Tried several times, reinstalled the files to my FTP and cleaned up my database. 

What to do? 

Screenshot: 
https://scr.hu/BoKjpl

**Comment by rica-carv** [comment] 2016-12-13 21:02
PHP 7.1 issue, perhaps?


Às 20:56 de 13-12-2016, joosthv escreveu:

**Comment by CaMer0n** [comment] 2016-12-13 21:27
@joosthv This may be a PHP 7.1 issue. Please download the latest version for here on Github, and see if that works better for you.

**Comment by joosthv** [comment] 2016-12-13 21:42
I changed my php version to 7.0 and now it works fine.

**Comment by Moc** [comment] 2016-12-13 22:29
If you ever get to test again with PHP 7.1 and the latest Github files, and you still get the error, then please check the apache error logs. The HTTP 500 error will produce more information in the error log, which will help us to get to the cause of the error. Thanks!

**Comment by CaMer0n** [comment] 2016-12-16 20:27
Confirmed. Installation fails during the last step.

**Comment by tgtje** [comment] 2017-01-14 15:51
Update fresh install -latest files dd 14-01-17  ( on Wamp64 php 7.1.0 MySql 5.7.14 ) 👍

**Comment by CaMer0n** [comment] 2017-01-16 02:15
Closing this as fixed. Re-open if necessary.

**Closed by CaMer0n** 2017-01-16 02:15 UTC
Labels: bug
