### ISSUE TITLE
Social plugin issues

### ISSUE THREAD

**Issue by yesszus** [e107inc/e107#2539] opened 2017-03-30 06:04 UTC
Not work for me plugin settings and Facebook, Github and Twitter login / registration.

See this [video](https://www.youtube.com/watch?v=aW82ynEVdcc).

My e107 version: 2.1.6

**Comment by Moc** [comment] 2017-03-30 09:44
Try clearing all your caches (e107 and browser). Does this help?

**Comment by Jimmi08** [comment] 2017-03-30 10:28
I know that this is something different, just to have all related issues in one list.
https://github.com/e107inc/e107/issues/2127

**Comment by yesszus** [comment] 2017-03-31 10:48
@Moc Cleared all e107 and browser caches.
No changes were made.

**Comment by yesszus** [comment] 2017-04-22 12:01
@Moc @Jimmi08 pls test this commits.
Work for me.

**Comment by yesszus** [comment] 2017-05-02 05:21
Ok, now work for me plugin settings.
Not work for me Facebook, Github and Twitter login / registration.

**Comment by CaMer0n** [comment] 2017-09-19 00:03
@yesszus hybridAuth has just been upgraded. Please test again.

**Comment by yesszus** [comment] 2017-09-19 06:37
Facebook login / registration now work for me.

[5]Authentication failed! Twitter returned an error.
Github: [5]Error SQL Insert Error

Would anyone test this?

**Comment by tetolk** [comment] 2017-09-19 06:57
I will test the Twitter part today.

**Comment by yesszus** [comment] 2017-09-19 07:32
And work?

**Comment by Jimmi08** [comment] 2017-09-19 08:00
With LinkedIn I got error (but I have ID and secret key inserted):
 
![image](https://user-images.githubusercontent.com/5429548/30581586-f8ce3412-9d20-11e7-9348-3ca894d0232b.png)

With Facebook login and signup I got notification  Event Triggered: user_xup_login as main admin (for both, login and signup)
Event Triggered: user_xup_login
![image](https://user-images.githubusercontent.com/5429548/30581654-2a0d28bc-9d21-11e7-8476-df861eec66c8.png)

Nothing happend.

**Comment by Jimmi08** [comment] 2017-09-19 10:51
Ok, maybe reason for LinkedIn:

there is this check in Provider_Model_OAuth2.php:
```
    if (!$this->config["keys"]["id"] || !$this->config["keys"]["secret"]) {
      throw new Exception("Your application id and secret are required in order to connect to {$this->providerId}.", 4);
    }
```
but values for $this->config["keys"] are:
![image](https://user-images.githubusercontent.com/5429548/30588930-eb944d0a-9d38-11e7-92a6-8991159f9676.png)

$this->_config() in user_handler.php
![image](https://user-images.githubusercontent.com/5429548/30588960-08d0a634-9d39-11e7-8e31-6b7e8ad1ea3b.png)

**Comment by Jimmi08** [comment] 2017-09-19 11:28
This part of code is confusing and in results it looks like FB signup doesn't work

```
			if($uid = $sql->retrieve("user", "user_id", "user_xup='".$sql->escape($this->userId())."' ".$insert." OR user_loginname='{$userdata['user_loginname']}' OR user_name='{$userdata['user_name']}'"))
			{
				// $this->login($redirectUrl); // auto-login
				e107::getUser()->loginProvider($this->userId());

				if($redirectUrl) 
				{
					e107::getRedirect()->redirect($redirectUrl);
				}
				
				return false;
				// throw new Exception( "Signup failed! User already exists. Please use 'login' instead.", 3);
			}
```
If user with the same user_name exists (in my case) there is no message, nothing, only displaying empty signup form again (because $redirecturl = signup.php
In my case long time ago LinkedIn created user with the same user_name (I forgot it) but with different email and xup. 

After deleting that user, facebook signup works.  But I changed API version on Facebook to 2.8 (before 2.4, latest 2.10) to have the same version as is needed HybridAuth.  I don't know if this is important.

**Comment by yesszus** [comment] 2017-12-12 03:48
Registrations doesn't work.

[5]Authentication failed! Twitter returned an error.
Github: [5]Error SQL Insert Error

**Comment by Moc** [comment] 2018-03-05 08:25
@yesszus @Jimmi08 @tetolk Are the issues above still occurring? If yes, please specify in detail what the issue is and how it can be reproduced.

**Comment by yesszus** [comment] 2018-03-11 08:14
Registrations doesn't work.

[5]Authentication failed!
Twitter returned an error.

Github: [5]Error SQL Insert Error

**Comment by Jimmi08** [comment] 2018-03-18 08:25
LInkedin:
![image](https://user-images.githubusercontent.com/5429548/37563984-2c788afc-2a8d-11e8-8c03-3f3296f16391.png)

This address needs to be added to linkedin to get this work:
![image](https://user-images.githubusercontent.com/5429548/37564007-bb6d3280-2a8d-11e8-8026-2df6b8016254.png)

But admin says
![image](https://user-images.githubusercontent.com/5429548/37564012-d2544358-2a8d-11e8-8336-052f8b828ee1.png)

There is still no message that I am trying to create account with the same email adress that is belong to registered user.

**Comment by net1313** [comment] 2018-05-18 23:30
Everything works. The problem is that you do not know how, or maybe do not want to read carefully. Each provider has its own settings. Including callback url.
e107 social plugin authorization through Facebook, Twitter, Google and Github works great.

**Comment by CaMer0n** [comment] 2018-06-06 17:27
Thank you for the confirmation @net1313 ! :+1:

**Comment by CaMer0n** [comment] 2018-06-06 17:44
Closing.

**Closed by CaMer0n** 2018-06-06 17:44 UTC
Labels: Help Wanted, awaiting feedback, testing required
