### ISSUE TITLE
still log out from admin area

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4130] opened 2020-04-17 15:16 UTC
## Question
I have main admin rights to somebody else site.  It worked normally after installation.

Now, there was some question about the theme and I needed to log in again. 

I am able to successfully log in to admin area (I can see dashboard), but if I click anywhere, I am logged out (Menu Manager, Plugins list, Feature box)

The main admin can work normally.   Except for standard plugins they used Stat visits and Newsfeeds.  

I tried different browser, I cleared browser cache and cookies. But I am using the different network than first time (different IP).  

What can be a problem?

Thanks

**Comment by Jimmi08** [comment] 2020-04-17 16:23
It was definitely by the network (IP) - I switched back to the original network I was logged in the first time and now it is working.

**Comment by Moc** [comment] 2020-04-23 10:07
I don't know if this is related but I have a similar issue on most (if not all) of my installations where I get random logouts, especially after initially entering the admin area and then clicking my first link to another part of the admin area.

**Comment by CaMer0n** [comment] 2020-04-26 17:52
@Jimmi08 Were you using a different account (with '0' perms), or the same account as the owner of the site?

**Comment by Jimmi08** [comment] 2020-04-26 17:59
> @Jimmi08 Were you using a different account (with '0' perms), or the same account as the owner of the site?

Different accounts (no ID 1) but they added main admin rights.  I can't simulate it now, because I am on the same IP (network) like when I log in the first time.

**Comment by CaMer0n** [comment] 2020-04-28 21:36
@Jimmi08 Okay thanks. User tracking was set to Cookies or Sessions?

**Comment by Deltik** [comment] 2020-05-26 07:30
This issue is a duplicate of #1836, and the bug is now confirmed.

**Closed by Deltik** 2020-05-26 07:30 UTC
Labels: type: question
