### ISSUE TITLE
If admin e-mail has a dash in it, e107 won't install properly

### ISSUE THREAD

**Issue by Brooniee** [e107inc/e107#950] opened 2015-04-02 18:00 UTC
Hi there,

I've been puzzled with trying to install e107 beta, always getting a blank screen, but I've found the cause!

The e-mail address I've been trying to install with is @xxxxx-xxxxx.co.uk

I also own the domain with the dash, @xxxxxxxxx.co.uk

If I try to install with the support @xxxxx-xxxxx.co.uk domain, the install completes, but news.php/all other pages displays as blank with no HTML source code.

If I try to install with the support @ @xxxxxxxxxx.co.uk domain, it's works fine.

**Comment by CaMer0n** [comment] 2015-04-03 06:57
Could you please add the following to your e107_config.php and see if any error notice appears?

define('e_DEBUG', true);

**Comment by CaMer0n** [comment] 2015-04-05 19:27
I have tried to reproduce this locally, but the installation continues as normal. Do you have mod_security running?

**Comment by Brooniee** [comment] 2015-04-05 19:30
Ah sorry, I've tried to reproduce again but it's white screening with the dash. So totally different issue.

I'll try the debug option shortly, but I'm seeing no output whatsoever in the source code after install completes...

---- Cameron wrote ----

**Comment by CaMer0n** [comment] 2015-04-06 17:54
Thanks, your PHP error logs should explain what the issue is.

**Comment by CaMer0n** [comment] 2015-04-14 08:32
@Brooniee Any progress?

**Comment by Brooniee** [comment] 2015-04-14 09:17
Will try again tonight and let you know. 

Sent from my Sony Xperia™ smartphone

---- Cameron wrote ----

**Comment by Brooniee** [comment] 2015-04-14 21:02
@CaMer0n worked ok on one domain, but trying to install on the problematic one is the same result.

the page with the debug setting on only displays:
34

**Comment by Brooniee** [comment] 2015-04-14 21:05
(both domains are on the same server)

**Comment by CaMer0n** [comment] 2015-04-24 07:38
Hmm, I would probably need to take a look at your setup to track down the problem. 
If you are willing to send me a URL and FTP access, you can send it to me by Private Message by logging in at http://e107.org/developers and clicking "Send New Message" to 'admin'.

**Comment by CaMer0n** [comment] 2015-05-08 17:53
@Brooniee what do you think?

**Comment by Brooniee** [comment] 2015-05-08 17:55
Sorry, keep meaning to come back to the this. Involves configuring up an FTP server for you as I use scp. 

Sent from my Sony Xperia™ smartphone

---- Cameron wrote ----

**Comment by CaMer0n** [comment] 2015-05-08 17:58
@Brooniee I can work with scp too, if you are able to give me some kind of jailed access to the e107 root.

**Comment by Brooniee** [comment] 2015-05-08 18:17
I'll see what I can do. 

Regards 

Sent from my Sony Xperia™ smartphone

---- Cameron wrote ----

**Comment by Moc** [comment] 2015-10-24 12:57
@Brooniee Any updates on this?

**Comment by Brooniee** [comment] 2015-10-24 13:20
I did private message with scp access, but never got a response.

Sent from my Sony Xperia™ smartphone

---- Tijn Kuyper wrote ----

**Comment by Moc** [comment] 2015-10-24 14:16
All right, thanks for the update. 

@CaMer0n Did you receive the PM?

**Comment by CaMer0n** [comment] 2015-11-05 19:13
I didn't. Please just login at http://e107.org/developers and use the "Contact" page on the site. Thanks.

**Comment by Moc** [comment] 2016-03-11 12:46
Closing this as I think the issue is no longer present. In case it is, please comment and I'll re-open.

**Closed by Moc** 2016-03-11 12:46 UTC
Labels: bug
