### ISSUE TITLE
info:  not displaying captcha

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#604] opened 2014-05-26 21:54 UTC
Captcha stopped to work when you changed name of e107_images folder (tested, with changed or deleted htaccess too) 

And you can't change e107_core and e107_web folder's name via e107_config (otherwise you got blank page) Only warning for others. 

I never noticed this before because I always changed folder's name before installation (in install.php and e107_class.php).

**Comment by CaMer0n** [comment] 2015-03-09 20:05
Please add the following to your e107_config.php file - it should allow you to see any errors behind 'blank pages'.

define('e_DEBUG', true);

**Comment by CaMer0n** [comment] 2015-03-09 20:57
Tested today with the following modified setup without any problems - captcha displays correctly as does the rest of e107. 

    $ADMIN_DIRECTORY     = 'e107_admin/';
    $FILES_DIRECTORY     = 'e107_files/';
    $IMAGES_DIRECTORY    = 'e107_images2/';
    $THEMES_DIRECTORY    = 'e107_themes/';
    $PLUGINS_DIRECTORY   = 'e107_plugins/';
    $HANDLERS_DIRECTORY  = 'e107_handlers2/';
    $LANGUAGES_DIRECTORY = 'e107_languages/';
    $HELP_DIRECTORY      = 'e107_docs/help/';
    $MEDIA_DIRECTORY	  = 'e107_media/';
    $SYSTEM_DIRECTORY    = 'e107_system2/';
    $CORE_DIRECTORY		= 'e107_core2/';
    $WEB_DIRECTORY		= 'e107_web2/';

**Comment by Moc** [comment] 2015-10-24 12:37
Closing this, please re-open if the issue is still present.

**Closed by Moc** 2015-10-24 12:37 UTC
Labels: bug, enhancement
