### ISSUE TITLE
Version for PHP 5.6.x - when?

### ISSUE THREAD

**Issue by TrueHatori** [e107inc/e107#1600] opened 2016-05-01 13:20 UTC
I would like to newly set up the CMS, it does not work properly. I tried it with the v 2.1.1 and also with the Master File of here. In both cases, I have again the problem, which was from CaMeR0n eliminated by me. It makes no sense, now continue to talk and mend times since, whenever a body is repaired, breaks another. Now the archive no longer works (www.ninja4ever.de if you scroll down, you can see it).
When is there a version that works well with PHP 5.6.x?

**Comment by Jimmi08** [comment] 2016-05-01 13:23
Maybe it's related:  https://github.com/e107inc/e107/issues/1597

**Comment by CaMer0n** [comment] 2016-05-01 16:32
@Jimmi08 Yes, I believe it is related. It should be fixed now @TrueHatori

**Comment by Moc** [comment] 2016-05-04 10:47
@TrueHatori Please try updating from Github to see if your issue is resolved.

There is an easy way to sync with Github:
- Enable developer mode in Preferences > Advanced features
- Go to Tools > Database > Sync with Github 

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

**Comment by TrueHatori** [comment] 2016-05-06 11:15
@Moc - sorry, I want a clean system, without residue from 1.0.4, that is, a complete reinstall with a prior complete delete all old files. This does not work when I return only update.

**Comment by Moc** [comment] 2016-05-06 11:38
Alright so in that case, follow the instructions of downloading the zip from Github and use these for a clean install.

**Comment by TrueHatori** [comment] 2016-06-06 22:39
Version from GitHub isn't clean. Look here: [http://www.ninja4ever.de/](http://www.ninja4ever.de/)
Scroll down to archiv and say, this is clean :(

**Comment by Moc** [comment] 2016-06-07 08:04
Is this currently a fresh installation?

**Comment by Jimmi08** [comment] 2016-06-07 08:18
@Moc that problem appears with some old shortcodes. I can't find issue now where this is discussing with @CaMer0n, but old birthday plugin from father barry has the same issue.  That theme probably use bullet shortcode or something.  I would swith to default theme if problem still is or remove bullet from theme, but this is related to old shortcodes.

**Comment by Jimmi08** [comment] 2016-06-07 08:20
I found it, here:
https://github.com/e107inc/e107/issues/1597

**Comment by Moc** [comment] 2016-06-07 08:44
Thanks Jana, labeled as bug.

**Comment by CaMer0n** [comment] 2016-06-07 16:25
@Moc @Jimmi08 Could you please enable news archives on your installations and tell me if you see a similar issue?

**Comment by CaMer0n** [comment] 2016-06-07 18:09
@TrueHatori I am unable to reproduce this problem using the v1.x jayya theme or the v2.x bootstrap3 theme. Are you sure that all your files are up-to-date?

**Comment by Jimmi08** [comment] 2016-06-07 20:35
@CaMer0n  done, no problem, tested with voux and bt3. With defined bullet or available bullet2.gif in theme.  No problem.  (by the way, I didn't know about this functionality before :) )

@TrueHatori   at first, 
- could you tell if problem is related to news archive?  Could you set news archive off and look at result? 
- could you tell if problem is theme related or not? Could you set default bootstrap theme and check result? 

If problem is news archive related, could you tell if:
- has your theme defined template for $NEWSARCHIVE?  
- has your theme defined BULLET constant?

If nothing helps, could you share your theme code? Thanks

**Comment by Moc** [comment] 2018-02-28 11:57
Closing due to lack of feedback, please answer the questions as listed by @Jimmi08 above if this issue is still relevant, and I'll re-open

**Closed by Moc** 2018-02-28 11:57 UTC
Labels: awaiting feedback
