### ISSUE TITLE
forum poll vote

### ISSUE THREAD

**Issue by gary231178** [e107inc/e107#1058] opened 2015-06-16 14:56 UTC
Hi, seems there is a bug which prevents the author of a poll from being able to vote, as when making a choice the submit button says disabled. I also assume that voting in the poll is ip specific as logging in as other users etc prevents the same issue.
Other users able to vote and see the result, but because I can not vote, i therefore are unable to see any results on the poll.
Is there a way to set it for cookie/ip setting? I looked in the poll function which you can set it for polls in menus etc, but nothing specific for forum poll settings.

![screenshot_6](https://cloud.githubusercontent.com/assets/12760959/8186108/3f00a7ce-1440-11e5-9608-88e58350426c.png)

**Comment by gary231178** [comment] 2015-06-16 14:59
Just tried to log out to see if it will let me view results, but still gives me the option to vote / disabled.
Ideally poll needs a setting so that only userclass's can vote rather than public, unless i am missing settings somewhere?

**Comment by gary231178** [comment] 2015-06-16 15:08
I have also noticed, that if you wish to edit the poll, when editing the thread the poll section does not re-appear for editing again, not sure if this is a bug also?

**Comment by gary231178** [comment] 2015-06-16 15:09
![screenshot_7](https://cloud.githubusercontent.com/assets/12760959/8186411/13858900-1442-11e5-88c9-118ed344610c.png)

**Comment by gary231178** [comment] 2015-06-16 15:21
Shouldn't active polls (even those in forum) show as below? If so then is definitely a bug as you can see i have an active poll but the plugin shows none.
![screenshot_10](https://cloud.githubusercontent.com/assets/12760959/8186713/c9d28950-1443-11e5-9f7a-0b61b581b76a.png)

**Comment by Moc** [comment] 2015-06-17 13:18
>  seems there is a bug which prevents the author of a poll from being able to vote, as when making a choice the submit button says disabled. 

Reproduced. Looking into a fix for this. 


> Is there a way to set it for cookie/ip setting? I looked in the poll function which you can set it for polls in menus etc, but nothing specific for forum poll settings.
Ideally poll needs a setting so that only userclass's can vote rather than public, unless i am missing settings somewhere?

Correct. These options can be set for polls used accross the website, but not when used in the forum. Would be a nice feature addition. 

> if you wish to edit the poll, when editing the thread the poll section does not re-appear for editing again, not sure if this is a bug also?

Probably this is intended, I'll check to see if it's easy to change. 

> Shouldn't active polls (even those in forum) show as below?

Probably a bug, will check.

**Comment by Moc** [comment] 2015-06-17 13:43
Pushed two commits. The submit button should now work. The forum polls should now also display in the polls admin overview.

**Comment by gary231178** [comment] 2015-06-17 15:44
Your the Man!! well done and such a quick fix, all confirmed that both commits have resolved both issues.
Regards.
Gary

**Comment by CaMer0n** [comment] 2015-06-17 18:37
:+1: Nice one @Moc

**Closed by CaMer0n** 2015-06-17 18:37 UTC
Labels: bug, enhancement
