### ISSUE TITLE
Email notifications for tracked topics doesn't work

### ISSUE THREAD

**Issue by sanslash332** [e107inc/e107#1524] opened 2016-04-11 23:36 UTC
Hello people,
I have mi e107 installation updated to the comit aea0fd2e53c47c06aa4feaba19043eac343e033c of 09.03.2016.

All of my emails settings Works properly, including confirmation email after signup, request a forget password, etc.
But, when a user has a tracked forum topic, and someone post on that thread a new post, the corresponding notification throug email to the user that has a suscription to that thread it doesn't send.

The email notification setting in the forum settings is enabled, and the track topic option ídem, is enabled too.
And, the set the default action add a email suscription to a answering topic is set to on.

Can you please give me a solution? In the newest updates that problem is solved? Or you need work on it.
Thanks for all.

**Comment by Moc** [comment] 2016-04-12 09:50
It may very well be that this issue is resolved in the latest update. Please try updating from Github before we look into this more closely. 

There is an easy way to sync with Github:
- Enable developer mode in Preferences > Advanced features
- Go to Tools > Database > Sync with Github 

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

**Comment by sanslash332** [comment] 2016-04-13 13:50
Hello @Moc,
O, thanks for the tip on the database setting. I didn't know that option for automatically update the installed e107 on my server.
Well, currently I've updated my installation of e107 on my server using that option (and on mi local machine pulling directly using git (on the server I can't do it because I don't have ssh Access.... dam it)) but the fórum issue is didn't solved.

¿Where i can view a log for email activity on my e107 page? I can't find any log file that says anithing about failed emails, o emails notifications that can't be sent. I have the developer setting turned on.

Thanks for all. I have this problem since I've updated from e107v1.7 to v2.

**Comment by Jimmi08** [comment] 2016-04-13 15:31
@sanslash332 
Try this:
![image](https://cloud.githubusercontent.com/assets/5429548/14498955/b4e75682-019c-11e6-83e9-21c7f6a3a200.png)
In logs in admin:
![image](https://cloud.githubusercontent.com/assets/5429548/14499067/053109c6-019d-11e6-8440-07a5f2a71aa9.png)
and there is file in system folder 
![image](https://cloud.githubusercontent.com/assets/5429548/14499133/4b399ece-019d-11e6-89ce-791eab7ee98f.png)
![image](https://cloud.githubusercontent.com/assets/5429548/14499171/73c2606a-019d-11e6-8145-08f6f09f7424.png)

**Comment by sanslash332** [comment] 2016-04-14 04:35
Hello,

Thanks for your answer and for the tips, but. Can you explain what are you showing in the images?

I’m blind, and I can’t see the images to find these files or options on my installation (if you don’t give me a more detailed description, ofcourse) :P 

 

About the log file in the system folder, nop, I can’t find any file that have anything information about emails. Only other information about access, etc.

 

 

:P

**Comment by Jimmi08** [comment] 2016-04-14 06:38
@sanslash332 
In the email preferencies, in the window where you set smtp connection. 
I really don't know rules for this, it was just try and see method. 
I suppose you need to have debug mode true.
If you check Include email at the log, in txt you will see full sended email.
From this: http://e107help.org/2060/not-sending-emails?show=2060#q2060
You see that I had problems to find that file too - reason for screenshot about folder structure.

Second picture is from log section in admin area.

**Comment by arunshekher** [comment] 2017-05-12 21:23
Is anyone still experiencing no forum email notifications after turning them on in forum plugin preferences? I'm not getting them after a quick test on a v1.0.2 to v 2.1.5 upgraded site.

I don't think '**Mailshot logging**' applies to 'forum email notification' or 'forum topic tracking email notification'. After a quick test I did not get any logs, I think it only applies to bulk mail shots.

**Comment by arunshekher** [comment] 2017-05-12 23:05
I'm sorry Mailshot logging **DOES** log forum email notification mails as @Jimmi08 mentioned. 

By going through mailoutlog.txt I got the below error info for each failed forum notification email:

`21:29:55 17.05.12 - Error info: Could not instantiate mail function.`

In my case I'm using Google's SMTP server and getting signup email as well as admin TEST email without issues.

**Comment by arunshekher** [comment] 2017-05-13 19:55
Sorry again, though bit erratic at times the forum reply notification email seems to work fine. Probably I it didn't seem to work for me initially because I didn't pay enough attention.

But Forum seems not to respect notify be default settings. Using v2.1.6 git

**Comment by Moc** [comment] 2018-02-28 12:08
@arunshekher Can you please clarify if there's still an ongoing issue that needs to be looked into?

**Comment by arunshekher** [comment] 2018-03-12 07:19
@Moc, As far as the local confines of a testing server goes this is not an on-going issue. I tested it on a fresh install of 2.1.8 (git) and it works fine. Didn’t get chance to try on a live server.

**Comment by Moc** [comment] 2018-03-12 15:23
Related #2888

**Comment by Moc** [comment] 2018-03-12 15:24
I'm going to keep this open for a while until I've had time to look at the code. There may be something wrong here.

**Comment by sanslash332** [comment] 2018-03-13 01:47
Hello guys, sorry for don't report in a while. Well, with the current commit that i have installed on my site, ver: 24e6f033bf (i can't find a better number in the settings, this is the number that i find at e107-system/<commit number>) well, the track option at forums works fine. The notifications are sent when somebody post a new reply (and if you have the topic tracked) or when you are mentioned.

thanks :P

**Comment by Moc** [comment] 2018-03-13 08:42
@sanslash332 Thanks for your reply. The string you mentioned is not the version number but the hash for your installation. For security reasons I removed it from your post.

**Comment by Moc** [comment] 2018-03-13 08:42
I am assuming the issue is no longer present in the latest files. Please let us know if anyone is experiencing this issue and I'll re-open.

**Closed by Moc** 2018-03-13 08:42 UTC
Labels: Help Wanted, bug, testing required

**Comment by sanslash332** [comment] 2018-03-13 12:45
a OK, thanks @Moc
For future issues where is the exact version / commit number?

I can't found it at about tab on the settings, or somewhere else on the admin panel.

**Comment by Moc** [comment] 2018-03-19 17:20
@sanslash332 Sorry for the late reply. There is no versioning available in the admin area if you are using the Github version. You could refer to the date when you last updated, or to be more accurate, the latest commit to the e107 repository when updating. For instance `75ff5fc36d56fecbb1ee2181a30d9acadc23bf2e`

**Comment by sanslash332** [comment] 2018-03-20 16:16
OK @Moc, thanks. 
Well is hard to check, because i don't have git exactly on the deploy server, but i can see when i need it for future reports. ¡thanks!
