### ISSUE TITLE
Downloads page, no page change option present

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2032] opened 2016-11-12 18:05 UTC
On the downloads page if you select a catagory that contains more than the display number of downloads in (setting Number of downloads to display per page) then the page does not present you with any way to change to the next page and so you can not see the remaing downloads.

**Comment by tgtje** [comment] 2016-11-12 18:44
@Aaronsss  is it similar to https://github.com/e107inc/e107/issues/1199 ? (although closed) If so maybe needs attention (re-appearing) ?) You could try some posted methods and report back please.

**Comment by Aaronsss** [comment] 2016-11-13 11:39
Nope, I don't believe it’s the same issue. I can display as many downloads per category as I like. The issue here is say I have 17 downloads in one category and my site is set to display 10 per page, there is no button on the page to change to the second page to see the remaining 7.

**Comment by tgtje** [comment] 2016-11-13 11:56
Ok, so next prev issue. Normally ( sorry can not replicate) the next prev for that should display number and button next (or prev). Please try setting (admin/prefs/text) change. Just asking ; using a adjusted download template (other theme as core one) etc..?

**Comment by Aaronsss** [comment] 2016-11-13 17:42
I have tried the following:
Changing the text pref setting "Use 'classic' nextprev look:" - no effect. 
Using the default theme - no effect.
All the files in the downloads and templates folders appear to be in order. 

The bottom of the page just contains "Return to Category List" and how many downloads have been done from the displayed files.

**Comment by tgtje** [comment] 2016-11-14 07:43
Pagination.. might be a tough one when not replicable..Is a url present one can take a look?

**Comment by Aaronsss** [comment] 2016-11-15 21:51
@tgtje [http://sto-gaming.org/p/download/download.php?action=list&id=7](url)

I have left my downloads count set to 14 currently, so its only that catagory not displaying all.

**Comment by tgtje** [comment] 2016-11-16 02:31
Ok, going back 9 days.. by upgrade you had a lot of old files.. there could be the problem. Since as in first post mentioned (some old sc code) might be the same happens here. Download plugin has it own shortcodes  and usesnow templates and different sc calls example : old system the next prev sc was in files/shortcode as nextprev.sc  . In new system it (the nextprev sc) is gone It is replaced (changed) by using nextprev php (core/shortc/single) and has its own template !! core/templates/nextprev_templ...php
Now in the template the pagination is used (line 45 bootstrap start) this should be called/positioned in the download template. In your case (remember i can only look from outside) it seems this does not happen. So i have to base my idea (i do think there is a file missing or too much (in call)) on what i see..
Example hopefully displays what i mean: 
my source : 
`			<div class='text-center'>
			
<nav>
<ul class='pagination'><li class="active disabled"><a  href="#" onclick="return false;" title="Nu bekeken">1</a></li><li><a class="hidden-xs" href="/e107_plugins/download/download.php?action=list&id=15&from=1&view=1&order=id&sort=desc" title="Ga naar pagina 2">2</a></li><li><a class="hidden-xs" href="/e107_plugins/download/download.php?action=list&id=15&from=2&view=1&order=id&sort=desc" title="Ga naar pagina 3">3</a></li><li><a class="next" href="/e107_plugins/download/download.php?action=list&id=15&from=1&view=1&order=id&sort=desc" title="Ga naar de volgende pagina">volgende</a></li></ul></nav>					
			</div>
	
 			</div>
        	<div id="sidebar" class="col-xs-12 col-md-4">`

now the same position from yours : 
`			<div class='text-center'>
								
			</div>
	
 			</div>
        	<div id="sidebar" class="col-xs-12 col-md-4">
`
See the piece missing : that is the template interaction..
The prev/back/next is ok.
Remains another question : did you alter by any chance the dl template (or use it in theme?)

**Comment by Aaronsss** [comment] 2016-11-17 23:25
No, the download template is default and I don't think I modified it in the theme but to be sure I tried it with the default theme and that didn’t change anything.

I synced the directories with a fresh install of 2.1.2 with my FTP client and had a look at the differences, of course there are some but nothing to be concerned about.

I also ran the file inspector and it threw up some errors saying some files are missing but when I navigate to their folder on ftp they exist.

I also tried setting the download.php page to the full version in the theme preferences so there are no menus to interfere this had no effect.

**Comment by tgtje** [comment] 2016-11-18 03:24
Question which php version running?  (notice : your theme (bootstrap) is one version behind by cdn, this should not be off influence).

**Comment by Aaronsss** [comment] 2016-11-18 22:43
I am running PHP version 5.6. The theme is based of the 2.1.1 default theme.

**Comment by tgtje** [comment] 2016-11-20 13:48
I did some installations different php versions (range of php 5) NO replication: all does work as intended.
So since i can not recreate it, i do have to believe it has to be in a file somewhere on the server. (i have seen your running YT plug, but looks not be interferring, as sidenote:  it will wreck your system in php 7)

The only thing i can not test (because of my not be able to replicate) is for you to test if you change prefs to display other numbers to display (instead of 10) and look if that does differ..

Now waiting for others to reply as i do have no other tests leftover.

**Comment by Aaronsss** [comment] 2016-11-21 00:31
I don't intend to up this site to php 7 as there would be much for me to update so its all good.

Changing the number displayed will show however many I define in the settings on the download page, which for the interim is a way around the issue.

One of my other issues (with the forum) was a result of using legacy URL's as opposed to SEF URL's, I wonder could this be a similar thing? Have you tried running it with legacy URL's? I did try to do this but am unable to get SEF URL's working correctly at the moment. (everything gets 404ed that tries using them even when I have enabled modrewrite in the htaccess)

**Comment by Moc** [comment] 2016-11-23 16:50
@Aaronsss Please, stick to one problem at the time in each Github issue. 

As for the download next/prev navigation not appearing. Did you try deleting the `e107_plugins/download` folder and then re-uploading it from Github?

**Comment by Aaronsss** [comment] 2016-11-23 19:35
Yes I have tried it both from the latest github one and from the 2.1.2 instal folder, it has no effect.

**Comment by tgtje** [comment] 2016-11-25 21:23
Well ,took a step back, and just watched the behaviour of the site.. Just to see what is going on.
Now being aware that (older)plugins can have influence on behaviours, there is one, that points out having it;s 'own' next/prev pagination : that is the war plugin... Might be interesting to see if disabling (backup >delete plugin, keep dbase files, remove plugin folder!) if that has some effect. Else honestly no clues..

**Comment by Aaronsss** [comment] 2016-11-26 12:05
I tried what you suggest and it had no effect. I dont beleive the wars plugin uses shortcodes. I will take a look around to see if there is anything similar that does.

**Comment by Aaronsss** [comment] 2016-11-26 12:18
As another thought at teh bottom of the downloads page you can read this: '142 download(s) from 15 files'

Is that intended to be for just the current displayed page of downloads or all in that catagory? If its all in the catagory then it should be out of 17 files. Which may be the reason it presents no pagnation

**Comment by tgtje** [comment] 2016-11-26 13:06
**Intended.** On main page you see the actual amount, on the list page (combi with setting) you see the amount listed on a per page.>  Pagination 'displays' there's more(page/s) than this one.
Test it by clicking the last (Money Tool) so it opens view window. There is the prev/next ..click on next and see number 16...  Server ads  This dl is NOT mentioned in **list** page (as it is hidden being 16 and so on..
So next prev and files are presen, and working, just pagination does not function (display).

**Comment by Moc** [comment] 2016-11-26 13:14
Looking at the debug: `http://sto-gaming.org/p/download/download.php?action=list&id=7&[debug=sc+]` the {DOWNLOAD_LIST_NEXTPREV}` shortcode is called. It just returns no output. I think this requires manual debugging, ie. admin login and FTP access. 

@Aaronsss I suggest contacting Cameron or myself on our chatroom (https://gitter.im/e107inc/e107) to ask for manual debugging of this issue.

**Comment by tgtje** [comment] 2016-11-26 13:28
@Moc ; it is not replicable for me, so (imo) has to be a internal misbehaviour. (next_prev template;  line 45 should be used/working )

**Comment by Moc** [comment] 2016-11-26 13:29
@tgtje I agree. That's why I suggest manual debugging using admin/FTP login :)

**Comment by CaMer0n** [comment] 2017-02-21 00:37
I believe this can be closed. Can any of you reproduce the issue now?

**Comment by Moc** [comment] 2017-02-21 10:35
@Aaronsss Can you please update using the latest files from Github and check if this issue is still present?

**Comment by Aaronsss** [comment] 2017-02-24 22:04
I have tried with the latest files and it has not resolved the issue

**Comment by CaMer0n** [comment] 2017-04-20 01:57
More work was done on this recently.. @Aaronsss please retest.

**Comment by Moc** [comment] 2018-02-28 13:54
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107

**Comment by Moc** [comment] 2019-01-11 16:49
@Aaronsss We are assuming this issue is fixed using the latest files. If this is not the case, please let me know and I'll re-open.

**Closed by Moc** 2019-01-11 16:49 UTC
Labels: awaiting feedback, testing required
