### ISSUE TITLE
How to override admin template?

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#1329] opened 2016-02-05 13:56 UTC
I just want to override "e107_themes/bootstrap3/admin_template.php" because I want to increase the width of left side-bar, becasue it's terrible as it appears, especially on smaller screens.

For example, on 1440x900 resolution (with hungarian translation):
![kepernyokep - 2016-02-05 - 14 44 31](https://cloud.githubusercontent.com/assets/6043821/12848058/c17cc37e-cc17-11e5-8cf7-b0c44c419072.png)

...on 1280x800 resolution (with hungarian translation):
![kepernyokep - 2016-02-05 - 14 44 54](https://cloud.githubusercontent.com/assets/6043821/12848064/cb6ebf90-cc17-11e5-9d6e-3b1f5b0fd5c5.png)

I copied template file to my theme's folder, and I tried to set my theme as admin theme, but it did not work, because (at least I think) only the "bootstarp" and "bootstrap3" themes are approved, according to the line 30 of "e107_handlers/theme_handler.php":
```
private $approvedAdminThemes = array('bootstrap','bootstrap3');
```
So, the question is: "How to override admin template?" to increase the width for left sidebar...

**Comment by CaMer0n** [comment] 2016-02-05 23:44
Overriding is disabled for admin themes. So, we'll need to find a way to fix the core theme and make it look good.

**Comment by lonalore** [comment] 2016-02-08 08:28
Bootstrap list group with badges?

**Comment by lonalore** [comment] 2016-02-08 08:31
Or simply increasing the with for sidebar? Not, it has class "col-md-2". It looks nice with "col-md-3".
And right panel: "col-md-10" => "col-md-9"

**Comment by Moc** [comment] 2016-02-08 12:35
This is how it would look in English with the suggested changes by @lonalore 
@CaMer0n If you agree I can commit... 

<img width="935" alt="dashboard" src="https://cloud.githubusercontent.com/assets/577978/12885783/db5da90e-ce68-11e5-972b-87e563e16950.png">

**Comment by lonalore** [comment] 2016-02-08 13:57
"Hungarian" version. :)
![kepernyokep - 2016-02-08 - 14 56 11](https://cloud.githubusercontent.com/assets/6043821/12887396/3388683e-ce74-11e5-9c6f-3ca3f231414c.png)

**Comment by CaMer0n** [comment] 2016-02-08 18:38
The problem is that on large tables with many fields, we want as much space as possible in the "right" panel. Did you try the Bootstrap list group with badges, did it help?

**Comment by lonalore** [comment] 2016-02-10 08:28
Could we use this layout (with "col-md-3" and "col-md-9") only for admin frontpage?
Layout with "col-md-2" and "col-md-10" could be used by other admin pages.

**Comment by CaMer0n** [comment] 2016-02-10 20:03
@lonalore I have committed some changes. There was some excess padding there leftover from the bootstrap2 version. Please test and send a screenshot. thank you!

**Comment by lonalore** [comment] 2016-02-10 20:19
It's better. :) 

1440x900:
![kepernyokep_2016-02-10_21-16-29](https://cloud.githubusercontent.com/assets/6043821/12960488/d2209764-d03b-11e5-99df-973c48e2a28b.png)

1280x800:
![kepernyokep_2016-02-10_21-17-01](https://cloud.githubusercontent.com/assets/6043821/12960494/db2ff91c-d03b-11e5-927b-6f295844ebda.png)

**Closed** 2016-04-01 12:00 UTC
Labels: enhancement
