### ISSUE TITLE
white page on install - bug

### ISSUE THREAD

**Issue by kreossino** [e107inc/e107#3076] opened 2018-03-15 22:58 UTC
e107_handlers/session_handler.php

PHP Fatal error: Can't use method return value in write context in e107_handlers/session_handler.php on line 904

Errors parsing e107_handlers/session_handler.php
For correct could write “defined” not empty. (http://php.net/defined)

**Comment by Moc** [comment] 2018-03-16 14:00
PHP version please?

**Comment by kreossino** [comment] 2018-03-17 08:13
two webserver:
the first with 2 php-versions. PHP 5.6 and PHP 7.0.27-0+deb9u1 (cli)..
the next this: PHP 5.4.45-0+deb7u2 (cli)

**Comment by CaMer0n** [comment] 2018-03-19 18:21
@kreossino Please try with the latest commit. Thanks

**Comment by SimSync** [comment] 2018-07-09 16:11
@kreossino Could you please verify if the issue is gone?

**Comment by CaMer0n** [comment] 2018-07-16 21:46
Closing this. Line 904 is no longer reachable unless debug is active.

**Closed by CaMer0n** 2018-07-16 21:46 UTC
Labels: bug
