### ISSUE TITLE
PHP 7.1.1 issues (test needed)

### ISSUE THREAD

**Issue by lonalore** [e107inc/e107#2870] opened 2017-11-17 08:22 UTC
The following issues are reported by a user on e107hungary forum, I'm just forwarding them:

1. Cannot be change headlines on news items ~~(I requested more info for this, waiting for response)~~
**EDIT:** Inline-editing on the admin news page is not working under PHP 7.1.1. It jumps to top of the page when clicking on the news title.

2. Wrong/missing plugin names because e107 cannot find language files (I think we should use english files as fallback, if no language files available for the selected language)
3. Cannot select sub-forum in the forum:

**Provided screenshot for issue 3.**
![xampp-hiba1](https://user-images.githubusercontent.com/6043821/32937295-329d6e3a-cb78-11e7-8642-c88596bd4217.png)

**Comment by Jimmi08** [comment] 2017-11-17 09:33
@lonalore 
I confirm that issue with subforum:
https://github.com/e107inc/e107/issues/2852

There is what I tried and what helped.  But why and how to correctly fix it - no idea.

**Comment by tgtje** [comment] 2017-11-17 13:14
@lonalore  is more info (names) available on point 2 ?

**Comment by Norwayman** [comment] 2017-11-17 13:15
I totally agree on point 2 :)

**Comment by Jimmi08** [comment] 2017-11-17 14:52
@tgtje  or core plugin
![image](https://user-images.githubusercontent.com/5429548/32952744-78bf75da-cbae-11e7-97fb-55864e2180d9.png)
and by the way.  if you have plugin with frontend administration, you still needs double all strings in admin and front file. Working with Lang folders is harder that with all files in one folder _languages_. 
What is point to have folders when lang name is part of file name?
Just my 2 cents.

**Comment by tgtje** [comment] 2017-11-17 18:46
> What is point to have folders when lang name is part of file name?
That is/will be always a point of discussion. I can see a much cleaner system, and as translator can focus on not having to oversee other parts. Suppose you are using 6 or 7 languages and all the needed ones are in 'root', bit messy.... (although should work). Another thought would be when developing. Do i use a seperate locale folder or just my own language (as i believe english should always be present to uphold fallback) > eg.. 1 rule for 'how to'. (some side effects there too)

 In long term, i could ( also some tinkering on security) see something (helas no coder and just idea) a system check (ala md5 hash) as a security rule to see if compromise of system (uploaded illegal file(s) folders are part of the system (warning post) etc.... But i stop here.. little going off topic.. (always open for suggestions).

Cause of wrong or missing names.  .. That why i ask for more info as i (due to the coding skills i aproach at a different angle... (eg look at it in another way..)

**Comment by CaMer0n** [comment] 2017-11-17 19:09
Thanks @lonalore . 
Confirming (3) : Cannot select sub-forum in the forum when PHP 7.1 is active. No problem with PHP 5.6 is in use.

**Comment by lonalore** [comment] 2017-11-17 19:50
I got more info, so I updated the first issue in the list.

**Comment by CaMer0n** [comment] 2017-11-17 20:00
Thanks @lonalore I can't reproduce the first issue on PHP 7.1.1. Perhaps a javascript error somewhere? Could it be related to Hungarian?

**Comment by tgtje** [comment] 2017-11-18 16:53
Small post (if lang for list_new Hung. pack misses if (!defined("PAGE_NAME")) { define("PAGE_NAME", "List New Items"); } in Hung...php; made an issue/post on git/content.... )

**Comment by tgtje** [comment] 2017-11-27 19:53
Ok **fresh install of php 7.1.11** (xamp install) No issues on 1 
![issue1](https://user-images.githubusercontent.com/1811857/33286139-def4699c-d3b4-11e7-9bca-b92f3874382c.jpg)

And on 3 also none 

![issue3](https://user-images.githubusercontent.com/1811857/33286170-f623b2da-d3b4-11e7-8f88-edd16fee128b.jpg)

issue 2 remains unknown (for me)..

**Comment by CaMer0n** [comment] 2017-12-10 20:58
Closing.

**Comment by lonalore** [comment] 2017-12-11 10:30
@Jimmi08 where is this setting: "Load language files only for current language"? I've been looking for days but can not find it. :D

**Comment by Jimmi08** [comment] 2017-12-11 10:39
![image](https://user-images.githubusercontent.com/5429548/33827222-e1721206-de67-11e7-9b86-a942881576de.png)

**Comment by lonalore** [comment] 2017-12-11 10:48
Ahh thank you! But the current value is 'Off' on my website, but there are some plugins that do not have a hungarian language file. But english files are not included. 
@CaMer0n It would be possible to modify `e107::lan()` to include default, english files if files (fur the current language) are not available (or not readable, etc)?

**Comment by Jimmi08** [comment] 2017-12-11 11:07
Me too. Not sure now. But if I notice nontranslated strings, I just copy English file as Slovak (with lang folder English/English_  this is double work) with English strings.  But this haven't happend long time so I supposed that this setting (OFF) works.

**Comment by Norwayman** [comment] 2017-12-11 12:44
![languagesettings](https://user-images.githubusercontent.com/1757346/33831597-4beb5cc0-de3e-11e7-8d19-c303a2528348.JPG)

the value on my site is also OFF, but if I do not make a folder named Norwegian or Spanish (with the corresponding files in English if I do not have the sufficient time to translate them) it shows just the LAN strings, so that is why I think we should use english files as fallback, if no language files available for the selected language

**Comment by CaMer0n** [comment] 2017-12-11 18:31
@lonalore The code is already there. I am not sure why it is not working for some people. Perhaps some language files are including language files incorrectly?

```
        public static function includeLan($path, $force = false)
	{
		if (!is_readable($path))
		{
			if (self::getPref('noLanguageSubs') || (e_LANGUAGE === 'English'))
			{
				return false; // pref is "ON" so don't load. 
			}
			
                        // Pref is OFF so load English
			$path = str_replace(e_LANGUAGE, 'English', $path);

			self::getDebug()->log("Couldn't load language file: ".$path);

			if(!is_readable($path))
			{
				return false;
			}
		}
		
		$adminLanguage = self::getPref('adminlanguage');
		
		if(e_ADMIN_AREA && vartrue($adminLanguage))
		{
			$path = str_replace(e_LANGUAGE, $adminLanguage, $path);	
		}
				
		$ret = ($force) ? include($path) : include_once($path);
		return (isset($ret)) ? $ret : "";
	}
```

**Comment by lonalore** [comment] 2017-12-11 19:11
Thank you @CaMer0n I don't use `includeLan()`, I always use `e107::lan()`, for example:

```php
// [PLUGINS]/metatag/languages/[LANGUAGE]/[LANGUAGE]_admin.php
e107::lan('metatag', true, true);
```
And `e107::lan()` uses `e107::coreLan()`, `e107::themeLan()` and `e107::plugLan()`. But as I see... these methods also use `includeLan()`. Interesting...

**Comment by Jimmi08** [comment] 2017-12-11 19:13
@lonalore just to have it complet, this was fixed/changed lately
https://github.com/e107inc/e107/issues/2899

**Comment by lonalore** [comment] 2017-12-11 19:18
The problem is the missing folder name. So,

> ../../e107_plugins/metatag/languages/Hungarian_admin.php

should be

> ../../e107_plugins/metatag/languages/Hungarian/Hungarian_admin.php

![kepernyokep_2017-12-11_20-16-39](https://user-images.githubusercontent.com/6043821/33849198-363be3f0-deb0-11e7-826b-ff6153efc8ef.png)

**Comment by Jimmi08** [comment] 2017-12-11 19:20
@lonalore but that folder is not mandatory. Both version should be working. I don't use this version for my plugins either.

**Comment by lonalore** [comment] 2017-12-11 19:25
So I've always used wrong parameters for `e107::lan()`. Nice... :/ Mea Culpa!

**Comment by lonalore** [comment] 2017-12-11 19:36
OMG....
![kepernyokep_2017-12-11_20-33-58](https://user-images.githubusercontent.com/6043821/33849978-a3e39e64-deb2-11e7-99cf-ade2f9adc045.png)

So I've always used wrong parameters for `e107::lan()` in ALL of my plugins... @%!&!@%!
It will be nice to update all of them...

Anyhow, thank you for the help!

**Comment by lonalore** [comment] 2017-12-11 19:55
> I am not sure why it is not working for some people.

@CaMer0n It may be because they use `e107::lan()` the same way I do/did. Or they use my plugins on their websites. :D

**Comment by Jimmi08** [comment] 2017-12-11 20:00
@lonalore why is your way wrong?  Look at documentation:  (Maybe I don't see something)

![image](https://user-images.githubusercontent.com/5429548/33851103-39397792-deb6-11e7-9fbc-c0cb53134437.png)

**Comment by lonalore** [comment] 2017-12-11 20:04
@Jimmi08 You're right, my solution based on documentation, but documentation seems to be outdated. I checked PHP docs now, but `e107::lan('...', true, true);` is not listed here:
```php
/**
 * PREFERRED Generic Language File Loading Function for use by theme and plugin developers. 
 * Language-file equivalent to e107::js, e107::meta and e107::css
 * FIXME disallow themes and plugins named 'core' and 'theme'
 * @param string $type : 'theme' or plugin name
 * @param $string $fname (optional): relative path to the theme or plugin language folder. (same as in the other functions)
 * when missing, [e_LANGUAGE]_front.php will be used, when true [e_LANGUAGE]_admin.php will be used
 * @param $options : Set to True for admin. 
 * @example e107::lan('theme'); // Loads THEME."languages/English.php (if English is the current language)
 * @example e107::lan('gallery'); // Loads e_PLUGIN."gallery/languages/English_front.php (if English is the current language)
 * @example e107::lan('gallery', 'admin'); // Loads e_PLUGIN."gallery/languages/English/admin.php (if English is the current language)
 * @example e107::lan('gallery', 'admin', true); // Loads e_PLUGIN."gallery/languages/English_admin.php (if English is the current language)
 * @example e107::lan('gallery', 'admin/example'); // Loads e_PLUGIN."gallery/languages/English/admin/example.php (if English is the current language)
 * @example e107::lan('gallery', true); // Loads e_PLUGIN."gallery/languages/English_admin.php (if English is the current language)
 * @example e107::lan('gallery', "something", true); // Loads e_PLUGIN."gallery/languages/English_something.php (if English is the current language)
 */
public static function lan($type, $fname = null, $options = null)
{
	...
}

```

**Comment by lonalore** [comment] 2017-12-11 20:12
I became uncertain now... I don't know which documentation is the good one.

**Comment by Jimmi08** [comment] 2017-12-11 20:15
I am lost too, there is "break" in logic/system in these examples above. 

There should be strict rules and plugins develop should use them.
I use now:
```
e107::lan('creative_writer',true);
e107::lan('creative_writer');
```
So many possibilities and no one what would be load simple English.php if this is because back compatibility.

**Comment by lonalore** [comment] 2017-12-11 20:34
My (currently working) implementations:
```php
// [PLUGINS]/metatag/languages/[LANGUAGE]_front.php
e107::lan('metatag');

// [PLUGINS]/metatag/languages/[LANGUAGE]_admin.php
e107::lan('metatag', 'admin', true);
```
Maybe `e107::lan('...', true, true);` worked before, but it may have broken somewhere... :/

I think it would be a great need to update outdated PHP docs and it would also be a great need to write unit/functional tests for e107 to avoid such misunderstandings.

**Comment by rica-carv** [comment] 2017-12-12 19:04
Maybe i'm wrong, but `e107::lan('...', true, true);` was on the earlyer v2. It was a short lived option, i think...
I've also had that "bug", and had to adapt all my plugins to the new way....

**Comment by lonalore** [comment] 2017-12-12 19:21
It is interesting that `e107::lan('metatag', true, true);` loads `[PLUGINS]/metatag/languages/English/English_admin.php` file if the current language is English. But it tries to load `[PLUGINS]/metatag/languages/Hungarian_admin.php` for hungarian language. I think this is a bug, and the documentation is good.

**Comment by tgtje** [comment] 2017-12-12 23:11
Just adding : It is the 'problem ' i mentioned before (Gitter??) here is _no_ straight rule if files must be on 'root', or inside a locale (country) folder. Where one works with locale files, and others with 'root '  files ('root'= main language folder). The mix of both is throughout.

**Comment by rica-carv** [comment] 2017-12-13 18:27
I think the two options (inside and outside country folder) are there because of legacy complatibility.
Old V1.x plugins and themes don't have the country folder, so the code is that way to make them work too...

**Comment by Jimmi08** [comment] 2017-12-13 19:07
@rica-carv for legacy it would be there option load languages/English.php file.  This is not there as option.

Using folder and language in file name is duplicity.   You have no such case in these examples or I am blind.  

This is correct:  `/English/admin.php `   or this: `/English/admin/example.php`  but not this `/English/English_admin.php`.  

```
* @example e107::lan('gallery'); // Loads e_PLUGIN."gallery/languages/English_front.php (if English is the current language)
 * @example e107::lan('gallery', 'admin'); // Loads e_PLUGIN."gallery/languages/English/admin.php (if English is the current language)
 * @example e107::lan('gallery', 'admin', true); // Loads e_PLUGIN."gallery/languages/English_admin.php (if English is the current language)
 * @example e107::lan('gallery', 'admin/example'); // Loads e_PLUGIN."gallery/languages/English/admin/example.php (if English is the current language)
 * @example e107::lan('gallery', true); // Loads e_PLUGIN."gallery/languages/English_admin.php (if English is the current language)
 * @example e107::lan('gallery', "something", true); // Loads e_PLUGIN."gallery/languages/English_something.php (if English is the current language)
```

**Comment by lonalore** [comment] 2017-12-13 19:35
The problem was: `is_dir(e_PLUGIN.$plugin."/languages/".e_LANGUAGE)` in the condition. Because the (Hungarian) folder does not exist if no translated files, so the condition always returned with false, and the `$path = e_PLUGIN.$plugin.'/languages/'.$fname.'.php';` was used instead of the proper path.

**Closed** 2017-12-13 21:09 UTC
Labels: bug
