### ISSUE TITLE
still problem with installation latest github

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3952] opened 2019-09-14 12:01 UTC
Fresh installation on localhost, different browser that normally I use
index.php

**PHP version 7.2.13**

![image](https://user-images.githubusercontent.com/5429548/64907740-d0822600-d6f6-11e9-8634-3c5e13c2fc4a.png)

admin

![image](https://user-images.githubusercontent.com/5429548/64907760-1a6b0c00-d6f7-11e9-842f-fe6b84243326.png)

**Comment by Jimmi08** [comment] 2019-09-14 12:09
Database compared:
on the left 2.2.1 working

![image](https://user-images.githubusercontent.com/5429548/64907846-3e7b1d00-d6f8-11e9-8a1a-977e9395fd44.png)

this is probably correct, because git version is not working, online t

![image](https://user-images.githubusercontent.com/5429548/64907866-797d5080-d6f8-11e9-9552-6bb36d05a5ef.png)

**Comment by tgtje** [comment] 2019-09-14 13:10
Tested on existing xampp 7.1.1 Chrome : no issues
Tested on xampp 64X  php 7.3.9 apa 2.4.41 mariadb 10.4.6 (newest,fresh) 
For test used Opera (normally also not my standard browser for installments : No issues
Both cases latest github files.... Just to inform

**Comment by Alex-e107nl** [comment] 2019-09-14 19:16
Hi Had the same problem today, called my website 'Demo 05' and that was the problem, 'Demo05' did the trick...

**Comment by Jimmi08** [comment] 2019-09-14 20:05
@Alex-e107nl Nope, I tried e107demo, demo05, demo... still the same result. But thanks for the confirmation that there is a problem.

**Comment by Alex-e107nl** [comment] 2019-09-15 06:39
@Jimmi08 sorry that it did not help, i should mention that i started all over again, so no files left on the server. Complete clean new install and then it worked here with php 7.1, I had exacly the same problems like your first screenshot and server is not locally..

Will try it again..

**Comment by tgtje** [comment] 2019-09-15 08:53
@Jimmi08 maybe you know it, just use it..who knows : http://www.redirect-checker.org/index.php

**Comment by Moc** [comment] 2019-09-15 10:43
Or use define('e_DEBUG', 'redirect'); in e107_config.php. it will show more info about the redirect. 

I'll do some testing Monday to see if I can reproduce this issue.

**Comment by Jimmi08** [comment] 2019-09-15 11:31
It's not about redirect, database core table is not created correct way in some cases..

**Comment by Moc** [comment] 2019-09-15 16:04
Yeah, that's the issue that should have been fixed with the latest files

**Comment by Moc** [comment] 2019-09-16 09:08
I did numerous tests on this with PHP version 5.6 up to 7.3. 
Website name with and without spaces 

I cannot reproduce this. Please verify that this fix is present before you install (or verify on your broken install): https://github.com/e107inc/e107/commit/2a1b4d75dfc5e1a8da477e65d0336193a6c4dcf6

**Comment by Moc** [comment] 2019-10-24 13:18
Still an issue?

**Comment by Alex-e107nl** [comment] 2019-10-24 13:20
Not here, i am going to work with PHP 7.3 will open new one when there are problems :-)

**Closed** 2019-10-24 13:19 UTC
Labels: awaiting feedback, testing required
