### ISSUE TITLE
frontend blank for 2 / 3 hours.

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#819] opened 2014-11-22 09:40 UTC
last night something strange happened.
somewhere between 0:00 and 0:30 hours  the frontend went blank.
rendering stoppped after 4 or 5 lines of header ..  

clearing server and browser cache, fiddeling around in de backend (which was still ok) , turning on and off caching .. it all didnt do a thing.

when i was about to restore a backup i tried changing themes.
that really crashed the server and it then went completely *unreachable down for 10 minutes. cpu throught the roof. as it was doing for a while at that time.

(somewhere in this time i did upgrade to the latest git files dont ask why, i did run a git version about a week old. i just felt like doing this. but it didnt help a thing ..  at that time.)
but then .. suddenly..  10 minutes after changing themes .. all started working again. 
(i think that was around 3 am)

we have been checking, - there was noone logged into the server admin,
there was no update running,  the server and apache logs do not show anything weird.
we have been looking for changed files, but except for some cache files noting got changed.

the only thing i do know : there was a huge peak in cpu usage when this happened.

i have been told by others this happened at least once before. 
at that time the site was blank for about 2 houts. 

it almost looks like the server saved an incomplete cache file and statted serving this until 2 houts later it got updated and was ok again. (but why didnt clear cache help here?) 

one good thing tho. #818 disappeared. 
probably the gitupdate that fixed it.

**Comment by CaMer0n** [comment] 2015-01-30 09:35
I have the site stats plugin running and cannot reproduce this. Could it be a server-side restriction? 
A blank page is almost always an error that has been suppressed - checking the logs and/or searching for an error_log file in the root folder and "e107_plugins/logs" folder often provides useful info.

**Comment by willem010** [comment] 2015-02-23 07:49
Cameron, like i told in another issue, i no longer own the site in question, i cant test anything.

i did send all the log files to Moc, there you will find what happened.
(it was a bug in the sitestats plugin, combined with a huge load of custom pages (>5000) using special chars in the titles.
some of the logged lines actually were RTL .. which didnt seem right .. *to left hahaha..

when i got rid of the stats plugin everything was ok,)

**Comment by CaMer0n** [comment] 2015-02-27 21:58
Okay, thank you. Will close it and keep it in mind if others report something similar.

**Closed by CaMer0n** 2015-02-27 21:58 UTC
Labels: bug
