### ISSUE TITLE
Userclass is reset on all user accounts to the one public userclass "Newsletter"

### ISSUE THREAD

**Issue by Bobbycharlton1** [e107inc/e107#3657] opened 2019-02-01 18:18 UTC
I have 56 members on my e107 site.  all have the default 'newsletter' class, with 2 admins and some forum moderators.

I changed my PHP from 7.1 to 5.6 due to another part of my website not working on 7.1 and it has changed every member in my list to ony 2 classes , 'newsletter'  and the new class I created manually.  it removed all forum mods and also admin classes from myself.

**Comment by CaMer0n** [comment] 2019-02-08 18:18
@Bobbycharlton1 Sorry to hear about the trouble. Could you tell me what theme are you using?

**Comment by Bobbycharlton1** [comment] 2019-02-11 15:33
Hi

I am using the theme I downloaded called

Basic-light

All my memberships classes, suddenly reset again to just ’newsletter’ today for no reason?

**Comment by Moc** [comment] 2019-02-11 16:01
Did the hosting provider make any changes?
I doubt it's PHP version/switching related as during development, we switch between PHP versions multiple times. We need to figure out a way to reproduce the issue to be able to solve it.

**Comment by Bobbycharlton1** [comment] 2019-02-11 16:03
Not as far as I am aware. I also have an issue with this theme where the PM menu will not show so unable to send PMs

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Moc** [comment] 2019-02-11 16:06
Please create a separate issue for your problems with the Private Messenger plugin.

**Comment by Bobbycharlton1** [comment] 2019-02-11 17:08
I will keep an eye on my site, and see when and if it next does the class reset

**Comment by Moc** [comment] 2019-02-12 20:30
Could you list all your installed plugins please?

**Comment by Bobbycharlton1** [comment] 2019-02-15 17:16
ok yet again today, I have noticed ALL my members have been reset to default  'newsletter' class.  all other class status have been removed, including admin for myself.  nothing has been changed or altered on the server.  its annoying as I have over 70 member and I have to manually now alter their member classes

**Comment by Bobbycharlton1** [comment] 2019-02-15 17:19
installed plugins 

Chatbox 
Class Membership 
Downloads 
Feature Box 
Forum 
Gallery 
Site Stats 
New Forum Posts 
Newsletter 
Private Messenger 
Poll 
RSS 
Smartsupp Live Chat 
Social 
User 
Voice eXeSystem 
Youtube

**Comment by CaMer0n** [comment] 2019-02-17 23:12
@Bobbycharlton1 I'm guessing, but I highly suspect your problem is due to the "Class Membership" plugin.

**Comment by CaMer0n** [comment] 2019-02-17 23:27
Thank you @Bobbycharlton1 
I thought the "Class Membership" plugin could have been the cause, but it doesn't appear to have any updating of tables in it's code. The problem must lie elsewhere. 

Could you please make a screenshot of the following URL...
( YOURSITE.COM/e107_admin/userclass2.php?mode=main&action=initial )
.. and then post it here. (you can drag-n-drop to the text box)

**Comment by Bobbycharlton1** [comment] 2019-02-18 09:27
![scrren](https://user-images.githubusercontent.com/19687934/52940836-5f94ae80-335f-11e9-9b41-bcbee3d5938e.jpg)

**Comment by CaMer0n** [comment] 2019-02-18 16:54
Thank you @Bobbycharlton1 . You don't have NEWSLETTER selected as a default class, so it is odd that NEWSLETTER is being assigned to everyone when this issue occurs. 
Could you tell me if the userclass change happens immediately after switching PHP versions? I'm wondering if something a user is doing (eg. signup or usersettings change) could be messing with these values. 

For example, to test you could switch your site into maintenance mode, and then change PHP versions back and forth to see if changes occurred in the user classes. (If you have access to PHPMyAdmin I suggest making a backup of the e107_user table in case a change does occur)

**Comment by Bobbycharlton1** [comment] 2019-02-19 12:21
ok I changed my website from 5.6 to 7.0 to 7.1 and it did not affect the user classes, so this is not the issue

**Comment by Bobbycharlton1** [comment] 2019-02-19 12:23
i changed PHP from 5.6 to 7.0 to 7.1 and it did not change the user classes so this is not the issue.  one other thing I did think, I admin the site sometimes from two different Pcs.  the loss in user class may happen when i log into another PC.  not sure i will try that out

**Comment by Jimmi08** [comment] 2019-02-20 21:47
![image](https://user-images.githubusercontent.com/5429548/53126883-6ee34a00-3561-11e9-8751-400fdc4b3f5c.png)
![image](https://user-images.githubusercontent.com/5429548/53126896-7acf0c00-3561-11e9-9882-28af53574597.png)

**Comment by CaMer0n** [comment] 2019-02-20 22:52
@Bobbycharlton1 Do you happen to have any e107 updates which have not been completed? (see here: /e107_admin/db.php?mode=db_update )

**Comment by Bobbycharlton1** [comment] 2019-02-21 15:50
Checked that all upto date



Sent from Samsung tablet.


-------- Original message --------

**Comment by CaMer0n** [comment] 2019-02-22 19:15
@Bobbycharlton1 Are you able to grant me admin access so I can review the system logs?

**Comment by Bobbycharlton1** [comment] 2019-02-22 19:17
Access just to the e107 system?



Sent from Samsung tablet.


-------- Original message --------

**Comment by CaMer0n** [comment] 2019-02-22 19:24
@Bobbycharlton1 Yes, an e107 admin login.  (You may reach me on gitter)

**Comment by Bobbycharlton1** [comment] 2019-03-01 10:17
happened again this morning, all users reset to 'newsletter'

**Closed** 2019-03-02 15:56 UTC
Labels: testing required

**Comment by Moc** [comment] 2019-03-02 16:56
This should noe be fixed. Please.update to the latest files from Github. Then keep an eye on your website. If the reset happens again, please do let us know.
