### ISSUE TITLE
Download listings only 1 per category showing

### ISSUE THREAD

**Issue by leonuk78** [e107inc/e107#1199] opened 2015-10-04 17:27 UTC
Only 1 download is showing in each category.
the downloads are viewable by id or using next button.

![untitled](https://cloud.githubusercontent.com/assets/14966187/10269143/92a30594-6ac5-11e5-8531-38e2ed273a0a.png)

**Comment by tgtje** [comment] 2015-10-10 12:46
I did have similar issue : uninstall the plugin (keep tables) and reinstall. 
Reason this happening? unknown

**Comment by CaMer0n** [comment] 2015-10-13 22:21
I would need a MySQL database dump of the downloads and downloads category tables to trouble-shoot this.

**Comment by Dutchfoxy** [comment] 2015-10-13 22:29
Isn't this an issue with the downloads-plugin? Or is this part of the core?

**Comment by Moc** [comment] 2015-10-14 10:53
@Dutchfoxy Core plugin

**Comment by tgtje** [comment] 2015-11-29 19:01
becoming an issue, new post on e107help, so it is defintely a bug imo.

**Comment by CaMer0n** [comment] 2015-11-30 22:44
Is each category within a higher category?

**Comment by Moc** [comment] 2015-12-01 10:37
Apparently when reinstalling the plugin while keeping the tables in the database, the issue resolves itself.

**Comment by tgtje** [comment] 2015-12-01 13:06
Correct (for now) as posted as first reaction on top. it does seem to be regarding the action > list where only the first id is present on display; after reinstalling list expands and displays all as should (still trying to replicate it with new install)..No dbase backup to compare with and without error)

**Comment by tgtje** [comment] 2015-12-01 19:30
4 installs later : can not replicate (using latest files). Taken in consideration the 'timeframe' in which issues arise (out of the box thinking), the only thing left (dl is not really changed for min 3-5 months) the one leftover is bootstrap 3 and calls for js/css (cdn). Keeping in mind the posts around that period (end july/aug/sept) in regard to styling issues on forum as example which was first push to cdn, it could well be the cause, because no actual version (date) is really known from users; not everybody uses the sync or latest.

**Comment by CaMer0n** [comment] 2016-01-26 02:51
Closing this for now. If someone else comes across this problem, please try running "Repair" from the Plugin Manager on the downloads plugin.

**Closed by CaMer0n** 2016-01-26 02:51 UTC
Labels: bug, testing required
