### ISSUE TITLE
[Banner plugin issue] counting every render (even on admin panel)

### ISSUE THREAD

**Issue by nesjett** [e107inc/e107#1390] opened 2016-02-28 13:24 UTC
Well, I dont know if this is a bug or you did it that way, but I think that when you are managing a campaign, or editing them, your page prints shouldnt increase the impresions count.

Grts
- Nes

**Comment by CaMer0n** [comment] 2016-02-28 15:48
@nesjett Please provide the steps to reproduce. You are using the latest files from here on Github, correct?

**Comment by nesjett** [comment] 2016-02-28 17:00
I´m surprised because it stopped happening when I was trying to tell you an answer, but I found the path to make it happen.

Im using the github version, but downloaded some days ago.

When you create your first campaign, you activate the banner menu on the web, and you config the menu to show the newly created campaign (I also checked that the ad was showing on the menu), if you go to the campaigns page you will get a new impression for every hit of this page (if you press f5 you will get one new impression), you will get 2 new impressions if you access to manage this campaign (1 for the campaign page, and other for the manage page)


Not sure if this happens when you have more than one campaign created.

After some time without accessing the campaign page, it stopped occuring.

Maybe are you using some kind of cookie to track the clicks? or some kind of cache?


Grts
- Nes

**Comment by CaMer0n** [comment] 2016-02-28 18:14
@nesjett hmm, it only increments the impressions when the banner is rendered. The method used to render the banner in the admin area is completely different. I can't understand why you would experience that.

**Comment by nesjett** [comment] 2016-02-28 18:53
I´ve created more campaigns and this keeps happening only to the first one (the one which I aded to the menu)

![screenshot_14](https://cloud.githubusercontent.com/assets/7051231/13381160/e60576b0-de54-11e5-9122-a8c26ffca544.png)

**Comment by Moc** [comment] 2019-09-25 09:38
I cannot reproduce this at all. Refreshing the Admin Area > Banner area (either on the manage page where all banners are displayed, or when editing a specific banner. 

I added multiple campaigns, showed the menus on pages with different templates. 

I am closing this issue, but feel free to comment and I'll re-open if other people are able to reproduce this as well.

**Closed by Moc** 2019-09-25 09:38 UTC
Labels: plugin: banner, testing required
