### ISSUE TITLE
Spanish characters converted automatically in WYSIWYG

### ISSUE THREAD

**Issue by OliverTenerife** [e107inc/e107#4105] opened 2020-02-19 11:36 UTC
Hi, I recently installed the newest version, 2.2.1, and when I try to paste in any new page or article any text with spanish charecters, like for example á é ñ, or when I write it directly and save the page (or article), they are automatically transformed into Ã¡ Ã© Ã±Â  respectivelly.

So there is no way to write in spanish.

I checked the database charset and is all correct un utf8_general_ci. 
There are no errors in the database.
I haved tried to change from english to spanish language in the admin section with no results.
When I disable WYSIWYG, using with the clasic editor, everything goes well.
In Fileinspector is everything OK.

So I don't know what to do.

I attached a GIF so you can have an idea about what happeds. I first write á, then I copy-paste and that happeds. But also happends when I safe the page/article.

Thanks,

Oliver.

![error-WYSIWYG-spanish](https://user-images.githubusercontent.com/5391264/74830763-be428e80-530b-11ea-94a1-2e5bf89410ff.gif)

**Comment by tgtje** [comment] 2020-02-19 13:24
The Spanish languagepack is still not complete helas
Put the complete content in (just upload by ftp) in the plugin folder onto tinymce4, this maybe will get you helped   (overwrtie recognizes the folder nam (no issue as it is the same, but will add the internal folder langs/an the es,js file inside it)
success

**Comment by OliverTenerife** [comment] 2020-02-19 14:10
> The Spanish languagepack is still not complete helas
> Put the complete content in (just upload by ftp) in the plugin folder onto tinymce4, this maybe will get you helped (overwrtie recognizes the folder nam (no issue as it is the same, but will add the internal folder langs/an the es,js file inside it) (i can not guarantee if your system runs in spanish, so it is a guess)
> 
> [tinymce4.zip](https://github.com/e107inc/e107/files/4225283/tinymce4.zip)
> 
> success

Thank you very much, I cleaned the broser cache, changed the admin area to spanish, uploaded your code and the menus are now translated, but the writing still not working neither. 

It is a strange behaviour, because sometimes while writing, the browser freezes for a couple of seconds and then all the characters (á, é, ñ, etc), are converted automatically to Ã¡ Ã© Ã±Â ) without any further action. Strange.

**Comment by tgtje** [comment] 2020-02-19 22:35
well i did a little test on tiny wysiwyg , my site itself runs in Dutch
Since i do not know how to 'create' spanish chars i used the windoos virtual keyboard to do this..(set to spanish)
I have no issues with it, same paste texts and added some self typed. all remains the same.
Looks like something is (browser?) has troubles with utf8  .
Make a backup evntually and de-install tinymce from plugin manager, clear cache an re install it.. maybe there's a glitch somewhere.
Some cases can relate to database, but that i can not tell : here are some screenshots
![sp1](https://user-images.githubusercontent.com/1811857/74883040-6a1dc580-5370-11ea-98b3-596a850139e8.jpg)

![sp2](https://user-images.githubusercontent.com/1811857/74883051-7144d380-5370-11ea-8670-4e33368762fa.jpg)

**Comment by OliverTenerife** [comment] 2020-02-20 17:25
> well i did a little test on tiny wysiwyg , my site itself runs in Dutch
> Since i do not know how to 'create' spanish chars i used the windoos virtual keyboard to do this..(set to spanish)
> I have no issues with it, same paste texts and added some self typed. all remains the same.
> Looks like something is (browser?) has troubles with utf8 .
> Make a backup evntually and de-install tinymce from plugin manager, clear cache an re install it.. maybe there's a glitch somewhere.
> Some cases can relate to database, but that i can not tell : here are some screenshots
> ![sp1](https://user-images.githubusercontent.com/1811857/74883040-6a1dc580-5370-11ea-98b3-596a850139e8.jpg)
> 
> ![sp2](https://user-images.githubusercontent.com/1811857/74883051-7144d380-5370-11ea-8670-4e33368762fa.jpg)
> 
> So pasing and typimg make me having no issues here...

You did a great effort trying to help me. Thanks!

I did what you said, de-install the plugin, cleaned the cache and re-install it.

But still the same. :-(

I have tried in 3 diferent computers and also happends when doing it from the mobile version.

**Comment by tgtje** [comment] 2020-02-20 19:19
YW No problem, so on neither of those you get good results.|
It limits either the database collation , or ( i never use fileinspector) theres a corrupted file maybe..
I would suggest download to download the code from here (code page right side green button) download zip, **_delete_** the install file and plain overwrite everything. Your immediatly are up to, let's cal it 2,2 (nearly v2,3) so the very latest files.
Tried it on eventually also home pc? like xampp or wamp?).
After soem reading it used to be described as too much ut8 going on simultanious. *combi of dbase browsers,os and website. Please also look at the pref settings fot text editing (turn off any html thingies (admin only) and no filtering,,iff that makes change... Just pouring out ideas.
Since it seams not replicable, it is very hard to discover the issue behind it. Keep your site in AEnglish if possibble since an outdated or incomplete language pack can make a difference...If you use some 3rd party plugins.....keep an eye on it... those can influence too...

good luck

**Comment by OliverTenerife** [comment] 2020-02-20 22:20
> YW No problem, so on neither of those you get good results.|
> It limits either the database collation , or ( i never use fileinspector) theres a corrupted file maybe..
> I would suggest to download the code from here (code page; right side green button) download zip, **_delete_** the install file and plain overwrite everything. Your immediatly are up to date, let's cal it 2,2 (nearly v2,3) so the very latest files.
> Tried it on eventually also home pc? like xampp or wamp?).
> After some reading it used to be described as too much ut8 going on simultanious. *combi of dbase browsers,os and website. Please also look at the pref settings fot text editing (turn off any html thingies (admin onlyallowed scriting) and no filtering,,iff that makes change... Just pouring out ideas.
> Since it seams not replicable, it is very hard to discover the issue behind it. Keep your site in AEnglish if possibble since an outdated or incomplete language pack can make a difference...If you use some 3rd party plugins.....keep an eye on it... those can influence too...
> 
> good luck

Thanks, anything helps. 

It happends wherever the tinymce is used, also in the front forum post, as I show in the attached capture.

![tinymce error](https://user-images.githubusercontent.com/5391264/74981422-24bdce80-542a-11ea-8b1b-b3fd33b73a94.jpg)

**Comment by Jimmi08** [comment] 2020-02-21 14:06
Hi, at first, install only the English site. It has to work.  I tried it too (á is in my lang too). No problems.  

But something similar happened to me before. It was a problem with xampp (local installation, some bug there). As soon as I moved everything to the live server, problems were gone.

**Comment by OliverTenerife** [comment] 2020-02-24 11:17
> Hi, at first, install only the English site. It has to work. I tried it too (á is in my lang too). No problems.
> 
> But something similar happened to me before. It was a problem with xampp (local installation, some bug there). As soon as I moved everything to the live server, problems were gone.
> 
> I found it, not sure if it's the same. But there is some advice on what to check.
> 
> #2503
> 
> Oh, and last time I had problem with national characters - my editor (PSPad) new version changed default file coding - some automatic way, so it switched to Ascii without my knowing - they already fixed it, but I spend hours with trying to find what is wrong.
> 
> Last thing - I suppose you checked console for any javascript errors if this is only tinymce problem.

Thanks. 
I use notepad++ and there are no problems with the encoding as far as I know.

I have made some advances. I managed to temporally fix the issue of PASTING text with Spanish characters. 
I just deleted the plugin activation from the template file, as I show in the next animation.

![delete-paste-plugin-activation-in-template](https://user-images.githubusercontent.com/5391264/75146569-4ac9c400-56f3-11ea-9047-3ec383c1176c.gif)

What is happening now, is that when I open the html source editor, it transforms the Spanish characters that I have written (e.g. á é í ó ú ñ) into ANSI ones (&aacute; &eacute; &iacute; &oacute; &uacute; &ntilde;), so is very difficult to edit html specially in long postings. (It also transforms spaces).

Furthermore, when I write those Spanish characters in the HTML source editor, they become transformed in the other side. :-\

You can also watch it in the next animation. 

![automatic-transform](https://user-images.githubusercontent.com/5391264/75147569-84033380-56f5-11ea-81ba-376c10b75486.gif)

Ideally, they should stay both sides in utf-8. (I have used e107 from many years, last version 2.1.5, with the same server, and I hadn't that problem before).

When I edit it directly in the database using phpMyAdmin, it stores correctly, but tinyMCE transfroms it while open it in the editor.

I have checked all the code among the diferent files of the plugin, but how it transforms the character from one side to the other is beyond my programming knowledge.

**Comment by Jimmi08** [comment] 2020-02-24 11:45
@OliverTenerife Could you please try one other test, please? Install the latest Slovak language pack and try to write something.  
It's important to know if this problem is in your local environment, or only in Spanish translation or in e107 core itself.  I am sure that the Slovak pack works.  try f.e áááá  .

**Comment by OliverTenerife** [comment] 2020-02-24 12:12
> @OliverTenerife Could you please try one other test, please? Install the latest Slovak language pack and try to write something.
> It's important to know if this problem is in your local environment, or only in Spanish translation or in e107 core itself. I am sure that the Slovak pack works. try f.e áááá .
> 
> But I confirm that source code displays HTML entities for national characters. I reported this before.

Thanks Jimmi08.

Here are the results. 

![in-slovak](https://user-images.githubusercontent.com/5391264/75151567-e6146680-56fe-11ea-8c34-fec8d9a69434.gif)

The same occurs.
So how can it happend only for me?

**Comment by Jimmi08** [comment] 2020-02-24 12:15
Wait. You had a problem that you couldn't insert your characters.  
That changing in source code is there a long time...

**Comment by OliverTenerife** [comment] 2020-02-24 12:24
I don't know what happends.

Here is what I did.

- I installed a fresh 2.2.1 (in English) in a new database created in phpMyAdmin.
- In myTinyMCE (pages, articles, forum, etc), I could't paste the Spanish characters (eg. á é, etc). 
- To solve the paste issue, I deleted the paste activation from template file of myTinyMCE plugin.
- Anyway, even though that's resolved, the source html editor transform the characteres (utf-ansi-ascii) in both ways, so there is no easy way to create or edit a post.

I have seen in wysiwyg.php some staff related to the entity_encoding, but I don't know if has something to do.

**Comment by Jimmi08** [comment] 2020-02-24 12:29
Ok, for me is really important to have this fixed or clear...   

So I will test e107 2.3.0 (I can't go back to 2.2.1, it's too old for me)  with Spanish pack, but this: `the source HTML editor transform the characters`  is long term behavior, but you should be able to create pages without changing of tinymce template.

**Comment by OliverTenerife** [comment] 2020-02-24 12:36
> Ok, for me is really important to have this fixed or clear...
> 
> So I will test e107 2.3.0 (I can't go back to 2.2.1, it's too old for me) with Spanish pack, but this: `the source HTML editor transform the characters` is long term behavior, but you should be able to create pages without changing of tinymce template.

Thanks, I will do it.

¿How can I get the 2.3.0? Is the master here in github?

**Comment by Jimmi08** [comment] 2020-02-24 12:39
Sec, I think I found something...

**Comment by OliverTenerife** [comment] 2020-02-24 13:00
> > Ok, for me is really important to have this fixed or clear...
> > So I will test e107 2.3.0 (I can't go back to 2.2.1, it's too old for me) with Spanish pack, but this: `the source HTML editor transform the characters` is long term behavior, but you should be able to create pages without changing of tinymce template.
> 
> Thanks, I will do it.
> 
> ¿How can I get the 2.3.0? Is the master here in github?

Oops, I undesrtood you recomended me to do it.
I did it, downloaded from here, installed 2.3.0 correctly, but it doesn't let me log-in. LOL.
Sorry for the mistake.

**Comment by Jimmi08** [comment] 2020-02-24 13:01
No, I thought that toAscii() is missing Spanish characters, but it's something else.   Similar like here:  https://github.com/e107inc/e107/issues/4101 
But it's not this case.

Ok, so what I did. 
- sync 2.3 to have latest github version
- installed Spanish lang pack (from github, not downloaded zip)
- set Spanish for frontend and English for backend
- I found some Spanish site and I copied some text to existing page content, I added some our characters

![image](https://user-images.githubusercontent.com/5429548/75154109-3c88a180-570d-11ea-953d-e0a927fa5730.png)

Source code is converted but I think it's tinymce issue.
This is saved correctly:
![image](https://user-images.githubusercontent.com/5429548/75154234-97ba9400-570d-11ea-9b3e-3d9d23b220b2.png)
Confirmed in phpMyadmin
![image](https://user-images.githubusercontent.com/5429548/75154274-a903a080-570d-11ea-8b6a-ac534b9c93c7.png)

then I set Backend to Spanish,
I tried to create a new page with the same text. The same result.

**Comment by Jimmi08** [comment] 2020-02-24 13:02
> I did it, downloaded from here, installed 2.3.0 correctly, but it doesn't let me log-in. LOL.
> Sorry for the mistake.

Use 2.2.1, set on developer mode and use Tools/Database/Github Sync to have the latest version.

**Comment by OliverTenerife** [comment] 2020-02-24 13:22
> > I did it, downloaded from here, installed 2.3.0 correctly, but it doesn't let me log-in. LOL.
> > Sorry for the mistake.
> 
> Use 2.2.1, set on developer mode and use Tools/Database/Github Sync to have the latest version.

Thank you very much.

Done, changed to 2.3.0, but same happends (paste issue, and transform characters when html source editor is opened).

**Comment by OliverTenerife** [comment] 2020-02-24 18:20
I have tested in a free hosting website, installed and the paste issue seems to work wright here.

Also, the html source editor, works better, since it does not transform the Spanish characters (e.g. á é í) into ascii characters once closed.

I must keep investigating into the hosting where is located the website, to know what is happening. 
Perhaps the database?

Thanks,

Oliver.

**Comment by Moc** [comment] 2021-12-21 14:58
This is likely to be resolved in the newest version. Please check and re-open in case the issues persists.

**Closed by Moc** 2021-12-21 14:58 UTC
Labels: type: bug
