### ISSUE TITLE
forum got messed up somehow

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3521] opened 2018-10-26 10:15 UTC
This issue is on behalf of @wrxxy
He says that just moved forums (with blue arrows)

In admin:
![image](https://user-images.githubusercontent.com/5429548/47560279-0fa95c00-d918-11e8-9291-a675c477e928.png)

forum with ID 13 is main forum. 

But frontend looks like this:
 
![image](https://user-images.githubusercontent.com/5429548/47560347-3d8ea080-d918-11e8-8e8f-84f0da3db9b4.png)

First main forum is ignored. 
But url is used from main forum
main forum (ID13):   /forum/new-members-introductions/
subforum (ID15):  /forum/newmembersintroductions/

both urls redirect to main forum page.  I am not able to find missing 130 topics

**Comment by Jimmi08** [comment] 2018-10-26 10:56
Just next note:
after moving forums I noticed that sef-url was changed.  As you see at first image, they were different before and they weren't changed manually

 
![image](https://user-images.githubusercontent.com/5429548/47562275-44201680-d91e-11e8-9cb2-073ed49e6dee.png)

**Comment by Jimmi08** [comment] 2018-10-26 11:30
So problem with rewritten ulr stays.

But maybe initial problem is caused by missing class member in UserClasses.   

https://github.com/e107inc/e107/issues/3523
https://github.com/e107inc/e107/issues/3457

**Comment by Moc** [comment] 2019-02-07 12:33
I just tried moving forum categories with the blue arrows. They visually change order, but the new order is not saved for me. Is it the same for you? @Jimmi08 @wrxxy?

**Comment by Moc** [comment] 2019-02-07 13:34
Debug shows the any SEF url starting with 'new' is matched;

```
e_URL in forum with key: new matched ^forum/new? and included: e107_plugins/forum/forum.php with $_GET:
Array
(
    [newmembersintroductions/] => 
)
```

**Comment by Moc** [comment] 2019-02-07 13:50
I cannot reproduce anything with the SEF URL changing after moving the forum order.

**Comment by CaMer0n** [comment] 2019-02-08 19:14
@Moc I'm thinking this:` '^forum/new$/?'` so the after slash becomes optional.

**Comment by Moc** [comment] 2019-02-09 15:41
@CaMer0n 👍 Committed.

**Comment by Moc** [comment] 2019-02-20 11:41
This issue is fixed, closing.
Issue #3545 remains open, a tricky one as the current forum structure seems broken.

**Closed by Moc** 2019-02-20 11:41 UTC
Labels: plugin: forum, testing required
