### ISSUE TITLE
view download from admin ui doesn't work 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3319] opened 2018-07-26 10:32 UTC
URL setting for download plugin:

![image](https://user-images.githubusercontent.com/5429548/43257233-8996d218-90cf-11e8-9b3d-388a5274d151.png)

Frontend link (works)
`site/download/1/download-sef-url`

This url:
![image](https://user-images.githubusercontent.com/5429548/43257332-cde2b996-90cf-11e8-80af-1bab94efacba.png)

`site/download/view/item?id=1&name=download-sef-url`

**Comment by CaMer0n** [comment] 2018-08-15 00:32
@Jimmi08 Duplicate of #3379 . Closing.

**Closed by CaMer0n** 2018-08-15 00:32 UTC
Labels: bug
