### ISSUE TITLE
Page/ Menus problem

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3831] opened 2019-06-06 20:14 UTC
In Menus should be listed only record where menu name is filled.
Now it displays all records.
 
![image](https://user-images.githubusercontent.com/5429548/59063186-d4a4d900-88a7-11e9-99e1-d4f145942502.png)
 
![image](https://user-images.githubusercontent.com/5429548/59063220-e8e8d600-88a7-11e9-8cf5-ea30a556bd20.png)

Plus search is searching only menu body, not menu title (name)

**Comment by CaMer0n** [comment] 2019-06-06 21:28
@Jimmi08 In a recent change it also checks if Menu-title is not empty when retrieving the list. Can you please confirm if those items have a Title value or not?

**Comment by Jimmi08** [comment] 2019-06-06 21:30
There are imported data. Page content:

```
		<item>
			<field name="page_id">1</field>
			<field name="page_title">Log Cabin</field>
			<field name="page_sef">portfolio_01</field>
			<field name="page_chapter">2</field>
			<field name="page_metakeys"></field>
			<field name="page_metadscr"></field>
			<field name="page_text"><![CDATA[[html]<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>[/html]]]></field>
			<field name="page_author">1</field>
			<field name="page_datestamp">1466170560</field>
			<field name="page_rating_flag">0</field>
			<field name="page_comment_flag">0</field>
			<field name="page_password"></field>
			<field name="page_class">0</field>
			<field name="page_ip_restrict"></field>
			<field name="page_template">default</field>
			<field name="page_order">10</field>
			<field name="page_fields"></field>
			<field name="menu_name"></field>
			<field name="menu_title"></field>
			<field name="menu_text"></field>
			<field name="menu_image">{e_THEME}freelancer/install/cabin.png</field>
			<field name="menu_icon"></field>
			<field name="menu_template"></field>
			<field name="menu_class">0</field>
			<field name="menu_button_url"></field>
			<field name="menu_button_text"></field>
		</item>
```

**Comment by CaMer0n** [comment] 2019-06-07 03:38
@Jimmi08 Please feel free to have a play around: 

Line 707 of `e107_admin/cpage.php`
```
$this->listQry = "SELECT SQL_CALC_FOUND_ROWS p.*,u.user_id,u.user_name FROM #page AS p LEFT JOIN #user AS u ON p.page_author = u.user_id WHERE (p.menu_title != '' OR p.menu_name != '' OR p.menu_image != '' OR p.menu_icon !='') "; 
```

**Comment by Jimmi08** [comment] 2019-06-07 17:10
@CaMer0n  I can see it now. Image or icon is tested too. But this is not correct. 

You can create menu only with image/icon,  you always need to fill name. 
`You must enter either a page title or a menu name.`  
So you never have a menu only with an image or icon. 

That test should be only for the menu name field.

**Comment by CaMer0n** [comment] 2019-06-08 15:32
@Jimmi08 What has me curious is how your menu_title has a value?

**Comment by Jimmi08** [comment] 2019-06-08 17:09
No, see xml example above - only menu_image is used

**Comment by CaMer0n** [comment] 2019-06-08 17:40
@Jimmi08 Yes, I saw already. Could you do an export directly from phpmyadmin?

**Comment by Jimmi08** [comment] 2019-06-08 17:59
```
INSERT INTO `e107_page` (`page_id`, `page_title`, `page_sef`, `page_chapter`, `page_metakeys`, `page_metadscr`, `page_text`, `page_author`, `page_datestamp`, `page_rating_flag`, `page_comment_flag`, `page_password`, `page_class`, `page_ip_restrict`, `page_template`, `page_order`, `page_fields`, `menu_name`, `menu_title`, `menu_text`, `menu_image`, `menu_icon`, `menu_template`, `menu_class`, `menu_button_url`, `menu_button_text`) VALUES
(1, 'Log Cabin', 'portfolio_01', 2, '', '', '[html]<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia neque assumenda ipsam nihil, molestias magnam, recusandae quos quis inventore quisquam velit asperiores, vitae? Reprehenderit soluta, eos quod consequuntur itaque. Nam.</p>[/html]', 1, 1466170560, 0, 0, '', '0', '', 'default', 10, '', '', '', '', '{e_THEME}freelancer/install/cabin.png', '', '', '0', '', '');
```

**Comment by sudakk** [comment] 2019-07-02 16:48
@Jimmi08 I don't understand problem... For example, I have custom pages and I want to make visual menus for it with custom menu template (I don't need Name or Title, just Description and Image). So I fill description and choose image, and can see my menu without name & title. It's good because I can filter menus for my custom pages by menu template... It's usefull.

**Comment by Jimmi08** [comment] 2019-07-02 17:49
@sudakk 
` I have custom pages`
exactly, you have pages, not the menu.  So your page shouldn't be listed between menus. If you want a menu, you need to fill the menu name. 
 To see both, pages and menus, there is Overview option.

**Comment by sudakk** [comment] 2019-07-03 03:22
@Jimmi08 I just mean that it is convenient for me to see the menu without name and title. I do not consider it a bug.

**Comment by Jimmi08** [comment] 2019-07-03 05:00
Can you use it in Menu manager. NO. So its not menu. If you have missing functionality in pages or overview, ask for it. It has no logic and it wasnt this wsy before. I would like to know how you explain now what its menu in e107 for somebody new. Try.

**Comment by sudakk** [comment] 2019-07-03 13:16
I can... Only last edited.
![1](https://user-images.githubusercontent.com/11300090/60594494-cade9a80-9dad-11e9-9eaf-c45bd7ffdcfd.png)
![2](https://user-images.githubusercontent.com/11300090/60594496-cf0ab800-9dad-11e9-9447-a70dbef0ff46.png)

**Comment by Jimmi08** [comment] 2019-07-03 13:53
Sorry, it's not your problem, I meant this generally - are you kidding me?  So if you have Book/Chapter/Pages system with hundred pages that are using menu image field, all are listed in menu manager? 

This is totally bug, you can't have menu with only ID listed in menu manager. It's nonsense. 
See the result in menu table? What menu is used where?  
 
![image](https://user-images.githubusercontent.com/5429548/60596508-79341100-9da9-11e9-9d7c-ebe684272a2e.png)

By the way. There is bug in Chrome that causes that your menu name is always filled without you knowing about it (2 issues at least are here about this, it's not only this field). So I supposed that seeing IDs in menu manager is caused by this bug.  Otherwise I would ask sooner about this.

Nevermind, if you don't mind, I will end this discussion.  I am so glad that I use old content plugin, not this.  I will not waste time anymore.  If nobody sees the problem here, it's their problem, not mine. 

Thank you for your help, you really helped me to see this in big picture.

**Comment by CaMer0n** [comment] 2019-07-09 19:04
@Jimmi08 You're right, if removing the menu-name hides it in Menu-Manager then technically it is not a menu and shouldn't display here.

**Comment by Moc** [comment] 2019-10-24 10:12
@Jimmi08 Is this still an issue? It seems fixed already. For me in the Menu List only items are displaying that have a menu_name value in the database.

**Comment by Jimmi08** [comment] 2019-10-24 11:30
Still the same, just sync, tested with sql example above.

![image](https://user-images.githubusercontent.com/5429548/67481464-584a4100-f662-11e9-9bf4-62c1088a317a.png)

**Comment by Moc** [comment] 2019-10-24 11:45
The screnshot from phpmyadmin is from the menus table right? And The issue is that those 4 records with an empty 'menu_name' display in the "Menu List" page right? 

It's odd that you have those menus in the menus database table to start with. Do you know how they got there?

**Comment by Jimmi08** [comment] 2019-10-24 12:04
From Freelancer theme. You create the page and you need image, so you use menu image field.  This is very common because page doesn't have an image field. 

no image, sql export here:  
https://github.com/e107inc/e107/issues/3831#issuecomment-500146213

**Comment by Moc** [comment] 2019-10-24 12:47
Hmmmm... 

@CaMer0n 
The current listQry on line 707
`$this->listQry = "SELECT SQL_CALC_FOUND_ROWS p.*,u.user_id,u.user_name FROM #page AS p LEFT JOIN #user AS u ON p.page_author = u.user_id WHERE (p.menu_title != '' OR p.menu_name != '' OR p.menu_image != '' OR p.menu_icon !='') ` 

It checks to make sure that either menu_title, menu_name, menu_image or menu_icon is not empty. 
In the case of @Jimmi08 there menu_image is filled, but it is not a menu. It is is a page which used the menu_image field to display an image. 

1. Would it be OK to just check for menu_title or menu_name not being empty. The assumption here is that every actual menu needs to have a name or title at least. 

2. Do we need to add an image field for custom pages?

@Jimmi08 If you want a quick fix, change line 707 to:
```php
$this->listQry = "SELECT SQL_CALC_FOUND_ROWS p.*,u.user_id,u.user_name FROM #page AS p LEFT JOIN #user AS u ON p.page_author = u.user_id WHERE (p.menu_title != '' OR p.menu_name != ''') "; // without any Order or Limit.

**Comment by Jimmi08** [comment] 2019-10-24 12:56
@Moc 
thanks.  Check menu manager too, you can select menu there too (with no name) 

I don't use pages with image anymore when I have elements, so... but thanks. this could be confusing for new users.

**Comment by Jimmi08** [comment] 2021-09-07 09:18
https://github.com/e107inc/e107/issues/4556

**Comment by CaMer0n** [comment] 2022-03-14 16:40
Closing this.  If the "menu" fields of the page table has any data, then it should be visible and accessible from the Menu list.

**Closed by CaMer0n** 2022-03-14 16:40 UTC
Labels: type: enhancement, core: pages/menus
