### ISSUE TITLE
Email notify option/checkbox for new post in forum does not appear.

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#1343] opened 2016-02-09 18:52 UTC
I can see {EMAILNOTIFY} in forum_post_template.php but it does not put a checkbox on the New Post screen to enable or disable (if default behaviour) like it used to in V1.7.

In fact I don't think the Email Notify works, as even when I enable it 'on by default', I do not get notification of a reply to a new forum thread.  However, I do get a notification if I select to 'Track' the forum post after I create it.

(I am not a coder, just an e107 user)

**Comment by tgtje** [comment] 2016-02-09 20:50
Different settings achieved ? mail has to be enabled 
notify settings enabled ?
forum settings (2) enabled ?
mail working ?
if yes you would see this (files 3-4 days old)
![mail](https://cloud.githubusercontent.com/assets/1811857/12930196/204a8366-cf77-11e5-881a-46bea8299b19.jpg)

**Comment by martyshep** [comment] 2016-02-09 23:25
I do see the Forum Tracking icon and that works, since I installed the latest from repository to fix #784 and if I click the track thread after creating a new post, I do get notified but I do not get notified when I enable email notification ON by default.
![forum - admin area three percenters mcc 2016-02-09 23-22-05](https://cloud.githubusercontent.com/assets/15772899/12934092/0b0cbc78-cf84-11e5-8cf5-0ef19b1ddee3.png)
![forum - three percenters mcc 2016-02-09 22-11-43](https://cloud.githubusercontent.com/assets/15772899/12934108/1fc816a8-cf84-11e5-98b8-44ba4570d888.png)

**Comment by martyshep** [comment] 2016-02-09 23:35
Also I get the same where when Notify TEST run, email received, but when new thread made on forum no email is received.
![admin area three percenters mcc 2016-02-09 23-33-48](https://cloud.githubusercontent.com/assets/15772899/12934346/c755444e-cf85-11e5-9389-4b4510131e15.png)

**Comment by bouncingsoles** [comment] 2016-06-27 13:56
I have this same issue on an upgraded release of e107 from V1 to V2.  Forum email stopped working after upgrade, but using the test events works and other email events like PMs are fine.  The bell notification icon is OFF, but I have set it as on in the admin.  I can reproduce with a clean install from Github on version on 2.1.2.  Newly created forum will not send out thread creation, topic deletes... etc.  
PHP Version => 5.4.16

What is weird is if when in the admin I click New topic created: TEST and set it to a class I get the email, but it says todo in the message.  Is the feature missing?

/e107_plugins/forum/e_notify.php  does have a line that says todo

// TODO - create notify messages + LAN

Let me know if I can provide any more information or assistance.

**Comment by martyshep** [comment] 2016-06-27 20:33
I've told my users to click the bell icon after creating a new discussion thread on forum as the notify by default does not function. I am not sure what the difference between Topic Tracking and Email notification is? Both are configurable separately in admin.

**Comment by bouncingsoles** [comment] 2016-07-02 01:16
I think I see the issue in the code and why forum events are not triggered.  It seems to be in e107_handlers/notify_class.php.  At the very end of the file the code is commented out which is supposed to extend to the e107_plugins/forum/e_notify.php.  The following block of code would extend to the forum notify class, but doesn't fire.  I am just guessing, but I would need a developer to confirm that.  This section at the end is what I am referring to.   

`
/*
        if (isset($nt->notify_prefs['plugins']) && e_PAGE != 'notify.php')
        {
        foreach ($nt->notify_prefs['plugins'] as $plugin_id => $plugin_settings)
        {
        if(is_readable(e_PLUGIN.$plugin_id.'/e_notify.php'))
        {
        require_once(e_PLUGIN.$plugin_id.'/e_notify.php');
        }
                }
                }

*/

`

Inside forum/e_notify.php, which gets extended to by the class has it set as "todo".  

        function forum_nt($data)
        {
                $message = 'todo';
                $this->send('forum_nt', LAN_PLUGIN_FORUM_NAME, $message);

**Comment by Moc** [comment] 2019-10-02 11:47
Fixed in https://github.com/e107inc/e107/commit/e67cf48c84ff31106a80354301bb425781ce777f

To clarify:
- e_notify is used for Notification triggers set in the admin area. The e_notify addon for the forum plugin has been updated in the past years and should be functioning fine now. 
- Email notification in the forum is a functionality from v1 which is slowly being replaced by the Topic tracking functionality in v2. 

There was a bug which caused the email notification checkbox not to appear, this has been fixed. 
I do recommend using the topic tracking method using the 'bell' icon as this is where future developments will focus on.

**Closed by Moc** 2019-10-02 11:47 UTC
Labels: bug, plugin: forum
