### ISSUE TITLE
can't use type userclasses for pref

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3233] opened 2018-06-29 20:04 UTC
It works for field 
(tested with news and ADMINUI_NEWS_VISIBILITY_MULTIPLE defined)

But if I set pref as userclasses this way:
```
'bday_showclass'		=> array('title' => LAN_VISIBILITY, 'type' => 'userclasses',  
			'inline'=>true, 'width' => 'auto', 	'thclass' => '', 'class' => null,  'batch'=>true, 'filter'=>true),
```

it works
![image](https://user-images.githubusercontent.com/5429548/42112448-1d6300d6-7be8-11e8-9223-f6c1df58616d.png)

but it's not saved.

**Comment by CaMer0n** [comment] 2019-01-31 23:37
@Jimmi08 There is a bug with the display, but you still need to set `data='array'` if you want to save multiple values.

**Comment by CaMer0n** [comment] 2019-01-31 23:50
@SimSync If you have time, please take a look at this one. When I do a var_dump($value) inside renderElement() the it returns false instead of the pref array.  The _blank plugin admin area 'Settings' page has an example already there.

**Comment by SimSync** [comment] 2019-02-01 12:35
@CaMer0n I'll check it.

**Comment by SimSync** [comment] 2019-02-01 19:20
Do not! set `data=array` in case of prefs. Use `data=str` instead!
The problem is, that the prefs are saved as an serialized array to the db, which is unserialized automatically on load. When set to `data=array`, the program tries the already unserialized array to unserialize again which than results into a 0 value.

Use the following example to define the userclasses pref field:
`'prefname' => array('title' => LAN_VISIBILITY, 'type' => 'userclasses', 'data' => 'str')`

**Comment by CaMer0n** [comment] 2019-02-01 20:04
Thanks @SimSync ! Odd though, as that would suggest there was never a bug to begin with. 
I just tested it now, and it seems fine with 'str' or even without 'data' defined. 
@Jimmi08 can you confirm?

**Comment by CaMer0n** [comment] 2019-04-11 23:06
@Jimmi08 Is this one still an issue?

**Comment by CaMer0n** [comment] 2019-04-30 17:15
@Jimmi08 Closing, but please re-open if you can reproduce the issue with SymSync's code.

**Closed by CaMer0n** 2019-04-30 17:15 UTC
Labels: bug, core: Admin-UI
