### ISSUE TITLE
Signup blank on Chrome for Mac/iOS

### ISSUE THREAD

**Issue by Minnn** [e107inc/e107#748] opened 2014-08-27 09:03 UTC
Hi all,
When signing up in Chrome (for Mac OS and for iOS), after filling out user details and selecting Register, a blank page loads. I accessed Chrome for iOS through 3G to confirm it wasn't an issue with my network.

This isn't an issue on Firefox, Opera, Safari on the same machine/device - and I tested on Chrome/Win7 and it was fine there too - registration process completes just fine. 

This is a really weird one...I'm wondering if anyone else can confirm or if anything can actually be done about it. There doesn't seem to be any JS errors or anything on the page...and beyond that I'm not sure what to check for. 
I'm not 100% certain this isn't a fault in Chrome, so I've been searching the Chrome product forums to see if there's anything like this (and will let you know if I find anything). But figured I may as well put it here as well and see if anyone else can replicate it/has any ideas.

Cheers,
Min

**Comment by lonalore** [comment] 2016-01-06 11:01
In recent days, we published the new "e107 Hungary" website to provide support for hungarian e107 users. Several people have indicated to us that it is impossible to signup with using Chrome. After submiting the form, a blank page receive them. Any idea what could be wrong?

**Comment by lonalore** [comment] 2016-01-14 10:11
Ok, I've also been this issue, and I think I found the source of the problem: old cookies. 
I always got blank page after submitting the signup form, but after I deleted cookies (with EditThisCookie Chrome extension), the issue is resolved.

**Comment by CaMer0n** [comment] 2016-03-03 01:25
@lonalore Is this still an issue? Did the chrome update fix it?

**Comment by lonalore** [comment] 2016-03-03 05:21
It looks like it is no longer an issue.

**Comment by CaMer0n** [comment] 2016-03-03 22:39
Thanks. Closing.

**Closed by CaMer0n** 2016-03-03 22:39 UTC
Labels: bug, testing required
