### ISSUE TITLE
problem with debugger and jquery

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3685] opened 2019-02-21 09:28 UTC
admin works normally

frontend:
 
![image](https://user-images.githubusercontent.com/5429548/53158054-0b8a0400-35c3-11e9-8928-ce75544d051d.png)

if I set debug mode off, everything is ok

**Comment by Moc** [comment] 2019-02-26 14:19
Cannot reproduce with manually changing the URL to enable debug mode `?[debug=basic+]` but still need to test with debug browser addon.

**Comment by Jimmi08** [comment] 2019-02-26 14:35
Just installed latest version, no custom plugins, bootstrap3 .  Only in Chrome.  
Manual adding debug url in Firefox - no problems.

It's weird.  It looks like jquery.js wasn't not fully loaded (just part of file). After manually refresh jquery.js on separate url in new tab, it works. CTRL-F5 didn't help. Now it works.

**Comment by Moc** [comment] 2021-12-20 19:47
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107

**Closed by Moc** 2021-12-20 19:47 UTC
Labels: status: testing required
