### ISSUE TITLE
Register user template not displaying well on v1 theme after upgrade

### ISSUE THREAD

**Issue by rica-carv** [e107inc/e107#1938] opened 2016-10-17 18:20 UTC
Again, e107 updated from v1.4 to v2.x

This time, bootstrap3 theme renders form correctly (at least i think it's rendered this way...)
![bs3_reg](https://cloud.githubusercontent.com/assets/17130530/19449716/a2e3ed34-949e-11e6-97ad-b389e71e47d2.jpg)

But my v1.4 theme renders it all garbled:
![spt_reg](https://cloud.githubusercontent.com/assets/17130530/19449735/b12be144-949e-11e6-9562-346746fc8ac8.jpg)

Any ideias what's wrong here?

**Comment by MikeyGMT** [comment] 2016-10-18 08:30
I had similar issues and needed to update e107_themes/templates from e107_core/templates - note that you need to back up your current e107_theme/templates and re-apply any customisations you made to these files. If you are usiing the latest GIT repo in live, then you will need to update these each time one of the files is updated or at least on a Major Release. These are being updated (Issue #6) to replace hard coded phrases to translatable lans, replace with generic phrases, remove HTML etc.

**Comment by Moc** [comment] 2016-10-18 09:49
@CaMer0n Can you take a look at this to see if there can be an improvement made in the core to correctly load the updated template?

**Comment by rica-carv** [comment] 2016-10-18 19:54
@MikeyGMT Thanks, that solved this issue...

**Comment by Moc** [comment] 2016-10-19 08:12
Leaving this open to check with @CaMer0n to see if something can be done to make this transition go smoother.

**Comment by MikeyGMT** [comment] 2016-10-19 08:43
@rica-carv no problem :) I faced the same recently. 

I wonder if we can compare the file date/size or similar (no idea how!), hence display a warning in Admin if the template is old? 
Automating it completely may overwrite user customisations in the themes/templates folder.

**Comment by rica-carv** [comment] 2016-10-19 16:35
Maybe use [filemtime](http://php.net/manual/en/function.filemtime.php) and/or [hash_file](http://php.net/manual/en/function.hash-file.php) with a comparison between files in both directories.

**Comment by CaMer0n** [comment] 2016-10-25 01:09
I would need someone who has done a legacy site upgrade to test this..  ( @rica-carv @MikeyGMT  )?
Once the issue is present, comment out the following line (2247) in e107_class.php 

    return $legacy_core_path;

... and then re-test.

**Comment by rica-carv** [comment] 2016-10-25 17:35
@CaMer0n Commenting out the line, it still renders it garbled....

**Comment by CaMer0n** [comment] 2019-04-30 17:51
Just tested registration with e107v4a released in 2003 without any issues. Closing, but please re-open issue if it can still be reproduced with latest code.

**Closed by CaMer0n** 2019-04-30 17:51 UTC
Labels: bug, enhancement
