### ISSUE TITLE
problem with messages in forgotten password and bootstrap 4 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4006] opened 2019-11-04 20:54 UTC
This should be solved in core because this causes that user is not able to change their password (after click on link in email in forgotten password

There is issue somewhere about this with quick fix, but this is not solution. Displaying something so important as password shouldn't depend on messages.

 
![image](https://user-images.githubusercontent.com/5429548/68157324-b8d45a80-ff4d-11e9-97b5-2b380dba5a17.png)

**Comment by Moc** [comment] 2019-11-04 21:41
Closing as duplicate of https://github.com/e107inc/e107/issues/3686

**Closed by Moc** 2019-11-04 21:41 UTC

**Comment by Jimmi08** [comment] 2019-11-04 21:47
@Moc that issue is about the alert, this one is about that user is not able to change their password because using s-message class.  For something like this e107 classes should be used, not bootstrap.

**Comment by Moc** [comment] 2019-11-04 22:35
It's the same underlying issue which needs to be fixed.
