### ISSUE TITLE
Login would not load

### ISSUE THREAD

**Issue by ghost** [e107inc/e107#1870] opened 2016-09-18 19:34 UTC
When members want to login in into the website the page is shown blank.

**Comment by CaMer0n** [comment] 2016-09-19 20:32
@Morris161 This sounds like a bad language file (lan_login.php?) or some other file not loading correctly. What language are you running?

**Comment by Morris161** [comment] 2016-09-21 14:22
Im running the dutch language

**Comment by Moc** [comment] 2016-09-21 16:48
For testing purposes, please try setting the default site and admin language to English and see if the issue still occurs then. Please let us know.

**Comment by Morris161** [comment] 2016-09-23 19:08
Issue still occurs

**Comment by Moc** [comment] 2016-09-23 21:11
It may very well be that this issue is resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in Preferences > Advanced features
- Go to Tools > Database > Sync with Github 

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

If the issue still occurs after updating from Github. Try enabling debug mode. To enable debug mode:

- Make sure developer mode is enabled in the `Settings > Preferences > Advanced features` 
- Use the Firefox e107 debug addon or manually change the URL to /e107_admin/admin.php?[debug=basic+]

Then try to login again. The blank page may now provide an error message. If so, please copy the error message here.

**Comment by Morris161** [comment] 2016-09-24 11:41
The blank page does not give any error message,
This was shown on the debug log:

Couldn't Load: e107_themes/basic-light/theme_shortcodes.php with class-name: theme_shortcodes and pluginName
 	e_parse_shortcode->getScObject()() 	/home/wonders1/domains/5wonders.nl/public_html/e107_handlers/e107_class.php 	1125 
Couldn't Load: e107_themes/basic-light/theme_shortcodes.php with class-name: theme_shortcodes and pluginName
 	e_parse_shortcode->getScObject()() 	/home/wonders1/domains/5wonders.nl/public_html/e107_handlers/e10

**Comment by rica-carv** [comment] 2016-09-24 14:21
Isn't basic-light an old v1.x theme?

**Comment by Morris161** [comment] 2016-09-24 20:16
By the way how can i turn ''debug mode'' off?

**Comment by Moc** [comment] 2016-09-25 15:23
> By the way how can i turn ''debug mode'' off?

- Use the Firefox e107 debug addon or manually change the URL to /e107_admin/admin.php?[debug=none-]

**Comment by Moc** [comment] 2016-09-25 15:29
Please provide the following information:

- When exactly does the blank page occur? 

For example: after a user tries to log onto your website by entering their user/pw in the login menu? 
-
 Please try setting the default language to English again, then clear the caches (`Admin Area > Settings > Cache > Empty all caches > Delete). After having done so, please test if the issue still occurs.

**Comment by Morris161** [comment] 2016-09-26 16:12
Issue still occurs

**Comment by Morris161** [comment] 2016-09-26 16:14
It occurs when i want to login with the 'login' menu, When i login with the admin panel it works.

**Comment by rica-carv** [comment] 2016-09-26 16:31
Once more, it might be a theme issue. Try change to the default bootstrap3 theme and see if the issue still occurs.
Again, i can see the login menu on your site:
![login](https://cloud.githubusercontent.com/assets/17130530/18842998/e9c48ede-840e-11e6-9fd9-dc640773e0b9.jpg)

& for me, it's working...
![login error](https://cloud.githubusercontent.com/assets/17130530/18842997/e9c3dac0-840e-11e6-953b-d751ef3560bc.jpg)

**Comment by Morris161** [comment] 2016-09-26 19:51
Correct, Only a few people got the problem

**Comment by tgtje** [comment] 2016-09-27 16:31
Do see the same as @rica-carv (so no argue there)..

The debug message is because there is no theme shortcode in this theme (MAW v2 theme).

The only other what remains (i follow Cameron in that) is language related. _The site reports to run in Dutch, but the html tag is english... (that should not happen)_. Also going through site, Dutch is not fully present.. Most of all that is in use is translated. > question what version (date ) is Dutch ? (the latest is waiting as pull request) ( you can either wait untill merged or for time being get it here : https://github.com/tgtje/e107-v2.x-Language-Packs.. this is the one committed for merging)

**Comment by rica-carv** [comment] 2016-09-28 16:26
@Morris161 
> Correct, Only a few people got the problem

If only a few people got the problem, then it's not e107 fault, it's of that few people!
Ask them to clean theyr web browser cache and try again. If problem persists, ask teh to update web browser to it's latest version, so there's no excuse on using old unsupported web browsers.
If issue sttill persists, then there's a serious end user problem.
But if site login works for most users, it's not e107 fault, guaranteed.....

**Comment by Moc** [comment] 2016-10-04 18:22
@Morris161 Did you try switching back to the default bootstrap3 theme temporarily? Did this change anything?

**Comment by Jimmi08** [comment] 2016-10-27 09:48
I noticed this behaviour from time to time, after login blank page, then refresh (enter or F5) and user is logged in and everything works. Just on one hosting, so I supposed it could be hosting related.  Main admin has no problem (the reason I didn't notice this before), but when normal user log in (not all, just some of them) there is blank page.  No error at all.   (It was version from half of October and Voux theme)

**Comment by Moc** [comment] 2017-04-17 09:17
@Morris161 Is this issue still happening?

**Comment by BlastFM** [comment] 2018-09-06 00:53
I am still having the same problem. I would appreciate some help as I've been chasing this for hours now. https://blastfm.limited login page does not show any form data, it seems to appear and disapear very quickly on page load, as if it's disabled somewhere/somehow but I've checked the settings over and over and can't find the cause.

**Comment by Jimmi08** [comment] 2018-09-06 06:54
@BlastFM What is your version of php?

@Moc it's different issue (Or I will create new one), and original author deleted their account.   Here is discussion that could mislead during solving this.

**Comment by Jimmi08** [comment] 2018-09-06 07:10
It's not php version related.
It's not related if theme template exists.
It's has something with core login template.  Custom login template works.  So now just to find "10 differencies"

**Comment by BlastFM** [comment] 2018-09-06 15:29
@Jimmi08 you are correct in that the template originally was GamePlus Theme by fizi, it is now quite modified though but perhaps the issue is realted to the theme. I can verify that if I switch to the Bootstrap3 theme the problem is gone.

**Comment by BlastFM** [comment] 2018-09-06 15:41
Ok so now for the good news.
The problem exists in the core/template file login_template.php at line 88, the LOGO is overwriting the form fields, the solution, delete line 88.

This is not a perfect solution, I am sure there will be cases where it is nice to have the logo on the login page so perhaps the devs could advise better on what it a good solution.

**Comment by BlastFM** [comment] 2018-09-06 16:03
@Moc You are correct in that there is some little information there to point people in the right direction, but in fact it does not go into enough detail, file names/locations etc. and for that reason I think this should be left here for future explorers.

**Comment by Jimmi08** [comment] 2018-09-06 16:17
@BlastFM see this issue:  https://github.com/e107inc/e107/issues/3420

Please, don't send post to closed issue until it's your issue and you then can reopen it.

**Comment by CaMer0n** [comment] 2018-09-12 17:29
@Jimmi08 @BlastFM Please test the committed change. thank you.

**Comment by Moc** [comment] 2019-02-21 17:53
@BlastFM Is this issue resolved?

**Comment by BlastFM** [comment] 2019-02-21 22:19
@Moc Yes this issue was resolved using the method listed above but as I stated it is clearly not a perfect solution and I had hoped that someone might elaborate on it.

**Comment by Moc** [comment] 2019-02-27 15:32
@BlastFM I meant, is the issue resolved using the commit by @CaMer0n. Anyway. I assume it is seeing @Jimmi08's reply here #3420 

Closing.

**Closed by Moc** 2019-02-27 15:32 UTC
Labels: awaiting feedback
