### ISSUE TITLE
Register member and required fields - missing asterix (*)

### ISSUE THREAD

**Issue by schlrech** [e107inc/e107#1767] opened 2016-07-07 14:41 UTC
I missing the star (*) by the fields there are required.

Birthday is for us a required field. After User logged in then popup the usersettings when missing the birthday. there are 20 extendend fields but nothing have a star (*)  for the required fields.

in the registersite itself there have stars

**Comment by tgtje** [comment] 2016-07-09 12:05
Correct, Required field for **sign up** ! 
Usersettings (suppose change) are using the same (if selected) but not the required > if you demand that field to be a must... talk with user or let him/her sign up again. 
So it is not an issue, but a would like to .. (add option/enhancement).

**Comment by Moc** [comment] 2019-11-14 09:07
@CaMer0n As discussed, missing CSS class for .required

**Comment by CaMer0n** [comment] 2020-04-20 19:39
@Moc I'm unable to reproduce this. How about you?

**Comment by Moc** [comment] 2020-04-20 20:01
According to my comment 5 months ago, I was able to reproduce it but there was no CSS styling that added the Asterix

**Comment by CaMer0n** [comment] 2020-04-21 18:26
Tested with e107v4a, bootstrap3, kubrick, gaia and freelancer.  

![image](https://user-images.githubusercontent.com/2825679/79898742-9e3d5300-83c0-11ea-82e4-56cbb0bdc880.png)

Gaia and Freelancer (@Jimmi08) are missing the extended user fields in their templates.

**Comment by CaMer0n** [comment] 2020-04-21 18:37
USERSETTINGS tested also without issues.

**Comment by CaMer0n** [comment] 2020-05-14 17:14
Closing.

**Closed by CaMer0n** 2020-05-14 17:14 UTC
Labels: type: bug

**Comment by Jimmi08** [comment] 2022-09-28 20:49
needed css

```
.required:before {
  content: "*";
  color: red;
  float: right;
}
```
