### ISSUE TITLE
Review alt_auth plugin

### ISSUE THREAD

**Issue by e107steved** [e107inc/e107#84] opened 2013-01-20 21:58 UTC
Prefs need sorting; try and eliminate globals
Missing method on login

**Comment by Jimmi08** [comment] 2023-12-15 17:16
@Moc this can be closed? Or a better title? Not clear what the issue is. Thanks

**Comment by Moc** [comment] 2023-12-21 15:23
Yeah closing this outdated.

**Closed by Moc** 2023-12-21 15:23 UTC
Labels: type: enhancement, status: testing required
