### ISSUE TITLE
Private Message: 'to' field missing

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#1747] opened 2016-06-29 08:30 UTC
Hi, whatever i do i cannot send a private message, cannot select of enter anything in the To: field.. that is from the front, in the admin it works..  tried to get it to work in the admin with many different settings but no go.. am i the only one?

Alex

**Comment by Moc** [comment] 2016-06-29 16:04
I cannot reproduce this issue at all, can you please try to: 

1) Update from Github and test
2) Switch back to the default Bootstrap 3 theme and test
3) Switch back to the default English language and test

**Comment by Alex-e107nl** [comment] 2016-06-30 11:18
Hi Moc,
1) new e107, github of yesterday... 
2) default Bootsrap 3 theme installed
3) English language selected
Really cannot select a user with PM frontend.. cannot select or type anything.. Just like on e107.nl
Backend works so what can i do to resolve this? I have not changed the standard settings..

**Comment by Moc** [comment] 2016-07-11 14:45
There's a bug somewhere for sure. I just logged in a regular testuser on one of my test websites, and I get the same situation as you. 

![image](https://cloud.githubusercontent.com/assets/577978/16734696/c0776516-4786-11e6-9173-eecefec6e83c.png)

For me the weird thing is, that this only happens when I am logged in as a regular test user without admin permissions. If I login as the head admin (created upon install), it all works as expected.

**Comment by Moc** [comment] 2016-07-11 15:04
Got it. There was a change in shortcodes file recently. 

@Alex-e107nl Here's what to do in order to fix it:
- Delete all files from your current e107_plugins/pm folder (check for attachments)
- Download the ZIP from Github
- Reupload the e107_plugins/pm files from this ZIP to the website 

@CaMer0n Apparently the batch to pm_shortcodes.php caused some issue. Is there some check needed to prevent this issue from happening to other users who are upgrading from previous v2.x installations?

**Comment by Alex-e107nl** [comment] 2016-07-12 13:44
THX!! Moc, deleted e107_plugin/pm/shortcodes  folder and it works!!
In Dutch the tabs are nog so nice yet, i will take care of that :-)

**Comment by CaMer0n** [comment] 2016-07-13 15:02
@Moc Thank you, I'll try to take a look soon.

**Comment by Moc** [comment] 2017-01-17 22:59
Closing this as the admin area now shows a message if the old files are still there

**Closed by Moc** 2017-01-17 22:59 UTC
Labels: bug
