### ISSUE TITLE
Clicking Edit Category directly in News > List does not display drop down menu

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2351] opened 2017-01-30 10:09 UTC
Selecting Edit Category directly in News > List within admin does not display drop down menu, shows **Error when loading list** instead. News item can have category changed successfully when editing the article, just not directly from the list screen. Other edits from News > List work ok, i.e. Visibility.
![news - list - admin area three percenters mcc 2017-01-30 09-57-35](https://cloud.githubusercontent.com/assets/15772899/22419172/25b23900-e6d4-11e6-8616-b6d7349532b8.png)
![news - list - admin area three percenters mcc 2017-01-30 10-05-53](https://cloud.githubusercontent.com/assets/15772899/22419175/2a2f0684-e6d4-11e6-8e5f-fcbbb6c0f32d.png)

**Comment by Moc** [comment] 2017-01-30 15:58
Cannot reproduce so far. 

- Are you using the latest version from Github?
- Can you please list the categories you have, especially those with special characters such as `&`

**Comment by martyshep** [comment] 2017-01-30 17:04
Turns out it was the ' character in What's On it didn't like. Changed this and it works now. The & character is okay and does not cause issue.

**Comment by Moc** [comment] 2018-02-28 14:35
Assuming this is fixed, closing. Let us know if the issue still occurs.

**Closed by Moc** 2018-02-28 14:35 UTC
Labels: bug
