### ISSUE TITLE
White page

### ISSUE THREAD

**Issue by chory** [e107inc/e107#2258] opened 2017-01-08 12:21 UTC
Since Yesterday, after installing the update "Added max-width on all images, as a precaution for upgraded sites.", 
me admin area show a white page, in html code only show
`<html><head></head><body></body></html>`
 and the web only show background image from theme, and html code show
`<html><head>!<--Some Code--></head><body></body></html>`
No changes in server setup

**Comment by Moc** [comment] 2017-01-08 12:34
If you have access to the Apache (server) error log, please check it. There should be an error in this log which tells us what the problem is.

**Comment by Moc** [comment] 2017-01-08 15:38
Please update again, the issue should be fixed. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

**Comment by chory** [comment] 2017-01-08 15:45
I can't acces to Admin Area, show white page  :cry:

**Comment by Moc** [comment] 2017-01-08 15:47
Do you know how to edit php files?

If not, please find Cameron on Gitter. This is a chatroom we use. He can give you individual help: https://gitter.im/e107inc/e107

**Comment by Moc** [comment] 2017-01-08 15:48
Also, if you know how to upload files to your website through FTP, download the latest zip as instructed in my first reply, and overwrite this file: e107_handlers/form_handler.php

**Comment by chory** [comment] 2017-01-08 16:09
jaja, sorry I don't remember and not read this 

> Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

Is all right, work fine
Thank You very, very much

**Comment by Moc** [comment] 2017-01-08 16:10
Good job. Sorry for the trouble.

**Closed by Moc** 2017-01-08 16:10 UTC
Labels: awaiting feedback

**Comment by chory** [comment] 2017-01-08 16:12
Sorry? Why? Your work is fantastic, without this it would not be possible, and we could not enjoy such a great CMS

**Comment by Moc** [comment] 2017-01-08 16:13
Thank you for the kind words!

**Comment by chory** [comment] 2017-01-08 16:14
I wish I knew as much about programming as you do, so I could help you, and not block myself for any nonsense
