### ISSUE TITLE
Long execution of php script

### ISSUE THREAD

**Issue by net1313** [e107inc/e107#3754] opened 2019-03-23 17:10 UTC
/e107_admin/admin.php' (request: "GET ?mode=addons&type=update&_=1553356977161") executing too slow (2.475930 sec)

**Comment by Moc** [comment] 2019-03-26 16:04
I cannot reproduce this so far. Are you getting this on a specific page?

**Comment by net1313** [comment] 2019-03-26 21:17
In fact I have LEMP (nginx php7.1-fpm) cron script which informs me about php errors on my site. There are no errors but only this one in admin.php

**Comment by Moc** [comment] 2021-12-20 19:22
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107

**Closed by Moc** 2021-12-20 19:22 UTC
Labels: status: testing required
