### ISSUE TITLE
why can't stay on admin area ?

### ISSUE THREAD

**Issue by Ghaners04** [e107inc/e107#1211] opened 2015-10-28 17:00 UTC
why when I login to the admin area, then I refresh the page I always go back to the login page ??

**Comment by CaMer0n** [comment] 2015-11-05 19:26
Cookies turned off?

**Comment by willem010** [comment] 2015-11-06 11:12
dunno if this is related but some of my users complain about an unauthorized notice when saving newsitems. 
this happens on at least 2 different servers and configs.

when they reload the page, and edit quickly.. it works.. 
but when they take some time, this unautorized notice appears again.
just like a session timedout.. but we're using cookies

i do remember having this issue before, where it was related to use of images 
(and misconfigured params in an url)

**Comment by Ghaners04** [comment] 2015-11-09 19:02
i have enable cookies, but still not work

**Comment by LaocheXe** [comment] 2015-11-09 19:42
could be your web host server is not configured correctly or even your browser.

**Comment by CaMer0n** [comment] 2015-11-19 04:44
@Moc Which browser are you using? I'm using the latest firefox and haven't had any issue. (linux or windows) . Any 3rd-party plugins common to all your sites?

**Comment by Moc** [comment] 2015-11-19 08:15
Chrome (its in my previous comment :)). I'll do some testing with other browsers to see if the problem can be replicated there.

No common 3rd party plugins. I'm pretty sure a clean install has the same odd behaviour. I'll try and confirm asap.

**Comment by Moc** [comment] 2015-11-19 09:36
@Ghaners04 Could you confirm which browser (and version) you are using?

**Comment by CaMer0n** [comment] 2015-11-22 18:08
@Moc If you disable the browser's cache, does it help?

**Comment by Moc** [comment] 2015-11-25 12:03
Doing my best to reproduce this for apparently this is one of the bugs that randomly appears. Currently I cannot reproduce this anymore but will do more testing asap.

**Comment by CaMer0n** [comment] 2015-11-30 22:58
If you are able to view this page at all, please share a screenshot of the "sessions" part. 

    /e107_admin/phpinfo.php#module_session

**Comment by Moc** [comment] 2015-12-07 11:56
OK issue is back. It usually happens when I am on the admin area, don't do anything for a while (work in a different tab) and then go back. Like the session times out (but way too quickly). Caching is not of influence here. 

Screenshots:

<img width="693" alt="e107 session 1" src="https://cloud.githubusercontent.com/assets/577978/11626266/c18f7e34-9ce1-11e5-8e17-22db22887344.png">
<img width="782" alt="e107 session 2" src="https://cloud.githubusercontent.com/assets/577978/11626265/c18f1ee4-9ce1-11e5-82ee-b0c0022a9daf.png">
<img width="720" alt="e107 session 3" src="https://cloud.githubusercontent.com/assets/577978/11626267/c1931cf6-9ce1-11e5-9d60-86e879ef71f3.png">

On the first screenshot, the session.cookie_domain value is `.domainname.com` (blacked out for privacy reasons)

**Comment by CaMer0n** [comment] 2015-12-12 08:25
Thanks @Moc . If you think the "unauthorized access" is displaying after submitted a form (which has been open for over 24 minutes) - please try adding this to e107_config.php to see if it helps.

    ini_set('session.gc_maxlifetime', 3600); 

(and check that it "takes" by viewing phpinfo again)

**Comment by Moc** [comment] 2015-12-13 10:59
@CaMer0n I'll try this asap but I don't think this is the issue. 

I just browser the admin area just fine, edited some settings. Then switched to another tab and worked for a few minutes (less than 24 minutes - 1440 seconds - for sure, maybe 5 minutes max). Then I went to Sync with Github (Tools > Database) and it suddenly threw me back to the index page and I was logged out.

**Comment by CaMer0n** [comment] 2015-12-13 11:20
Thanks @Moc. I understand. Is this happening on Linux or Windows for you?

**Comment by Moc** [comment] 2015-12-13 12:24
At the moment Linux but I think I experienced it on Windows as well.

**Comment by willem010** [comment] 2015-12-14 13:50
@moc  i just noticed my site keeps logging me off, just when i set Redirect all requests to site URL
when turned off, the problem isnt as bad.

**Comment by Moc** [comment] 2015-12-14 14:22
@willem010  'Redirect all requests to site URL' is turned off on my websites.

**Comment by willem010** [comment] 2015-12-14 14:56
.. ever since i checked that one, i cant stay logged on.
i turned it back off, but it keeps doing this now.
damn.

**Comment by willem010** [comment] 2015-12-14 15:03
omg omg.. i am an ass.. lol.. 
solved it, by entering the correct url in the site url box.
(it was set to / , which came from my development environment..)
now everything seems ok again. still logged on after 4 mins..
as always .. will keep u posted.

**Comment by Moc** [comment] 2016-03-16 14:53
At this point I cannot reproduce this issue anymore. I'm ready to close it until it starts occurring again.

**Comment by CaMer0n** [comment] 2016-03-17 18:12
Closing.

**Closed by CaMer0n** 2016-03-17 18:12 UTC
Labels: bug, testing required
