### ISSUE TITLE
adding user through admin using quick add

### ISSUE THREAD

**Issue by Worldwide7477** [e107inc/e107#1814] opened 2016-08-22 19:52 UTC
basically state that when creating a new user via the admin area user_extended table does not add a row for the user

**Comment by CaMer0n** [comment] 2016-08-30 18:07
@Worldwide7477 I am unable to reproduce this issue. When I create a user it creates an empty row in user_extended also. @Moc @Jimmi08 @tgtje Are you able to reproduce this problem?

**Comment by Jimmi08** [comment] 2016-08-30 18:52
May it solved with this:  https://github.com/e107inc/e107/issues/1639

By the way, it would be helped if you know what type of custom field was used 

I tried custom field and no problems.

**Comment by Worldwide7477** [comment] 2016-09-03 01:26
Sorry Cameron pc got hit by lighting, so rebuilding it right now....i will
report back very soon to let you know.

Worldwide7477

**Comment by tgtje** [comment] 2016-09-03 18:04
Can not reproduce; either activating pre existing fields or created.. both will show up (working)

**Comment by MikeyGMT** [comment] 2016-09-04 12:07
Cannot replicate either.

**Comment by Moc** [comment] 2016-10-17 15:58
Cannot reproduce either. 

@Worldwide7477 
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`

Alternatively you can download the ZIP file with all the latest files included by hitting the 'Download ZIP' button at the top of this page: https://github.com/e107inc/e107

**Closed** 2018-02-28 13:29 UTC
Labels: awaiting feedback
