### ISSUE TITLE
strange %0A popping up in news sef urls

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#818] opened 2014-11-20 09:54 UTC
![err1](https://cloud.githubusercontent.com/assets/6122908/5122662/7f2c5316-70a3-11e4-8fca-ea148fb209d6.png)
![err2](https://cloud.githubusercontent.com/assets/6122908/5122664/83e103f2-70a3-11e4-8ca0-6424077fa4f2.png)

all works ok, but it does look a bit weird.
i see this happening on about all my news items now.

**Comment by CaMer0n** [comment] 2015-01-29 20:54
Closing this as I'm unable to reproduce it. If someone else can, please re-open.

**Closed by CaMer0n** 2015-01-29 20:54 UTC
Labels: bug, testing required
