### ISSUE TITLE
& vs &amp; in e_url addon and validation

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4054] opened 2019-12-30 08:32 UTC
## Bug Description
e_url uses & in URL configuration and it causes validation error with HTML validator extension

## How to Reproduce
1. I noticed this with the forum plugin or use newforumposts menu

## Expected Behavior
No warning error, but W3C validation didn't find this, so maybe enough is just to explain why did you decide to use `&` in httpBuildQuery method instead of `&amp;`. Thanks

## Screenshots
![image](https://user-images.githubusercontent.com/5429548/71573638-3e572f80-2ae5-11ea-95fd-d44e687a7833.png)

**Comment by Jimmi08** [comment] 2019-12-30 12:57
@Moc it should be labeled as a question, it wasn't intention marked it as bug

**Comment by Deltik** [comment] 2019-12-30 13:39
An HTML validation error caused by e107 sounds like a bug to me.  I'll add an issue template for the `question` label.

**Comment by Jimmi08** [comment] 2020-01-07 10:24
@Deltik Great. Thank you.
It's easier this way. I still dislike to mark something like bug, or enhancement, it should be on core developers to mark this way. I just noticed this type of labeling in other repository (that word type):

![image](https://user-images.githubusercontent.com/5429548/71888060-ab02a780-313f-11ea-9c76-15d499d172a0.png)

**Comment by Deltik** [comment] 2020-01-07 20:19
@Jimmi08: Thanks for the feedback!  I've prepended all the issue type labels with "`type: `".

As for the auto-type assignment, the types are fundamentally different, so it makes sense to add them right off the bat.  If that's a mistake for whatever reason, a maintainer can change it later.

Issue statuses are now prepended with "`status: `", so that should make statuses clearer, too.

**Comment by Jimmi08** [comment] 2020-01-07 20:34
@Jimmi08 Perfect!  Thank you.

**Comment by Deltik** [comment] 2020-01-13 22:09
@Jimmi08: #4067 should fix this issue.  Can you try to apply the following patch (same changes as #4067) to see if the issue is fixed?: [fix-4054.patch](https://github.com/e107inc/e107/files/4056066/fix-4054.txt)

**Comment by Jimmi08** [comment] 2020-01-14 07:36
@Deltik Thanks.  I will do it ASAP.  

Could this be related?:  https://github.com/e107inc/e107/issues/3943
the point is that if there is `&amp; ` then that test fails because of `';'  `in the query.   
I have no idea why it just doesn't work in some cases.

**Comment by Jimmi08** [comment] 2020-01-14 08:38
What I did (I never used patch file before):
I am using this addon for testing:
http://users.skynet.be/mgueury/mozilla/

- sync with Github via admin
- on local repository applied your patch txt file, only e107_class.php was changed
- manual upload this file to the server
- cleared all caches (this was important)

Result:
- homepage (newsforum menu is there) - all similar errors fixed
- forum plugin - checked all pages (viewforum, viewtopic etc) - all similar errors fixed, 
- checked download, news, gallery.

**Comment by CaMer0n** [comment] 2020-01-14 21:42
This merged fix will break redirects when 'full' mode is in use. An exception needs to be added for this case.

**Closed** 2020-01-14 21:49 UTC
Labels: type: bug
