### ISSUE TITLE
Cannot create a new thread

### ISSUE THREAD

**Issue by pierre0042** [e107inc/e107#1367] opened 2016-02-17 20:45 UTC
When trying to create a new thread in the forum, I don't have all the fields displayed, and I see this error at the bottom of the page :

System Debug
Using Permlist cache: True
Query failed (e107forum::threadGet ): SELECT * FROM `e107_forum_thread` WHERE thread_id = 92

**Comment by pierre0042** [comment] 2016-02-17 21:09
So actually the query works but returns nothing, which is perfectly normal because 92 is the id of the forum where I want to make a new thread, it's not a thread id...

**Comment by pierre0042** [comment] 2016-03-01 20:06
Any news on this? This is really a blocking issue....

**Comment by LaocheXe** [comment] 2016-03-01 20:08
Give them some time, they got a lot on their plate.

**Comment by Moc** [comment] 2016-03-01 22:09
This is just a quick answer as I don't have that much time right now but IIRC a similar issue to yours was caused by incorrect templates used by the theme. 

Please try this:
- Change theme to bootstrap 3 to see if that changes things. This will rule out theme issues. 
- Temporarily remove any forum templates from your theme folder 

Is this is an upgraded website or a fresh install? 
Are you running any forum related plugins?

**Comment by pierre0042** [comment] 2016-03-01 23:22
Ok I will make those tests.

This is an updatet website, and I use a few forum plugins :
- Forum Thanks
- New Forum Posts
- Poll

**Comment by pierre0042** [comment] 2016-03-01 23:42
I tried with bootstrap3 theme but my site doesn't seem to work well with it so I can't really test :

![e107-newtopic](https://cloud.githubusercontent.com/assets/4124597/13445934/b0492820-e00f-11e5-9408-2fa2b21e9e98.png)

**Comment by pierre0042** [comment] 2016-03-01 23:45
The problem is :

![e107-msg](https://cloud.githubusercontent.com/assets/4124597/13445967/f49376ac-e00f-11e5-982d-4d6f3fb8a9d1.png)

but the fields are not present/visible on the new topic creation page...

**Comment by pierre0042** [comment] 2016-03-01 23:55
I renamed my templates folder in the theme directory and it doesn't change the issue

**Comment by CaMer0n** [comment] 2016-03-02 02:02
@pierre0042 I just tested with bootstrap3 and cannot reproduce the problem. Perhaps try uninstalling Forum Thanks, and see if that corrects it?

**Comment by pierre0042** [comment] 2016-03-03 23:04
Apparently removing the "Forum thanks" plugin fixes the problem

**Comment by pierre0042** [comment] 2016-03-03 23:08
But the SQL error is still visible...

and I have a PHP error at the bottom :

PHP Errors:

    Internal Error Message: Bad stored array data -

**Comment by CaMer0n** [comment] 2016-03-03 23:10
@pierre0042 I'm in the chatroom. Interested to take a closer look.

**Comment by CaMer0n** [comment] 2016-03-03 23:35
Closing this now. But please re-open if it occurs again.

**Closed by CaMer0n** 2016-03-03 23:35 UTC
Labels: awaiting feedback
