### ISSUE TITLE
PM_COMPOSE shortcode not working

### ISSUE THREAD

**Issue by pricey1981** [e107inc/e107#2217] opened 2016-12-30 15:48 UTC
On the PM Inbox page the 'Send New Message' button is not working (there is nothing in the href attribute of the link). I've tracked this through to the shortcode and the following line returns null...

`$urlCompose = e107::url('pm','index','', array('query'=>array('mode'=>'send')));`

The resulting output is `<th style='width:100px'><a class='btn btn-sm btn-primary btn-block-level' href=''><i class='fa fa-edit'></i> Send New Message</a></th>`

Any idea what the issue is?

**Comment by CaMer0n** [comment] 2016-12-30 19:06
Could you please share a list of the files located in your e107_plugins/pm folder ?

**Comment by pricey1981** [comment] 2016-12-30 21:58
It's the latest from github

images/
languages/
admin_config.php
e_cron.php
e_shortcode.php
e_url.php
index.html
plugin.xml
pm.css
pm.php
pm_class.php
pm_conf.php
pm_default.php
pm_func.php
pm_notes.txt
pm_setup.php
pm_shortcodes.php
pm_sql.php
pm_template.php
private_msg_menu.php

**Comment by CaMer0n** [comment] 2016-12-31 16:21
Thanks.. are you using SEF Urls or regular?

**Comment by pricey1981** [comment] 2017-01-21 17:45
@CaMer0n SEF urls

**Comment by CaMer0n** [comment] 2017-01-21 19:34
@pricey1981 Are you using the latest files from here? Also, is your .htaccess file up-to-date (ie. with code from e107.htaccess )

**Comment by pricey1981** [comment] 2017-01-21 20:18
I initially getting this issue with 2.1.2 so downloaded the github PM files. So I'm using 2.1.2, but with the github PM files.

**Comment by Moc** [comment] 2017-03-29 22:26
It may very well be that this issue is already resolved in the latest update. Please try updating from Github before we look into this issue more closely. 

There is an easy way to sync with Github:
- Enable developer mode in `Admin Area > Preferences > Advanced features`
- Go to `Admin Area > Tools > Database > Sync with Github`
- Press the `Overwrite files` button and wait until the process has finished. 

Alternatively you can download the ZIP file with all the latest files included by hitting the green 'Clone or download' button at the top of this page: https://github.com/e107inc/e107

**Comment by Moc** [comment] 2018-02-28 14:16
Closing this due to lack of feedback. Please let us know if the issue is still present, then I'll re-open

**Closed** 2018-02-28 14:16 UTC
Labels: awaiting feedback
