### ISSUE TITLE
LAN_PLUGIN_PAGE_NAME in search results..

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#3554] opened 2018-11-20 16:46 UTC
Search on site gives the text LAN_PLUGIN_PAGE_NAME for pages search results, not the translation or the original text in english.. Github of today.. 

Alex

**Comment by Moc** [comment] 2018-11-21 11:05
Cannot reproduce this so far.  What site language are you using?

**Comment by Alex-e107nl** [comment] 2018-11-21 14:48
In English and Dutch... http://fysid.nl/search?q=Lorem+ipsum&r=0&s=
Github today (21-11-2018) PHP Version 7.0.19

**Comment by Moc** [comment] 2018-11-21 15:48
I am pretty confident it's a language pack issue. I can reproduce it on my own website when I switch to Dutch, but when I switch back to English there is no issue. Looking into it.

**Comment by Moc** [comment] 2018-11-21 15:52
Got it. It was added last month, not yet translated in the Dutch LAN files because it will be part of the new release 2.2.0.

**Closed by Moc** 2018-11-21 15:52 UTC

**Comment by tgtje** [comment] 2018-11-22 18:53
Read it, will update the newer version ( for 2.20) asap. Bit short in time to keep up... 

Have to test the new pack then  also in case of not using the closing php tags in files, due to previous issues that blank spaces getting added sometimes in Github (although they not exist on pc) ???

**Comment by Alex-e107nl** [comment] 2018-11-29 21:43
Solved, THX Tgtje you are the best!!
