### ISSUE TITLE
+ sign is filtered out too severely

### ISSUE THREAD

**Issue by KeitaroHimura** [e107inc/e107#505] opened 2014-01-28 15:46 UTC
Whenever I post any news item or page with a + in it, the + gets filtered out. And when I post a news item, I get this error: Error: : 5 Connect error: php_network_getaddresses: getaddrinfo failed: No address associated with hostname (0)

**Comment by CaMer0n** [comment] 2015-05-22 18:13
Closing this. Unable to reproduce. I believe it was most likely corrected with the parser upgrades that were made in the past few months.

**Closed by CaMer0n** 2015-05-22 18:13 UTC
Labels: bug
