### ISSUE TITLE
newforumposts_menu wrong post_url (shortcode)

### ISSUE THREAD

**Issue by Killer0561** [e107inc/e107#2800] opened 2017-09-28 17:01 UTC
In newforumposts_menu forum plugin is the topic url wrong (post_url) shortcode:

https://xxx.de/plugins/forum/forum_viewtopic.php?id=5272&f=post&id=0 (wrong)
https://xxx.de/plugins/forum/forum_viewtopic.php?id=5272 (right)

https://github.com/e107inc/e107/blob/master/e107_plugins/forum/shortcodes/batch/view_shortcodes.php

**Comment by CaMer0n** [comment] 2017-09-29 19:21
Is this issue present on the default template or does it only occur with your own template?

**Comment by Killer0561** [comment] 2017-09-29 23:11
https://github.com/e107inc/e107/blob/master/e107_plugins/forum/templates/newforumposts_menu_template.php

default template => {POST_URL} must be changed to {TOPIC_URL}

**Comment by rica-carv** [comment] 2017-09-30 15:52
In theory, the only one to be changed would be the one in [line 50](https://github.com/e107inc/e107/blob/7485bc49ee1b854e0b3fce8e3503e82281a2d609/e107_plugins/forum/templates/newforumposts_menu_template.php#L50), since all the others refer to the last post, and not the topic opening post itself....

**Comment by Moc** [comment] 2019-02-07 12:28
@Killer0561 I cannot reproduce this. The `id` is properly filled with the right post ID. So it scrolls to the specific reply in the forum post. Can you show me the incorrect URL on your website please? I'm on Gitter.

**Comment by Killer0561** [comment] 2019-02-07 18:58
It is allready fixed. The problem was fixed months ago.

**Comment by Moc** [comment] 2019-02-07 19:29
Thanks. Closing.

**Closed** 2019-02-07 19:29 UTC
Labels: awaiting feedback
