### ISSUE TITLE
Fileinspector

### ISSUE THREAD

**Issue by fizi** [e107inc/e107#4511] opened 2021-05-31 17:04 UTC
## Bug Description
I got blank page on admin fileinspector page after upgrade from GitHub on admin area.

**Comment by Deltik** [comment] 2021-05-31 17:26
Can you paste the stack trace from the PHP error log?  You can usually find it in a file called `error_log` or in the web server (Apache or NGINX) error log.

**Comment by fizi** [comment] 2021-06-04 20:30
![fileinspector_bug](https://user-images.githubusercontent.com/86780/120859443-8143ef00-c584-11eb-8f5b-60ef742a75de.jpg)

**Comment by Deltik** [comment] 2021-06-04 22:00
@fizi, I cannot reproduce the issue based on the information you provided.  There is probably a fatal error, which should be logged in a log file somewhere.  Can you provide the stack trace?

The error should look something like this (but not exactly):

```
[Fri Jun 04 21:59:16.726521 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP Parse error:  syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE) in /var/www/html/e107/e107_handlers/e_file_inspector.php on line 26
[Fri Jun 04 21:59:16.726557 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP Stack trace:
[Fri Jun 04 21:59:16.726562 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   1. {main}() /var/www/html/e107/e107_admin/fileinspector.php:0
[Fri Jun 04 21:59:16.726567 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   2. require_once() /var/www/html/e107/e107_admin/fileinspector.php:251
[Fri Jun 04 21:59:16.726576 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   3. require_once() /var/www/html/e107/e107_admin/auth.php:96
[Fri Jun 04 21:59:16.726580 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   4. e107::renderLayout() /var/www/html/e107/e107_admin/header.php:591
[Fri Jun 04 21:59:16.726584 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   5. e_parse->parseTemplate() /var/www/html/e107/e107_handlers/e107_class.php:373
[Fri Jun 04 21:59:16.726591 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   6. e_parse_shortcode->parseCodes() /var/www/html/e107/e107_handlers/e_parse_class.php:823
[Fri Jun 04 21:59:16.726595 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   7. preg_replace_callback() /var/www/html/e107/e107_handlers/shortcode_handler.php:996
[Fri Jun 04 21:59:16.726600 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   8. e_parse_shortcode->doCode() /var/www/html/e107/e107_handlers/shortcode_handler.php:996
[Fri Jun 04 21:59:16.726607 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP   9. admin_shortcodes->sc_admin_help() /var/www/html/e107/e107_handlers/shortcode_handler.php:1130
[Fri Jun 04 21:59:16.726611 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP  10. e_help() /var/www/html/e107/e107_core/shortcodes/batch/admin_shortcodes.php:207
[Fri Jun 04 21:59:16.726616 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP  11. e107::getSingleton() /var/www/html/e107/e107_admin/fileinspector.php:1334
[Fri Jun 04 21:59:16.726623 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP  12. file_inspector->__construct() /var/www/html/e107/e107_handlers/e107_class.php:1138
[Fri Jun 04 21:59:16.726627 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP  13. e107::getFileInspector() /var/www/html/e107/e107_admin/fileinspector.php:368
[Fri Jun 04 21:59:16.726631 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP  14. e107::getObject() /var/www/html/e107/e107_handlers/e107_class.php:1819
[Fri Jun 04 21:59:16.726640 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP  15. e107_require_once() /var/www/html/e107/e107_handlers/e107_class.php:1179
[Fri Jun 04 21:59:16.726644 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP  16. require_once() /var/www/html/e107/e107_handlers/core_functions.php:137
[Fri Jun 04 21:59:16.726648 2021] [:error] [pid 2363] [client 10.64.229.1:49106] PHP  17. require_once() /var/www/html/e107/e107_handlers/e_file_inspector_json_phar.php:10
```

**Comment by Jimmi08** [comment] 2021-06-05 06:03
@fizi Little advice. Switch admin to English at first :)

**Comment by fizi** [comment] 2021-06-07 16:56
I switched to english, the problem same.

**Comment by Deltik** [comment] 2021-06-07 20:28
@fizi: Please email me at [`echo strrev(convert_uudecode("49W)O+FMI=&QE9$!R971S86UB97<`\n`"))`](https://ideone.com/3ukgjM).

**Comment by Moc** [comment] 2021-12-22 14:08
@fizi @Deltik Any update on this?

**Comment by Deltik** [comment] 2021-12-22 14:23
Closing as invalid due to insufficient details

**Closed by Deltik** 2021-12-22 14:23 UTC
Labels: type: bug, status: invalid
