### ISSUE TITLE
Issue: Initial User Class

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#1745] opened 2016-06-29 03:40 UTC
So in Admin Area - > User Classes - > Initial User Class   I have selected one class, and have it set to Initial Signup - However I notice it only works on users who used Social Login instead of users who create accounts.

**Comment by LaocheXe** [comment] 2016-07-17 18:24
![capture](https://cloud.githubusercontent.com/assets/5818022/16902315/5f8847f8-4c21-11e6-9cda-04b7efe7393b.PNG)

I have a user group called Civilian which when new accounts are created they are in that group - this is so I can have a link and some panels on my site to encourage the Civilians to enlist to the gaming community. The users who login with Steam are given that user group, but e107 new accounts aren't.

**Comment by LaocheXe** [comment] 2016-08-02 16:08
Over the past weeks, this still continues - social login accounts are added to the user class I have selected while e107 register new users do not get added.

**Comment by LaocheXe** [comment] 2016-10-25 15:12
@Moc, what php file has the code for this? I want to do some checks to why this happens

**Comment by Moc** [comment] 2016-10-25 15:18
I've done some work on this waaaaaaay back in issue https://github.com/e107inc/e107/issues/580
It should work just fine since then, I think on one of my websites this working fine with people who sign up using the regular sign up process (I do not have social logins enabled there yet). 

Anyhow, the code is located in the `e107_handlers/user_handler.php` class, under the `userClassUpdate()` method.

**Comment by LaocheXe** [comment] 2016-10-25 15:23
Odd cause on my tf13arma site i keep the code synced with github, and for some odd reason only social login works, regular doesn't.

**Comment by Moc** [comment] 2016-10-25 15:25
Maybe a bug crept in over these past two years, I don't know how up-to-date my current website is, plus I am not actively monitoring it haha. I'll check on a local installation to see if i can reproduce it (this week when I get a moment hopefully).

**Comment by martyshep** [comment] 2017-10-26 14:04
Hi all, it looks like this is still outstanding. My user signup through the regular signup method, no social login, and user does not get put in user group when my user admin validates the account and clicks activate.

**Comment by CaMer0n** [comment] 2017-10-26 19:37
@martyshep What is your setting for: "Point at which classes set:" ? Mine is set to "Initial Signup"

**Comment by martyshep** [comment] 2017-10-26 23:36
I've tried both settings. I reviewed all my userclass settings to return then as much as possible to default and I still do not get the user added to a userclass on signup or activation.

**Comment by martyshep** [comment] 2017-10-26 23:43
This is my class structure. I do have a question, if a userclass parent is everyone (public) does that userclass have access to the subclass?  I run the website as a members only website with a public front page.
![image](https://user-images.githubusercontent.com/15772899/32081897-e7c41dc4-baaf-11e7-8027-4d84988dfb29.png)

**Comment by martyshep** [comment] 2017-10-27 12:18
I also checked in the database, the e107_core SitePrefs option for the initial underclass I want set and it is set there ok.

**Comment by CaMer0n** [comment] 2017-10-28 01:19
Are you using email activation or admin approval for registrations?

Here's the main place where the data insert happens. `signup.php, line 449`:  

```
       if ($init_class = $userMethods->userClassUpdate($row, 'userfull'))
       {
            // commented code. 
            $dbData['data']['user_class'] = $init_class;
       }
```

If you want to do some tests, you could try inserting this code where it says `// commented code`

```
$initDebug = print_r($row,true);
$initDebug .= "Init Class: ".$init_class;
e107::getLog()->addDebug($initDebug)->toFile('initClasses',"Initial Userclass Log",true);
```

Try some signup activations, and then check `e107_system/xxxx/logs` for `initClasses.log` to see what it says. 

If it's empty, try moving the debug code BEFORE the `if`.

**Comment by martyshep** [comment] 2017-10-29 13:07
Can not get e107 to generate initClasses.log using:
// Set initial classes, and any which the user can opt to join
					e107::getLog()->addDebug($initDebug)->toFile('initClasses',"Initial Userclass Log",true);
					if ($init_class = $userMethods->userClassUpdate($row, 'userfull'))
					{
						$initDebug = print_r($row,true);
                        $initDebug .= "Init Class: ".$init_class;
						$dbData['data']['user_class'] = $init_class;
					}

In fact the initClasses.log file is not there at all so I tried creating it but nothing is being appended to it, it is empty. Have tried the debug before and after the if.

Do I need to use Firefox e107 debugger to make this happen?

**Comment by martyshep** [comment] 2017-10-29 13:53
I've tested further and I can now get an initial user class set for a new signup but only if I select in the preferences for the user to activate via email.  If I select this option, when the user verifies their email then the userclass is added. If I set to Admin approval, if the admin approves by clicking Activate, no email is sent to user (we send a personalised one) and no initial user class is added. If I have preference set to Admin Approval but then click Resend Email to a new signup, they then get the email and when they verify, the user class is added.

I haven't managed to get any logging working mind.

**Comment by CaMer0n** [comment] 2017-10-29 18:25
@martyshep Just committed a change. Please give that a try and let me know how it goes. Thanks.

**Comment by martyshep** [comment] 2017-10-30 00:42
AWESOME! Worked like a charm, as soon as Activate clicked, userclass added. Thank you Sir 👍

**Comment by CaMer0n** [comment] 2017-10-30 16:27
You're welcome! Thank you for the raising the issue! 👍

**Closed by CaMer0n** 2017-10-30 16:27 UTC
Labels: bug, testing required
