### ISSUE TITLE
Update Forum - Step 2

### ISSUE THREAD

**Issue by brhahlen** [e107inc/e107#1788] opened 2016-07-28 11:45 UTC
When trying to update the Forum, after upgrading to v2, at step 2 (Table creation), it will fail with the following error:

```
Error
Creating table forum_new
Creating table forum_thread
Creating table forum_post
Creating table forum_track
Creation of table(s) failed. You can not continue until these are created successfully!
```

However, the tables are created successfully.
When retrying the step, it will give the following error:

```
Error
Creating table forum_new
Creation of table(s) failed. You can not continue until these are created successfully!
```

Cannot find anything useful (so far) with the debug-info.

**Comment by rica-carv** [comment] 2016-07-28 12:38
I've had this same issue when upgrading from v1.4 to v2.x, so i had to manually make all the old forum changes to the new v2.x forum structure...
Anyway, i'm on the process of making a clean v2.x install and migrate all the data from old v1.4 to it, since there's a few more bugs on the update, which are not worth debug....

**Comment by brhahlen** [comment] 2016-07-28 12:48
I just tried to "Reset to 3", which kind of worked, but then step 4 gave me a blank page.
I seriously need some help here from someone, can even create a login for one of the e107 developers, if needed.

**Comment by tgtje** [comment] 2016-07-28 15:02
Please take a moment to read this thread, maybe it helps finding issue ( know its old but might give clues). https://github.com/e107inc/e107/issues/695

**Comment by brhahlen** [comment] 2016-07-29 06:20
I read through it, and it is kind of similar, but not really (that's the most clear I can make it).

That issue refers to a lightbox plugin that prevented the upgrade from go further.
I only have e107-provided plugins installed, I could uninstall them (without clearing the database tables) and see if that helps.
I'll report back on that.

**Comment by brhahlen** [comment] 2016-07-29 06:40
Uninstalling all plugins (except forum) gave me some core-database updates, but the forum upgrade still fails.

I do get this from debugging (among other things):
```
Notice Undefined index: reset, Line 43 of /home/web/www/wow/e107_plugins/forum/forum_update.php	

Array
(
    [0] => 
    [1] => 
)
```
Maybe it helps

**Comment by brhahlen** [comment] 2016-07-29 08:47
Uninstalling and reinstalling forum also didn't help.
I'm at a loss where it goes wrong...

**Comment by tgtje** [comment] 2016-07-29 11:29
Different approach ( #1109 + #1012 ) 
looks like session is not destroyed, needs developer to look at.
(just for testing > go update till forum update> do not update, but **log out** AFTER you have ckeared system cache.
Close your browser and delete browser cache + cookies of site. Now go back and log in. Start forum update (by using pluginmanager forum wrench icon ).

**Comment by brhahlen** [comment] 2016-07-29 12:30
I can provide a login (to both the site and the DB) if needed, if it helps.

Now, I tried clearing system cache, removing forum plugin, log out, open private window, log in, clear system cache, reinstall forum plugin, still no go.
There are no messages that I should delete files, so that doesn't help either...

**Comment by rica-carv** [comment] 2016-07-29 16:20
Try to force the creation of the missing tables via phpmyadmin or similar.
Just copy the code from the forum_update.php file, and give it a try.
I've solved the issue i had with it this way....

**Comment by tgtje** [comment] 2016-07-29 16:33
I (or anybody else who will) can take a look of course (no guarantee on solution however).
login needed ( m.admin + db maybe ftp..)
Be sure to have backups for yourself. Post> no message to delete files > than there are no...
If you like me to > tgtje (at) tgtje dot nl (github has no pm system).

**Comment by rica-carv** [comment] 2016-07-29 18:10
@tgtje 
`(github has no pm system).`
But you can create a private chat with github login on gitter.im....

**Comment by tgtje** [comment] 2016-07-29 19:47
Thanks @rica-carv  i know, ( but it is static information), although chat remains not usefull because testing has to be done first ( length in time) where direct mail is always straight forward independant if user is present...

**Comment by brhahlen** [comment] 2016-08-01 07:53
Thanks very much @tgtje 
I have send you the required information, it took a bit longer due to a busy weekend, and haven't touched my computer at all during that time.

Please let me know if you need anything else.

**Comment by tgtje** [comment] 2016-08-01 11:43
Received and looked into it, run some tests if your happy? (mail send).




---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by brhahlen** [comment] 2016-08-01 12:01
Thanks again for the help.
Just one issue left, as far as a I can see.

**Comment by brhahlen** [comment] 2016-08-02 08:05
Got a lot of help from @tgtje, but unfortunately, I think the DB was too screwed up to get it fixed properly.
Luckily, I had some backups lying around, so I went and ran a Docker image with a LAMP stack, with PHP5. Did the upgrade from there and then moved everything back to my own server.
It all works now!

Thanks again for all the help.
Closing.

**Comment by CaMer0n** [comment] 2016-08-02 16:09
@brhahlen Do I understand well that you had the empty tables in the database, but the upgrade wouldn't let you continue since it was trying to re-create them?

**Comment by brhahlen** [comment] 2016-08-02 17:48
@CaMer0n Yes, I had that, but I am not the sure if that was the full extent of the issue. 
I don't actually know what the real issue was, but upgrading on a PHP5 instance worked flawlessly, so I am assuming at this moment that it had to trying to do the update on a PHP7 box.
@tgtje looked at it, and he tried some stuff, but I think that the database was too far gone at that moment to be of any real help.

I can set a backup in a new instance and see if I can recreate it, so you can look around, if you want.

**Comment by tgtje** [comment] 2016-08-02 18:35
Just informative adding: in the process tables were created (4) but on error > step back > 3 of the tables exist.. ('behaviour' encountered before) > delete tables and start again... However even why that worked, table forum_thread was not 'filled' ( seeing no actual data to be restored/transfered) due to at point in time ( earlier updating???) this is/was not available. Reworked old v 0.7 23 (used older supplied dbase) updated to 1.04 > update to v2 > (php 5 x based). I stopped when forum thread was present and exported/imported table into php 7. So functional state (later mentioned.. not all working inside). So yes database issues are mostly the cause. 
( maybe make people angry : but ubuntu > lately often on issue posts). Not sure at last state if the newly running website has still utf8 + latin (swedish) tables.. as old dbase file had both ???

**Comment by brhahlen** [comment] 2016-08-03 07:37
After the upgrade, only the user_extended table has latin_swedish collation, all the other have been properly set to UTF8.

I have created a backup site, in the 0.7.23 state, with upgrade and backup files present, if you want to play around @CaMer0n 
Let me know where I can send you all login-details and such.

**Comment by CaMer0n** [comment] 2016-08-12 23:04
@brhahlen Please update from Github and upgrade your 'wow' installation. User-timezone and forum upgrade should perform without any issues now. (hopefully)

**Comment by brhahlen** [comment] 2016-08-15 07:57
Updated the 'wow' installation folder, but getting a different error now, it is in the chat.

**Comment by MikeyGMT** [comment] 2016-11-26 14:35
FYI - I got similar, php 5.3, it created the other tables inc forum_new, but when retrying after the message failed. with cannot continue. 
I got the site updated to php 5.6. 
Next went to phpmyadmin, found forum_new was there renamed/moved (empty) forum_new to xforum_new and retried step 2 and it created the tables ok. 
Hence looks like forum upgrade is not picking up that forum_new was previously created in another attempt. So trying to create it again failed.

**Comment by CaMer0n** [comment] 2016-11-26 18:39
Thanks @MikeyGMT this was helpful.

**Comment by Moc** [comment] 2016-12-16 17:22
@MikeyGMT Do you have the possibility to test this scenario again using the latest files from Github, just so we can confirm if Cameron's adjustments fix the issue?

**Comment by Moc** [comment] 2017-01-17 23:02
@MikeyGMT Freindly reminder for my previous comment. If you don't have the opportunity to re-test, I'll close the issue as I assume it's fixed. If not we can always re-open.

**Comment by MikeyGMT** [comment] 2017-01-19 11:53
@Moc I'll have a look on the weekend

**Comment by Moc** [comment] 2017-01-19 12:35
Thank you!

**Comment by MikeyGMT** [comment] 2017-01-30 16:29
Yes forum upgrade seems to have completed ok. @brhahlen Ben has that worked for you, cheers, Mike

**Comment by brhahlen** [comment] 2017-01-31 20:41
Mine was fixed a while ago. I worked on it with Cameron.

**Comment by Moc** [comment] 2017-01-31 21:35
Perfect, closing it then :)

**Closed** 2017-01-31 21:35 UTC
Labels: bug
