### ISSUE TITLE
Forum move & new reply star

### ISSUE THREAD

**Issue by Aaronsss** [e107inc/e107#2016] opened 2016-11-08 20:55 UTC
I am having a few forum related issues since upgrading to bootstrap and am a little unsure of what’s going on. 

Basically, on the forum the following appears to not work for my site:
1. When a user posts a reply no star appears on the forum or the thread (It does work when a new topic is created)
2. Admins are unable to move threads (the other functions appear to work fine) - All that happens is the page reloads and presents no dialog or way of selecting the thread destination.

Note I do get some integrety fails on it but even after reloading the files to the server I still get that and there are many elsewhere on the site.

**Comment by CaMer0n** [comment] 2016-11-12 01:28
Are you using the default Bootstrap theme or a custom one?

**Comment by Aaronsss** [comment] 2016-11-12 02:14
I was using a modified version of the default one. I did however try it with the default one and the same thing happened.

**Comment by CaMer0n** [comment] 2016-11-15 00:33
Thanks. So, regarding: 
1) Did you test with a different user to the one who posted the reply to a topic?

2) I was unable to reproduce this problem. Are you using the dropdown menu with the "Move" option?

![screenshot-move](https://cloud.githubusercontent.com/assets/2825679/20288385/e4685804-aa87-11e6-9354-a6905d1b1e7c.png)

**Comment by Aaronsss** [comment] 2016-11-15 22:00
@CaMer0n in response.

1) So during testing of this I did the following 1 user account was monitoring the forum the other was posting.
When creating a new topic the forum itself displays the star but the topic does not
When using the quick reply box or post reply it does not create a star anywhere.

2) yes I am using the drop down menu move option, it just reloads the page every time

**Comment by rica-carv** [comment] 2016-11-17 20:56
I also tried moving topics (question 2), and it works, even with my own bootstrap theme.....
Can it be a conflictuous plugin?
Do you have a clean v2.x installation, or an v1.x upgraded one?

**Comment by Aaronsss** [comment] 2016-11-17 22:48
I have an upgraded one. I have been using e107 for 8 years or so. I have verified all the files in the forum folder are correct. The rest of the site has been verified against a fresh install of e107 and I believe I have removed all the old files that I wasn't using

**Comment by CaMer0n** [comment] 2016-11-18 00:28
@Aaronsss Please update. I believe I have fixed Issue 1. 
For issue 2, I'm still unable to reproduce the issue. Are you renaming the thread, or simply moving it do a different forum?

**Comment by Aaronsss** [comment] 2016-11-18 00:40
Excellent that’s sorted issue 1, with one exception. When creating a new topic, a star appears on the forum itself but not on the topic. I am not sure if this is intentional or not. It is working very well for any replies.

As for the move feature, basically I click the drop down, click move, the page reloads exactly as i left it, there is no option to move rename or anything it is as if I never clicked move in the first place.

**Comment by CaMer0n** [comment] 2016-11-18 00:49
@Aaronsss Okay thanks. Are you using SEF Urls or regular urls?

**Comment by rica-carv** [comment] 2016-11-18 19:21
@CaMer0n Just a small question, that menu only is visible to admin & forum moderators, right? If so, instead of calling it "options" why not calling it "moderator options"?

**Comment by Aaronsss** [comment] 2016-11-18 22:41
I am using regular URL's

**Comment by CaMer0n** [comment] 2016-11-18 23:46
Thank you @Aaronsss. That helps. Please update your forum folder with the latest files from github and see if that helps.

**Comment by Aaronsss** [comment] 2016-11-19 09:08
Works a treat, thanks :) Could this be the problem for some of the other issues I have been having?

Was the intention to alter the new post start on new threads too? As I mentioned above when creating a new thread the forum gets a star but the thread itself doesn't

**Comment by CaMer0n** [comment] 2016-11-19 21:33
@Aaronsss We tested more with the SEF URLs, so it is possible that some legacy URLs have issues. 
I believe the 'star' should appear as you mentioned, so I'll keep this issue open until it is also corrected.

**Comment by Aaronsss** [comment] 2016-11-23 22:05
As an additional observation that I have just noticed. When a user posts it causes an activity star that they can see because of their own post.

**Comment by Moc** [comment] 2017-01-02 14:45
@cainey is likely to have this issue as well

**Comment by cainey** [comment] 2017-01-03 00:14
@Moc thank you, so i would just replace the file? sorry did have that many issues with the site i worry about doing anything :)

**Comment by Moc** [comment] 2017-01-03 11:02
@cainey Doing so may help a bit, but is not likely to completely solve your issue. This issue is still open on Github (here), but it should be fixed for the next release. Best is to keep an eye on this issue here, to follow any updates.

**Comment by cainey** [comment] 2017-01-03 11:48
@Moc thank you, its no major issue i will more than likely leave it until once its fixed.  again thank you.

**Comment by rica-carv** [comment] 2017-01-03 18:04
I'm kinda of lost here.
So the remaining issue is the new post icon not appearing on the thread itself, right?

**Comment by cainey** [comment] 2017-01-12 00:15
Its more random for people. say if a member posts new post/reply the star might not show, i might stumble across the new post then a day or so later the star shows a new post but i have already read it.

**Comment by CaMer0n** [comment] 2017-01-12 01:52
Is it related with this? #809 @cainey Would you mind updating from github and re-testing?

**Comment by Moc** [comment] 2018-02-28 13:49
I am assuming all issues are fixed in the latest version. If not, please let us know and I'll re-open.

**Closed by Moc** 2018-02-28 13:49 UTC
Labels: awaiting feedback, bug
