### ISSUE TITLE
Chatbox

### ISSUE THREAD

**Issue by Ashguardian** [e107inc/e107#999] opened 2015-05-08 22:26 UTC
Hi CaMer0n!

Chatbox count, and moderation (#972) are working fine now. Thanks for the fix!

But I have found some new issues (latest installer):
- I have installed the chatbox plugin, but I can't post a message. In the admin area, got a message:
  ![cb_dbup1](https://cloud.githubusercontent.com/assets/11802599/7546707/3acea61a-f5e1-11e4-8739-d88da59087c2.png)
  ![cb_dbup2](https://cloud.githubusercontent.com/assets/11802599/7546708/3feea906-f5e1-11e4-95ca-0cdcce01c241.png)
  After the database update, the chatbox is working fine, but...
- If I select in the chatbox admin this option:
  Chatbox Display options -> Use javascript code to update posts dynamically (AJAX)

and post a message, the whole chatbox is "loading" with a "toggle" effect.
- In the chat_template file, there is a missing bracket in line 13.

**Comment by Moc** [comment] 2015-07-05 17:25
@Ashguardian Is the database update message issue still present?

**Comment by Ashguardian** [comment] 2015-07-05 21:11
@Moc No, there is no db update anymore. Only the "whole chatbox loading" problem left.

**Comment by Moc** [comment] 2018-06-25 12:56
@Ashguardian I cannot reproduce it anymore. Closing this issue for now. If it's still a problem, let us know. Also mention which browser you are using please.

**Closed** 2018-06-25 12:56 UTC
Labels: bug
