### ISSUE TITLE
Avatar links not saving in usersettings.php

### ISSUE THREAD

**Issue by sparuj** [e107inc/e107#3808] opened 2019-05-19 12:16 UTC
Hello everyone.

I've been trying to figure out this for so long and I'm going crazy right now.

(On my webhosting provider):
The problem is when I try to upload a avatar in usersettings.php through Choose File Option and click Save settings I get a message Successfully uploaded '131676.jpg' and Settings updated and saved into database. However nothing is saved in the database and in usersettings.php. When I manually go to the database and add a link -upload-ap_1_131676.png the avatar is being shown. In addition even though the link isn't being saved in usersettings.php the avatar is still being uploaded to the /e107_files/public/avatars which is strange.

The strange thing is that when I run the website system on my PC through xampp I can upload avatars without a problem.

Please excuse me if I don't make any sense in this post. I've been up all night trying to figure out what the problem might be. (probably a cpanel setting or something, no idea...)

Cheers!

**Comment by Moc** [comment] 2019-05-19 12:41
What's your PHP and MySQL version?

**Comment by sparuj** [comment] 2019-05-19 12:47
This is the live server information

Apache Version | 2.4.39
PHP Version | 7.1.29
MySQL Version | 10.3.15-MariaDB

I tried all possibilities running php 5.6, running v1.04, v2 and everything works on my PC server.
(did not try to run different versions of mysql on my pc server.)

**Comment by tgtje** [comment] 2019-05-19 16:10
Just adding (no intention to interfere) the description is (when read) applicable to v 1.0.4 due to the path : e107_files. This folder exist only on v0.7.x and v2 _upgraded_ versions. In v2 the avatar path is to e107_media/hash/avatars.. When experimenting, keep this in mind.

**Comment by Moc** [comment] 2019-05-21 10:10
Not being able to reproduce this so far. 

Can you enable debug mode for SQL?
Change your URL to `/usersettings.php?[debug=sql+]` then try saving your usersettings again (try uploading a new avatar). 

This way we may see any possible SQL errors.

**Comment by sparuj** [comment] 2019-05-21 11:36
@tgtje Thank you for pointing this out. When I wrote the post I had v1.04 installed and just copy/pasted the path => because lazy and tired and forgot about the other path for v2

@Moc This is what I get from the debug message:

```
2 Query Errors!
Index	Query / Error
45 	UPDATE e107_user SET user_name = 'sparuj', user_email='sparuj@gmail.com', user_signature='', user_image='-upload-ap_1_129994.png', user_timezone='+2', user_hideemail='0', user_login='' , user_customtitle = 'sparuj0' , user_xup='' WHERE user_id='1'
Unknown column 'user_login' in 'field list'
47 	INSERT INTO `e107_user_extended` (user_extended_id, user_hidden_fields) values ('1', '')
Duplicate entry '1' for key 'PRIMARY'

```

**Comment by Moc** [comment] 2019-05-21 12:00
Can you verify with a tool such as phpmyadmin that the column user_login actually exists in your database table e107_user 

You can also run the database verify tools to see if that helps: Admin Area > Tools > Database

**Comment by sparuj** [comment] 2019-05-21 12:25
I can only say uh wow. I didn't even realize that I have deleted user_login from the database and it seems that it fixed the issue after adding it back. O_O
Guess I should try sleeping more often, heh.
Thank you so much for the help.

**Comment by sparuj** [comment] 2019-05-21 12:34
P.S. Is there a way to turn off the debug mode? I assume that regular user can also use this on the website and I don't want that.

**Comment by Moc** [comment] 2019-05-21 12:50
No worries. I recommend using the Tools > Database page to verify your database structure is intact. Also, e107 should provide alerts for this in the admin area as well, if it detects incorrect database structures. 

Debug mode can be turned of by changing the URL to `/index.php?[debug=none-]`
There are several  permission checks that control the visibility of specific debug information. Non-logged in users (guests) can only see very limited information. Logged in users with Admin permissions can see more. 

Another check you may to do is make sure 'Developer mode' is turned off in Preferences > Advanced features. 

Closing the issue as it's solved :)

**Closed** 2019-05-21 12:51 UTC
Labels: invalid
