### ISSUE TITLE
Without authorization comments.

### ISSUE THREAD

**Issue by Evgura** [e107inc/e107#3829] opened 2019-06-06 11:28 UTC
![eddv](https://user-images.githubusercontent.com/25720089/59029504-e66e8800-8877-11e9-9441-ba2315f0678c.jpg)

If you leave comments without logging in we get this...

![erty](https://user-images.githubusercontent.com/25720089/59029479-d5257b80-8877-11e9-9c43-3285b95c1a02.jpg)

If you then log in it turns out here that...

![edss](https://user-images.githubusercontent.com/25720089/59029583-13229f80-8878-11e9-98da-5c8178de7c14.jpg)

![edcaa](https://user-images.githubusercontent.com/25720089/59029551-fdad7580-8877-11e9-8558-2872878606d2.jpg)

Comments in the admin set up, recalculation did.

**Comment by Moc** [comment] 2019-06-06 13:21
I am not sure I understand your issue. 

From the title I understand that there is unauthorized comments. I assume that this means that Guests are able to post comments, even though you do not want this. 

In "Admin Area > Comments Manager > Preferences", the setting `Allow users to post comments` is turned off?

**Comment by Evgura** [comment] 2019-06-06 13:45
Yes, comments are allowed without registration.
What with the English language without it turns out the same.
Previously, you could write just like that.

**Comment by Moc** [comment] 2019-06-06 13:56
I cannot confirm this. I get this when I am not logged in:

![image](https://user-images.githubusercontent.com/577978/59038637-a1485700-8873-11e9-86ab-32531e9b2394.png)

Are you using the latest files?

**Comment by Evgura** [comment] 2019-06-06 13:58
e107
Версия 2.2.2 (git)

**Comment by Jimmi08** [comment] 2019-06-06 18:34
@Moc 
I think he is trying to say:
- quests can comment (it's ON)
- if you post comment as quest, you get time of posting  49 years ago
- if you post comment as quest, quest content of comment is not visible
- as soon as you log in, all icons on comments are changed to user icon 
- as soon as you log in, time and comment content is visible.

I could be wrong...  
Maybe this is related to that php 7.3 change
@Evgura on live site use max official 2.2.1 release from e107.org, not GitHub version

**Comment by Evgura** [comment] 2019-06-06 18:39
@Jimmi08 Версия PHP 7.2.18 
Maybe it is connected with the engine version 2.2.2

**Comment by Jimmi08** [comment] 2019-06-06 18:43
@Evgura 
Very probably,  I meant - after 2.2.1 release there was a big change in the core.  If this is related, very good that you find it.  But until full testing, you shouldn't use 2.2.2 on live site.

https://github.com/e107inc/e107/issues/2146

Did I get correct what you had on mind?

**Comment by Evgura** [comment] 2019-06-06 18:48
@Jimmi08 Maybe it has something to do with it. I'll try to roll back to 2.2.1

**Comment by Evgura** [comment] 2019-06-09 07:56
@Jimmi08 On version of engine 2.2.1, too, not earned.
2.2.0 not found where download.
Failed to start all without errors on version 2.1.9

**Comment by Moc** [comment] 2019-06-09 11:20
Al releases are available here https://sourceforge.net/projects/e107/files/e107/ and here https://github.com/e107inc/e107/releases

**Comment by Evgura** [comment] 2019-06-09 13:08
@Moc With the version of CMS 2.2.0 works fine.

**Comment by Moc** [comment] 2019-06-12 06:58
I really am unable to reproduce this on my test installations. Using PHP 7.2, and the BS_Magazine_01

In `Admin Area > Comment manager > Preferences`:

- `Allow users to post comments`: On
- `Allow anonymous posting?`: Off

Avatars are working fine, logged in and logged out. 
When not logged in, I get the message saying that I should sign up first. 

If I switch the anonymous posting to On, the name field appears and I can enter a comment. 

Not sure what else I can do here.... Can anyone else reproduce this issue?

**Comment by Evgura** [comment] 2019-06-12 09:40
@Moc I do not understand, does not work on this subject, other fine.

**Comment by Moc** [comment] 2019-10-11 14:52
Is anyone else able to reproduce this?

@Jimmi08 ?

**Comment by Jimmi08** [comment] 2019-10-11 16:09
PHP 7.2.16
latest github (sync yesterday)
Temp set:
![image](https://user-images.githubusercontent.com/5429548/66666911-06f98500-ec52-11e9-98a5-449765e82a8f.png)

Comment as Anonymous.
Button submit - no refresh, the second click - warning about the duplicate post

Result still the same
![image](https://user-images.githubusercontent.com/5429548/66666976-314b4280-ec52-11e9-868d-ff2999a5b142.png)

I found this too:
https://github.com/e107inc/e107/issues/3971

**Comment by Jimmi08** [comment] 2019-10-11 16:10
@Moc  test it with Allow anonymous posting?: **ON**

**Comment by Moc** [comment] 2019-10-12 10:41
Reproduced. Working on a fix.

**Comment by Moc** [comment] 2019-10-12 11:26
Turns out I created the bug when trying to fix another bug (#3813). 
This issue should be fixed now with the latest files, please test and let me know.

**Closed by Moc** 2019-10-12 11:26 UTC
Labels: testing required

**Comment by Moc** [comment] 2019-10-12 11:28
There are still two issues, but these are separate issues:

- Directly after entering an anonymous comment, the javascript that shows the newly added comment is not run. Therefore nothing seems to happen when the 'Submit comment' button is clicked, but the comment is added. After refresh, the comment appears. This works fine when logged in. 

- the datestamp directly after a comment is 'ago'. This is a bug in the relative date parsing. Will look into that. Same issue occurs in for example forum posts.
