### ISSUE TITLE
Forum moderator options not visible after upgrade to 2.2.0

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#3814] opened 2019-05-25 07:27 UTC
2.2.1 I mean

**Comment by Moc** [comment] 2019-05-25 13:46
Cannot reproduce on a clean git install, using the Bootstrap 3 theme. 

- Which theme are you using?
- Check the moderator class of the specific forum
- Make sure you are assigned to that userclass 

![image](https://user-images.githubusercontent.com/577978/58370211-335f6f80-7f04-11e9-942e-10af2692305f.png)


![image](https://user-images.githubusercontent.com/577978/58370216-3fe3c800-7f04-11e9-8209-93b81b7afad8.png)

**Comment by CaMer0n** [comment] 2019-05-25 19:00
@martyshep Are you using a custom template?

**Comment by martyshep** [comment] 2019-05-25 21:15
Do you mean using a custom theme? If so just using default bootstrap 3. The
user classes are correct. It was working before move to 2.2.1

**Comment by martyshep** [comment] 2019-05-28 15:38
I've done a clean install of 2.2.0 downloaded today from E107, installed the Forum plugin and I get the same issue.  No forum moderation items and no moderators are listed at the bottom of the forum window.

![Moderators none](https://user-images.githubusercontent.com/15772899/58491517-05c63080-8167-11e9-9062-3f6f3a551633.png)

**Comment by Moc** [comment] 2019-05-28 17:14
Again, please make sure that you (your user account) belongs to the userclass that is selected for that specific forum in the forum administration.

**Comment by Moc** [comment] 2019-05-28 17:15
Please show us a screenshot of the user and forum page of a clean install so I can compare.

**Comment by martyshep** [comment] 2019-05-28 17:20
It's a new fresh install with only an admin user on it, let me create main admin users on it for Moc and Tijn and you can look for yourself :) I'll PM you two.

**Comment by CaMer0n** [comment] 2019-05-28 17:28
@martyshep Could you please upgrade to the github version. I tweaked some forum things since the release of 2.2.0

**Comment by martyshep** [comment] 2019-05-28 17:35
just synch'd with latest on Github now and same issue on the new install site.

**Comment by CaMer0n** [comment] 2019-05-28 17:51
@martyshep Can you please PM me on Gitter?

**Closed** 2019-05-28 18:26 UTC
Labels: awaiting feedback, bug
