### ISSUE TITLE
Addo Forum Error.

### ISSUE THREAD

**Issue by pcmsodense** [e107inc/e107#3688] opened 2019-02-24 08:27 UTC
When i try to install the plugin Forun, i get this error : 
Success
is missing from the plugin db table

I need that plugin, can some one plz help me ??

I have just install the newst E107 CMS

**Comment by Jimmi08** [comment] 2019-02-24 11:13
And did you check if forum is installed?  I think that "is missing from the plugin db table" is related to something else (when you deleted folder manually) and not forum. Forum is part of core e107.

**Comment by Moc** [comment] 2019-02-24 11:14
This was a bug caused by an incompatibility with the newest PHP version (7.3). It is fixed in the next release. 

You can use the latest files from Github to get the latest updates: https://github.com/e107inc/e107/archive/master.zip

**Comment by Moc** [comment] 2019-02-24 11:51
Closing as duplicate https://github.com/e107inc/e107/issues/3621

**Closed by Moc** 2019-02-24 11:51 UTC
