### ISSUE TITLE
news grid menu -  weird behavior

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3828] opened 2019-06-05 19:50 UTC
I use the standard news grid menu (added in menu manager standard way).

If I don't fill the caption, tablestyle is not used 

![image](https://user-images.githubusercontent.com/5429548/58985406-8d511680-87db-11e9-88ad-1a16ce1a03d4.png)

As soon as I fill the caption, it behaves normal way:
![image](https://user-images.githubusercontent.com/5429548/58985479-ace83f00-87db-11e9-8f52-1fbd0f954035.png)

![image](https://user-images.githubusercontent.com/5429548/58985540-d6a16600-87db-11e9-849b-62d93f79b00d.png)

**Comment by Moc** [comment] 2019-06-06 13:25
Confirmed, not sure if this intentional or not. 

@CaMer0n your thoughts? :)

**Comment by Jimmi08** [comment] 2019-06-06 13:38
I have no problem if this is the intention.  So no need to change it only because of me.  It just surprised me.

**Comment by CaMer0n** [comment] 2019-06-06 21:33
It's intended. 

`news_template.php` works like this. When a caption value is found, **tablerender()** is used. 
`news_view_template.php` now works like this also.  See https://github.com/e107inc/e107/commit/be627b8c7bec6bb9f27de21d5b1e56e05cb7187d

**Comment by Moc** [comment] 2019-06-06 21:38
Alright. Closing.

**Comment by Jimmi08** [comment] 2019-06-06 21:38
Ok. caption key is not defined.  I mean this:
`if(isset($tmp['caption']) && $tmp['caption'] !== null)`

But if you insert data in menu manager, tablerender is used. Without template key.
Correct?

**Comment by CaMer0n** [comment] 2019-06-16 20:54
@Jimmi08 Correct. It's intended.

**Closed by CaMer0n** 2019-06-16 20:54 UTC
Labels: question
