### ISSUE TITLE
Downloads plugin does not recognize filetypes.xml + LAN issue

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#959] opened 2015-04-10 16:46 UTC
Updated file types, can Upload via uploads.php but in admin area plugin downloads upload do not notice the new file types added to the xml.

**Comment by LaocheXe** [comment] 2015-04-10 16:47
Also the LAN for previous file is not right, just shows the LAN_18 as the text

**Comment by Jimmi08** [comment] 2018-07-13 10:20
@LaocheXe @Moc  Could you check title of this issue to see without opening what about is it? Thanks

**Comment by Moc** [comment] 2018-07-15 13:39
Related #550

**Comment by Moc** [comment] 2019-02-04 13:41
Closing as duplicate of #550. I cannot reproduce the LAN issue anymore.

**Closed by Moc** 2019-02-04 13:41 UTC
Labels: bug, plugin: download
