### ISSUE TITLE
404 error from Sample Website

### ISSUE THREAD

**Issue by TerrificInTahoma** [e107inc/e107#2451] opened 2017-02-20 22:26 UTC
Ok, new user to the e107 CMS, but not un-aware of dev cycle (modern) vs 1980's and 1990's. (Before Internet and 24/7).

Had a look at CMS system, and attempted to change the "Welcome Here" message to have **BOLD TEXT**, in a portion of the Welome! page.

Saved the change, as an Admin user. Then went back to see the results.

The Entire welcome page had changed!

System Accepted Change, but after Refresh in PaleMoon Browser, get a 'HTTP 404' error as if the file is not found.

I hope I did not break anything, but then , what would be development be with out trying out 'new features'.

So I post the development link here, to see if others get the same response, or if it was that any other changes were happening to the e107 site at the same time. Since the entire welcome page was obliterated , and instead of being three columns with three articles, (and Lorum Ipsum was in the text) as was initially, now, only the welcome and start using site page pops up.

Strange.

see this link:
[https://demos6.softaculous.com/e107/e107_admin/e107_admin/admin.php](url)

**Comment by CaMer0n** [comment] 2017-02-21 01:57
@TerrificInTahoma very strange indeed. Where is your site installed?

**Comment by TerrificInTahoma** [comment] 2017-02-21 02:39
@CaMer0n , it is the e107 Demo Website (Sample). Username =admin, pw = password.

**Comment by rica-carv** [comment] 2017-02-21 09:48
@TerrificInTahoma On the [frontend homepage](https://demos6.softaculous.com/e107/), the welcome message is still visible, at least using ff...

**Comment by tgtje** [comment] 2017-02-22 15:01
tested on demo (with PaleMoon too) > not replicable. 
Works fine...

**Comment by rica-carv** [comment] 2017-02-22 17:47
@tgtje Have you tried his link (https://demos6.softaculous.com/e107/e107_admin/e107_admin/admin.php) ???
Seems it's the one giving problems, but anyway, it's not a standard e107 admin link, therefore, who knows what's there?

**Comment by tgtje** [comment] 2017-02-22 22:20
@rica-carv  Yes (out of frame (direct link)) and it does not give errors (for me) and the 404 is correct ! Since page (link) does not exist it does what it has to do > 404
Same as using (ex) https://demos6.softaculous.com/e107/e107_plugins/e107_plugins/download/download.php  is possible to type, but is 404... So all in all i do believe it is just a mistyped/pasted url.

**Comment by Moc** [comment] 2017-03-02 17:55
This is probably due to an incorrect configuration of the non-official demo website hosted by softaculous. Closing this issue as it is not a bug in the core. Further discussion can be done on Gitter. 

https://gitter.im/e107inc/e107

If the issue occurs on your own installation, then please do let us know.

**Closed by Moc** 2017-03-02 17:55 UTC
