### ISSUE TITLE
what could be reason for problem with missing ?> in lan files?

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4129] opened 2020-04-17 08:28 UTC
admin_config.php file of nofollow plugin returned black page on live site, but on local site it worked. 

After checking log:

`PHP Parse error:  syntax error, unexpected end of file in ***/web/e107_plugins/nofollow/languages/English/English_front.php on line 1, referer https://www.e107sk.com/e107_admin/plugin.php?mode=installed&action=list&path=nofollow
PHP Parse error:  syntax error, unexpected end of file in ***/web/e107_plugins/nofollow/languages/English/English_front.php on line 1
`

that lang file looks like this (picture to see hidden characters):

![image](https://user-images.githubusercontent.com/5429548/79548440-bf870200-8095-11ea-8c0b-51a723a13091.png)

After changing to 
```
<?php
?>
```
everything works.

Again clean installation on localhost works, the live site has installed more languages (not used).

**Comment by Moc** [comment] 2020-04-17 09:34
Probably related to the 'encoding' of the file. It must be saved as "UTF-8 without BOM".

**Comment by tgtje** [comment] 2020-04-17 09:47
Just did some search as the nofollow on org does not contain those files, so assuming it are the files as being present on Arun's github repo. They do contain those files.
However since (main title) missing ?>; this is now standarized  to not use them as closing the file.
That said, probably related due to the fact the available lang file are created with a single '  and would in present days be "  ..  .maybe that is the issue here (not being adjusted?).

**Comment by Jimmi08** [comment] 2020-04-17 09:49
> Probably related to the 'encoding' of the file. It must be saved as "UTF-8 without BOM". The character you see is BOM.

@Moc I always use UTF-8 BOM for all my files, I never heard about this. Without problems. So I should use UTF8-8 no BOM?   

It would be a problem on local server, wouldn't it?

**Comment by tgtje** [comment] 2020-04-17 09:52
> It would be a problem on local server, wouldn't it?
No, this is how i create all files local.. (UTF8 without)

**Comment by Jimmi08** [comment] 2020-04-17 09:56
> Just did some search as the nofollow on org does not contain those files, so assuming it are the files as being present on Arun's github repo. They do contain those files.
> However since (main title) missing ?>; this is now standarized to not use them as closing the file.
> That said, probably related due to the fact the available lang file are created (define coding) with a single **'** and would in present days be **"** .. .maybe that is the issue here (not being adjusted?).

e107.org version is outdated... I think, there were some fixes from that time...

So do you mean that some other file (f.e. old plugin) uses that bad way? It would explain why it works on a clean installation.  Hm...  It would be easier to delete this file... 

But I suppose that core doesn't count with empty lang file (just a open PHP tag)...  In fact, this is the first time I saw it in some plugin.  

And maybe if the core finds lan definition DEFINE('  - it should skip this file with some warning. 

Thanks, both, for help.

**Comment by Moc** [comment] 2020-04-17 10:04
> So do you mean that some other file (f.e. old plugin) uses that bad way? It would explain why it works on a clean installation. Hm... It would be easier to delete this file

Yes, in the past, some authors had BOM in their files but this aren't that many plugins anymore nowadays.

**Comment by Moc** [comment] 2020-04-17 10:08
I am doubting my initial answer btw... BOM usually starts with several characters before the first 'normal' character. In the screenshot, it shows some other character but I don't know what it is. I do suspect the issue is related to file encoding, so using 'UTF-8 without BOM' should resolve the PHP error anyway.

**Comment by tgtje** [comment] 2020-04-17 10:09
Headers already send message/warning will also be more common when files often use a closing tag. >> Not using it, often prevents  'call them illegal'  whitespaces after close etc..

**Comment by Jimmi08** [comment] 2020-04-17 10:20
@Moc 
Tested. It didn't help. Just to be sure: That hidden sign is the end of the line but not newline . 

![image](https://user-images.githubusercontent.com/5429548/79559168-8c4c6f00-80a5-11ea-84ee-af599def80b5.png)

Fatal error again. It would be related to old plugins.

**Comment by Moc** [comment] 2020-04-17 10:26
Hmm right, then the character means something else. Not sure. 

I'm closing this issue as I think it's just a minor issue that isn't occurring on larger scale. Let us know if you need any further help :)

**Closed by Moc** 2020-04-17 10:26 UTC
Labels: type: question

**Comment by tgtje** [comment] 2020-04-17 10:29
Just last remark, as i did test the front.php file. It is coded as DOS ANSI west-europian (1252)

**Comment by Jimmi08** [comment] 2020-04-17 10:45
> Just last remark, as i did test the front.php file. It is coded as DOS ANSI west-europian (1252)

@tgtje no idea, I cloned GitHub version, opened the file and I can see UTF8 no BOM there.  

> I'm closing this issue as I think it's just a minor issue that isn't occurring on larger scale. 

@Moc No problem. I created it to be aware that something like this can happen with this plugin. Or when a similar problem happens. I just too much often think that I had a similar problem but I didn't create an issue so I don't remember details.  And I don't think that plugin is maintained anymore.

By the way, this functionality should be part of the core.

**Comment by tgtje** [comment] 2020-04-17 14:56
@Jimmi08  I use PsPad  (using) CP auto detect, it tells me what file original is stored in.

(bottom line eg : Unix  : Unicode UTF-8 no BOM (65001) is my standard working mode)

**Comment by Jimmi08** [comment] 2020-04-17 15:13
> @Jimmi08 I use PsPad (using) CP auto detect, it tells me what file original is stored in.
> 
> (bottom line eg : Unix : Unicode UTF-8 no BOM (65001) is my standard working mode)
> 
> Iff CP mode is **not** activ, and standard = Unix : Unicode UTF-8 no BOM (65001) It is the setting which runs _default_.
> So if you would rework that ANSI file, and save it in **that** screen, it will store in UTF 8 no BOM coding..

Me too. But they so messed up this detection in the latest versions (the first version of 2020), that I am not sure about anything now.  You can be right, but for example, my definitely utf8 files (I don't use anything else), it autodetected as ISO-x (because there were national characters) and after saving (because so many years it didn't occur me to check this)...  I am sure you can imagine the result. It's already fixed, but...  I am moving slowly to Visual Code
.
