### ISSUE TITLE
e107_admin/prefs.php - results in You can not connect to this site

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#3174] opened 2018-06-05 12:33 UTC
I tried latest github on localhost, windows, xampp, php 7.0.29

Admin works, but Prefs end with error.

I was able to get to this line when I tried to find where it stops.:

![image](https://user-images.githubusercontent.com/5429548/40976158-75cc3e8c-68cd-11e8-95c0-fc7fb387bc62.png)

**Comment by CaMer0n** [comment] 2018-06-05 17:01
@Jimmi08 I just tried with PHP 5.6 and 7.2 without any problems. What do your apache error logs say?

**Comment by Jimmi08** [comment] 2018-06-05 20:46
I will try fresh install tomorrow. Nothing, just that child thread stopped to work or similar. No visible error.

**Comment by Jimmi08** [comment] 2018-06-06 07:07
Today, complete clean install with latest github

- info about core update, updated
- the same problem after click on prefs.php
- frontend and rest of admin works (at least it looks like)

- PHP 7.0.29, Windows 10

Problem is with function supported($mode = FALSE) in this part:
 
![image](https://user-images.githubusercontent.com/5429548/41022032-a3f38892-6968-11e8-846e-77bd03f4c1f4.png)

Error log (it's localhost, so I left it empty and then click on prefs page)

```
[Wed Jun 06 09:05:47.462936 2018] [mpm_winnt:notice] [pid 2800:tid 616] AH00428: Parent: child process 5888 exited with status 3221226356 -- Restarting.
[Wed Jun 06 09:05:48.022434 2018] [ssl:warn] [pid 2800:tid 616] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jun 06 09:05:48.054387 2018] [mpm_winnt:notice] [pid 2800:tid 616] AH00455: Apache/2.4.33 (Win32) OpenSSL/1.0.2n PHP/7.0.29 configured -- resuming normal operations
[Wed Jun 06 09:05:48.054387 2018] [mpm_winnt:notice] [pid 2800:tid 616] AH00456: Apache Lounge VC14 Server built: Mar 22 2018 10:55:30
[Wed Jun 06 09:05:48.054387 2018] [core:notice] [pid 2800:tid 616] AH00094: Command line: 'c:\\xampp\\apache\\bin\\httpd.exe -d C:/xampp/apache'
[Wed Jun 06 09:05:48.236287 2018] [mpm_winnt:notice] [pid 2800:tid 616] AH00418: Parent: Created child process 9384
[Wed Jun 06 09:05:49.133850 2018] [ssl:warn] [pid 9384:tid 596] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jun 06 09:05:49.343749 2018] [ssl:warn] [pid 9384:tid 596] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name
[Wed Jun 06 09:05:49.401595 2018] [mpm_winnt:notice] [pid 9384:tid 596] AH00354: Child: Starting 150 worker threads.
```

**Comment by Jimmi08** [comment] 2018-06-06 07:19
I have it.  

If I let only 25 fields in $strftimeFormats array (until letter Y), it works. If I add "Z", it crashes.

**Comment by CaMer0n** [comment] 2018-06-06 17:09
Thank you @Jimmi08 !
An actual error message relevant to this line of code would be helpful.

**Comment by Jimmi08** [comment] 2018-06-06 17:17
@CaMer0n in first post, there is no error message, you have there apache log error too.

**Comment by CaMer0n** [comment] 2018-06-06 17:26
@Jimmi08 Yes, I saw, but there is no 'fatal' error. Do you have the xdebug module installed and 'display_errors' set to "on" ?

**Comment by Jimmi08** [comment] 2018-06-06 19:09
do you mean on Apache in xampp?  I have no idea.  I could try display_errors tomorrow.

**Comment by Jimmi08** [comment] 2018-06-07 06:02
No change. No messages. Probably something in enviroment.

**Comment by Moc** [comment] 2019-01-16 16:44
I was not able to reproduce this on various environments. If anyone else is able to reproduce the issue, please let us know here and I'll re-open. Closing for now.

**Closed by Moc** 2019-01-16 16:44 UTC
Labels: testing required

**Comment by Moc** [comment] 2019-01-17 12:32
https://github.com/e107inc/e107/issues/3625
