### ISSUE TITLE
Object of class core_index_index_controller could not be converted to string

### ISSUE THREAD

**Issue by GaneshKandu** [e107inc/e107#4203] opened 2020-06-25 09:48 UTC
## Bug Description
```
Fatal error: Uncaught Error: Object of class core_index_index_controller could not be converted to string in e107_handlers/application.php:4061 Stack trace:
#0 e107_handlers/application.php(3007): eResponse->appendBody(Object(core_index_index_controller))
#1 e107_handlers/application.php(3055): eController->addBody(Object(core_index_index_controller))
#2 e107_handlers/application.php(569): eController->dispatch('actionIndex')
#3 e107_handlers/application.php(370): eDispatcher->dispatch(Object(eRequest), Object(eResponse))
#4 e107_handlers/application.php(417): eFront->dispatch()
#5 index.php(81): eFront->run()
#6 {main} thrown in e107_handlers/application.php on line 4061
```

## How to Reproduce
1. install on php 7.4
2. go to fronted
3. See error

### PHP Operating System

``Linux cpanel.nuftp.com 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux``

### PHP Version

PHP Version 7.4.7

**Comment by CaMer0n** [comment] 2020-06-26 19:55
Hello @GaneshKandu !
Thank you for posting this issue.  So far, I am unable to reproduce it. 
Could you please confirm that you're using the Github version of e107. ie. `v2.3.0 (git) ` ?

**Comment by GaneshKandu** [comment] 2020-06-27 09:22
Hi @CaMer0n 

I am using `2.2.1`

**Comment by GaneshKandu** [comment] 2020-06-27 09:28
also getting same error in ``v2.3.0 (git)``

**Comment by Moc** [comment] 2020-06-27 09:29
@GaneshKandu can you please try with the latest files from GitHub? These files will soon be published as the 2.3.0 release

**Comment by Moc** [comment] 2020-06-27 09:30
I'll do some testing and get back to you

**Comment by GaneshKandu** [comment] 2020-06-27 09:31
sure
some extra info.

``
Fatal error:  Uncaught Error: Object of class core_index_index_controller could not be converted to string in e107_handlers/application.php:4083
Stack trace:
#0 e107_handlers/application.php(3012): eResponse->appendBody(Object(core_index_index_controller))
#1 e107_handlers/application.php(3060): eController->addBody(Object(core_index_index_controller))
#2 e107_handlers/application.php(572): eController->dispatch('actionIndex')
#3 e107_handlers/application.php(373): eDispatcher->dispatch(Object(eRequest), Object(eResponse))
#4 e107_handlers/application.php(420): eFront->dispatch()
#5 index.php(81): eFront->run()
#6 {main}
  thrown in e107_handlers/application.php on line 4083
``

**Comment by Moc** [comment] 2020-06-27 12:08
Just did a fresh installation with the files from Github on PHP 7.4.7 and no issues so far.

**Comment by Moc** [comment] 2020-06-27 12:11
@Deltik Any idea?

**Comment by CaMer0n** [comment] 2020-06-27 19:35
@GaneshKandu I was able to reproduce it. Working on it.

**Comment by CaMer0n** [comment] 2020-06-27 20:13
@GaneshKandu It should be fixed now in the latest github version.

**Closed** 2020-06-27 20:12 UTC
Labels: status: testing required, type: bug

**Comment by GaneshKandu** [comment] 2020-06-29 04:59
@CaMer0n Thanks ! working now
