### ISSUE TITLE
Issue: Signup.php and Resend Activation Email

### ISSUE THREAD

**Issue by LaocheXe** [e107inc/e107#2342] opened 2017-01-28 22:49 UTC
So Resend activation Email gives a green box saying the email has been sent however at the top of the box says Error

Also for some reason when a user creates an account they get a white screen, and no email is sent.

**Comment by AdocArg** [comment] 2017-02-01 21:37
I have a similar issue (in localhost with xampp latest version, I don't tried in a web server yet) and because of that I post here. Whenever I try to register I receive this message: "There was a problem, the registration mail was not sent, please contact the website administrator.", it's necesary activated something in the admin panel or my Xampp has a bad configuration?

Thanks

**Comment by Reconix** [comment] 2017-02-01 21:59
![error](https://cloud.githubusercontent.com/assets/559757/22528023/70b8e510-e8c9-11e6-8ab2-1a40e11cba8c.png)
Guessing the error looks something like that, ignore the ### though.

Test done on a live server.

**Comment by Moc** [comment] 2017-02-02 13:24
@AdocArg If I remember correctly, XAMPP needs proper configuration in order for the email to work. it will not be able to send any email with the default settings.

**Comment by AdocArg** [comment] 2017-02-02 14:43
Ah ok, I use default settings. I tried in a live web server and when I test to send me an email (Users-->Mail-->Preferences-->Send test email to..) nothing happens. (I have an earlier review of e107 in the same web server and when I try the same, it works)

Also now I have the same problem of the post, when I register an account the page goes blank.

Thanks for help!

**Comment by Moc** [comment] 2017-02-02 14:48
Confirmed the blank page, bugfix incoming.

**Comment by Reconix** [comment] 2017-02-02 15:29
I should have mentioned the sending of e-mails worked fine on the tests I done.

@AdocArg If you do a quick google search on how to send mail through Xampp all should be well on that front :)

**Comment by AdocArg** [comment] 2017-02-02 15:44
@Reconix I searched (on google) and I configured xampp to send emails and it doesn't work. But beyond that, I tried in a web server that's has a good configuration and neither works me. (with an earlier review of e107 in the same web server, works perfect and I receive the email). If you receive the email with that option, i don't know.. it's strange haha.

Thanks anyway!

**Comment by LaocheXe** [comment] 2017-02-06 03:33
@AdocArg I don't know much about Xampp and sending email, however, I have had Xampp on a server, and also had to install a email server, i don't know if that help sending email but at the time I was focused on setting up my own email server with web interface.

**Comment by AdocArg** [comment] 2017-02-06 03:45
@LaocheXe Thanks, then I'll look for more information about what you're telling me (I continued with other things and didn't try again honestly). But the strange is that the web host that i have i don't know if they use xampp (and I doubt it a little) and also doesn't work. When i finished the terms and conditions of my web i'm gonna return to see this problem.

**Comment by Moc** [comment] 2018-06-27 11:59
@LaocheXe @Reconix Is the blank screen issue still occuring?

**Comment by Reconix** [comment] 2018-07-03 19:33
![testemail](https://user-images.githubusercontent.com/559757/42240714-152980d2-7f00-11e8-88df-1548bf903c69.png)

Tested this on 2.1.7

**Comment by CaMer0n** [comment] 2018-07-15 19:29
Thanks @Reconix  Closing.

**Closed by CaMer0n** 2018-07-15 19:29 UTC
Labels: Help Wanted, bug
