### ISSUE TITLE
 Activate Download Agreement - bad parsing 

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#4686] opened 2022-02-05 20:39 UTC
## Bug Description
when you activate Download Agreement, message is not correctly parsed

![image](https://user-images.githubusercontent.com/5429548/152658096-b215bc94-fbbd-43dc-b010-acae6ae76e49.png)

## How to Reproduce
Activate, use tinymce 
![image](https://user-images.githubusercontent.com/5429548/152658123-9240d176-27ea-4081-a25a-b666ece3df3f.png)
Try to download something

## Expected Behavior
correct message

 
## Server Information
PHP 7.4
stable 2.3.1
 
Thanks

**Comment by Deltik** [comment] 2022-02-06 13:10
I can't reproduce this bug.  When I set the source of the "Agreement Text" to the following:
```html
[html]<!-- HTML comment -->
<p><strong>https://github.com/e107inc/e107/issues/4686</strong></p>
<!-- HTML comment -->[/html]
```
There is no HTML comment in the alert box:
![image](https://user-images.githubusercontent.com/1364268/152682366-a799fc57-cf27-4302-83b0-a9afa88b6c69.png)

**Comment by Jimmi08** [comment] 2022-02-06 13:40
@Deltik was there a related change after the 2.3.1 release?

![image](https://user-images.githubusercontent.com/5429548/152683584-ff8c4177-9fcb-4a9b-bcb7-b2ca762439a3.png)

The front end is in a different language... 

What are your settings for this?

![image](https://user-images.githubusercontent.com/5429548/152683635-e7d94d7f-1255-4176-aad6-75f217f609b8.png)

**Comment by Deltik** [comment] 2022-02-06 13:43
I created a new test installation on e107 v2.3.1, since that's the version you indicated in this issue.

Here are the Site Preferences » Content Filters:

![image](https://user-images.githubusercontent.com/1364268/152683780-409148ee-bacb-429c-8f5e-e21d02fcff4a.png)

**Comment by Jimmi08** [comment] 2022-02-06 13:48
I have something
in download list 
![image](https://user-images.githubusercontent.com/5429548/152683898-effcfee3-d847-47aa-8d19-162773a8099b.png)

it works correctly
![image](https://user-images.githubusercontent.com/5429548/152683912-34a42b2e-7fab-49c5-a5f8-8c1025c94697.png)

- in download view 
![image](https://user-images.githubusercontent.com/5429548/152683931-6fc5686e-8558-42f9-9a9d-d9efd61afce3.png)

**Comment by Deltik** [comment] 2022-02-06 16:17
@Jimmi08: I did some substantial refactoring because the escaping was done inconsistently in five places:
* `download_shortcodes::sc_download_list_link()`
* `download_shortcodes::sc_download_list_name()`
* `download_shortcodes::sc_download_mirror_link()`
* `download_shortcodes::sc_download_view_link()`
* `download_shortcodes::sc_download_view_name_linked()`

I extracted all accesses of `e107::getPref()['agree_text']` into `download_shortcodes::getAgreeTextAsHtmlAttributeJsonString()` and made a new API ([`e_parse::toAttributes()`](https://github.com/e107inc/e107/blob/cf86267e62874b890f3eda862a035d60d51e584d/e107_handlers/e_parse_class.php#L1865-L1878)) to simplify the concatenation of the alert box `onclick` event.

Full details: https://github.com/e107inc/e107/pull/4688

**Comment by Deltik** [comment] 2022-02-06 16:18
@Jimmi08: I did some substantial refactoring because the escaping was done inconsistently in five places:
* `download_shortcodes::sc_download_list_link()`
* `download_shortcodes::sc_download_list_name()`
* `download_shortcodes::sc_download_mirror_link()`
* `download_shortcodes::sc_download_view_link()`
* `download_shortcodes::sc_download_view_name_linked()`

I extracted all accesses of `e107::getPref()['agree_text']` into `download_shortcodes::getAgreeTextAsHtmlAttributeJsonString()` and made a new API ([`e_parse::toAttributes()`](https://github.com/e107inc/e107/blob/cf86267e62874b890f3eda862a035d60d51e584d/e107_handlers/e_parse_class.php#L1865-L1878)) to simplify the concatenation of the alert box `onclick` event.

If merged, I encourage you to replace all manual HTML attribute concatenations with the new `e_parse::toAttributes()` method in your own code (unrelated to this issue).

Full details: https://github.com/e107inc/e107/pull/4688

**Comment by Jimmi08** [comment] 2022-02-06 16:21
I will test it asap. Big thanks.

Could it be related to this too? 

https://github.com/e107inc/e107/issues/4687

**Comment by Deltik** [comment] 2022-02-06 17:22
https://github.com/e107inc/e107/issues/4687 does use a method in common (`e_parse::toText()`), but it's a separate issue.

**Closed** 2022-02-22 21:41 UTC
Labels: type: bug, status: pending
