### ISSUE TITLE
e107_admin/cron.php language issue

### ISSUE THREAD

**Issue by Alex-e107nl** [e107inc/e107#2273] opened 2017-01-13 21:09 UTC
Do not know since when it does not show anything anymore but now it doesn't.. just a blank screen nothing no code...

**Comment by Moc** [comment] 2017-01-13 21:38
PHP version please

**Comment by tgtje** [comment] 2017-01-13 23:01
Just adding : updated a php 7.0.12  2 h ago site (+ Dutch language up to date)
Do see cron php BUT only WILL display in Dutch (not English).
Does not change anywhichway i set languages for this page (cron php) All files are present in lang system.

**Comment by Alex-e107nl** [comment] 2017-01-14 04:58
PHP Version 5.6.17 Dutch and English :-)

**Comment by tgtje** [comment] 2017-01-14 18:17
Happens along the line since 15-12-2016 installed version) files dd used (17-12) functional.

**Comment by Moc** [comment] 2017-01-14 18:41
Can you check the error log please? There should be an error in there.

**Comment by tgtje** [comment] 2017-01-15 15:07
No things that could relate to it (php 5.x and php 7.x), so file by file comparison... Got stuck on issues > i can not pinpoint where they were added, but there is array defined with UNused Lans
admin/cron php
line 158				5 => array(  etc....  ??? 
LAN_CRON_06_1 ; LAN_CRON_06_2 ; LAN_CRON_06_3
Have to stop there...... 
Maybe cron has to be revised...(dev)

(debugging reports that the language files ARE called, but Name and Description tables do not react on language).

**Comment by MikeyGMT** [comment] 2017-01-15 15:57
I did some LANs work on recently. https://github.com/e107inc/e107/commit/9877a9eebed1ab26ae9cfebd6417fa4f7a01df6b I can't see anything that could break cron. I wonder if adding the new LANs in the Dutch file helps?

**Comment by Moc** [comment] 2017-01-15 16:46
@Alex-e107nl @tgtje Please follow these steps:

- Add ` define('e_DEBUG', true);` to the e107_config.php file
- Go into preferences > advanced features > enable developer mode
- Enable debug mode (for example by navigating to `e107_admin/admin.php?[debug=basic+]`)

- Check the e107_admin/cron.php page again to see if any errors appears.
- If the blank page shows up without displaying an error, please check the Apache error log. This may be accessed either through the control panel (such as cPanel or DirectAdmin) or directly through FTP (either in the root of the e107 installation or in the public_html directory). 

Let me know.

**Comment by tgtje** [comment] 2017-01-15 19:12
Well tested proposed again now on local and live(=php 7) only error ( message) Using Cached Core Update Data 	admin_shortcodes->sc_admin_update()() 	C:\xampp\htdocs\214\e107_handlers\shortcode_handler.php 

Also made a fresh install, used Dutch (latest updated) as install language : visited cron php > working as should... (same message log) no other... Now trying to replicate : using settings/languages  and change ALL to use english.... > bamm there is the same happening  dutch stays in Name and Description... _vice versa does give no results back to (working 100%) mode.._  (now guessing iff elan has something to do with it)  (no entries in error logs (php and apache  note : local))

**Comment by MikeyGMT** [comment] 2017-01-15 20:39
There was a commit of a "proper" : ) code change after mine.

**Comment by tgtje** [comment] 2017-01-16 12:14
Just adding : again a new fresh install (latest) now using French pack as install language : identical behaviour as previous installments... So it is definitly something in the core... (to eliminate Dutch language on which prev. results were based).( Installed system is out of pack..no added plugs etc.. pure...)

**Comment by Alex-e107nl** [comment] 2017-01-16 12:51
@ Moc, i've done what you said... error is:
Fatal error: Call-time pass-by-reference has been removed in /home/andrekoot/domains/e107.nl/private_html/e107_plugins/calendar_menu/e_cron.php on line 141

Sorry was away for the weekend...  hope this helps.. seems like the calendar menu cron gives the failure..

Alex

**Comment by Moc** [comment] 2017-01-16 15:27
Thanks, this is what I needed. Will push out a fix asap.

**Comment by Moc** [comment] 2017-01-16 15:29
Please update the e_cron.php file with this fix: https://github.com/e107inc/calendar_menu/commit/3026122716698514a0437fde26dd7bc6b91d0465

**Comment by tgtje** [comment] 2017-01-16 18:10
Do have to mention while Alex did post his issue, i got the other... This (my postings) is not related to calendar_menu since it is NOT core

**Comment by Moc** [comment] 2017-01-16 18:14
@tgtje Do you have the calendar plugin installed? If yes, does my fix work? If not, and if you are still getting a blank page, then something is still wrong. I suspect there are no issues in the other e_cron.php files. 

If you are still getting a blank page, then retrieving the exact error from the logs is the best way to go.

**Comment by tgtje** [comment] 2017-01-16 18:17
In posting described: language relationship on cron php Since Alex posted blank page (i did test, NO blank page but the above) No i do not have calendar_menu installed..  
So basically we have 2 issues here....

**Comment by Moc** [comment] 2017-01-16 18:19
I don't understand. Is there still an issue left with the cron (schedule tasks) page on either English or Dutch (or any other language for that matter?).

**Comment by tgtje** [comment] 2017-01-16 18:20
**Yes** switching to and from any language keeps the tables in cron php  NAME and DESCR. in the last used language (will not return to the one wished...)

**Comment by Moc** [comment] 2017-01-16 18:21
Did you clear the e107 and browser cache after switching languages?

**Comment by tgtje** [comment] 2017-01-16 19:15
Sorry for the timeframe, yes always (knowing cache has impact throughout and to a lot of things)

**Comment by Alex-e107nl** [comment] 2017-01-16 20:09
Moc, fix works!!
 Plugins 	Calendar Subscriptions 	Process notifications of events on the calendar 	calendar_menu::processSubs

**Comment by Moc** [comment] 2017-01-16 23:12
@tgtje I cannot reproduce your issue:
- Latest git, latest Dutch files. 
- Switch from English to Dutch
- Navigate to cron (ingeplande taken) 
- Change language back to English
- Navigate back to cron
- All LAN's are fine (except for the missing help text in Dutch). 

Closing this issue as the blank page bug is sorted. 
@tgtje If you can find more info on this later, please let me know.

**Comment by Moc** [comment] 2017-01-16 23:39
@tgtje I am commiting a change to e107_admin/cron.php which may help with your issue. Let me know.

**Comment by tgtje** [comment] 2017-01-17 12:55
@Moc   quote : 
All LAN's are fine (except for the missing help text in Dutch).

? which one a hover or... Iff it is the help file on left side, than there is something happening...

well let me show you what is happening (this is from a live server (git updated yesterday) php 7.0.10 (identical to my locals on php 5.6.x and 7 ) wamp and xamp.

https://www.tgtje.nl/tempie/Untitled 22.mp4

**Comment by tgtje** [comment] 2017-01-17 20:50
back again, using the uploade changes (full overwrite), NO changes.
Adding : when commenting the language lines in file, you can see that lang.. changes to LAN (as expected).
Still this does not apply to the tables (or arrays probably) that have to switch the languages too (Name; Description aka LAN_NAME and LAN_DESCRIPTION .

Well maybe i may find it but please for yourself do a search on 	$cronDefaults['_system'] = array(
number 5   LAN >  'name' LAN_CRON_06_1  Where does it come from ? It appears in v2 alpha2 first..
(mystery).

Digged deeper : did also walk through the dbases... e107_cron table is FRENCH and stays french ( did even delete the lang pack)...
So it looks like it updates the dbase after first change??, but never 'refreshes'the dbase again when using another language....

**Comment by Moc** [comment] 2017-01-17 23:20
@tgtje Does the same issue appear when using only the Settings > Language page, and not the globe icon in the top right corner. I have a feeling that this one is causing some issues. I'll do more testing asap.

**Comment by tgtje** [comment] 2017-01-19 00:55
Not having to much time now, will be more to weekend.. Do not hurry yourself, we do know it exists and if the rest works, we try to find a way to solve it. To eliminate (because no reactions from others) if do have to eliminate any 'might be from' the pc i work on. Anybody else who can test please: contribute your findings.

**Comment by tgtje** [comment] 2017-01-19 22:50
Just adding in case forget : each install now throws 1 time only (untill something is changed...(change is not of influence> other page etc..) > message > can not load prefs LAN_CRON_6

**Comment by CaMer0n** [comment] 2017-01-21 19:30
@tgtje This was changed to a debug message instead of an error message. Should be okay now.

**Comment by tgtje** [comment] 2017-01-22 14:31
@CaMer0n correct on message, still no go on refreshing the dbase tables for name and description when switching languages. Once stored in dbase, no luck calling language defines... Do not see it happen elsewhere.. Because i DO use Dutch (user funct)  a lot, and most will use English (for dev) this might be overseen ?. _Still waiting to hear iff i am the sole one_ (it happens live server, and local)

**Comment by Moc** [comment] 2018-02-28 14:27
@tgtje is this issue still occurring?

**Comment by tgtje** [comment] 2018-03-02 00:20
@Moc  did not take a quite long time into it, just tested on the php 7.2.2. version (latest nl pack):
 Yes (for me at least) it is still the same...

**Comment by Moc** [comment] 2019-02-04 20:43
@tgtje can you please check with the latest files to see if the issue is resolved?

**Comment by tgtje** [comment] 2019-02-06 17:41
Nope, my issue i see is not changed. Need some more time to investigate.
Testcasing if it does matter which language is used during install and why one system has columns correct, mixed etc... (admin cron php tables)

**Comment by tgtje** [comment] 2019-02-09 08:32
SCHEDULE TASK
Follow up (did some testing) here is result in step (visual) NOTE : columns NAME and DESCIPTION
Normal install using Dutch as install language : 
![crona](https://user-images.githubusercontent.com/1811857/52518444-eb655700-2c4a-11e9-8b63-c3a1289d49a2.jpg)
all is as normally should be. (identical for an English used install) All columns presentr their own language.

Using language switching (system settings, not multilang plug) FROM Dutch to English
![cronb1](https://user-images.githubusercontent.com/1811857/52518500-77777e80-2c4b-11e9-8968-486b404d163f.jpg)
Note the textual parts of Name and description (they remain Dutch eg.. they are core DB stored)

Added language same result (switch to Hungarian)

![cron1](https://user-images.githubusercontent.com/1811857/52518526-dd640600-2c4b-11e9-9195-13b1bef9277f.jpg)

Now language table setting : create a db language table for Englsih (it will copy the dutch db to an english one and adds it to db; mind...since a copy the table WILL hold dutch tekst).

**Activating the usage of multilanguage tables as setting**, so it will use the copy db table when switching.

That does work HOWEVER the textual content (as being a copy of the dutch one) is still Dutch.

It will NOT load the language defines as made from/within the language packs. 

Now the last test (involving changing the Database table directly !!!, i finally get result
So it seems, once installed it will not load the defines (array tekst) into there, but database stored text ???.

This is the outcome after changing db table and multilang tables active.

![cron2](https://user-images.githubusercontent.com/1811857/52518623-75162400-2c4d-11e9-8537-fbae7b64dd22.jpg)
Hope it makes it easier to understand what happens (does not change using live server or local)

**Comment by Moc** [comment] 2019-10-03 09:41
@CaMer0n This seems to be an issue with the multilanguage tables. Any ideas?

**Comment by tgtje** [comment] 2020-04-28 10:48
Going through open issues; did same testing now (local) on php 7.3.5.
As is, and no idea when something was changed or commited, i can mention the issue seems to be gone.
Switching to another language provides correct language use.
**Since it is not my topic, i can not close it.**

**Comment by Moc** [comment] 2020-04-28 11:44
Thank you for the update @tgtje

**Closed** 2020-04-28 11:44 UTC
Labels: status: testing required, type: bug
