### ISSUE TITLE
It does not show download categories

### ISSUE THREAD

**Issue by oxigeno2** [e107inc/e107#2897] opened 2017-12-04 18:42 UTC
It does not show download categories, just created or existing.

![downloadcategory](https://user-images.githubusercontent.com/2928863/33568879-28e6a7e0-d928-11e7-98a3-3f2c7146c1d4.png)

**Comment by tgtje** [comment] 2017-12-04 21:08
Fresh install (php 7.1.11 local) 2 days old, freshly synced before posting. Empty downloads> can not replicate (working) Dbase error? image> records = 0

Needs more info..

**Comment by oxigeno2** [comment] 2017-12-04 22:50
Installed Version 2.1.7 (git)
Just updated php to version 7.1.11, problem persists.

![verzephp](https://user-images.githubusercontent.com/2928863/33579839-5ca001e4-d94b-11e7-8c7b-d1144570f6bc.png)

There are categories in the database:

![createdownload](https://user-images.githubusercontent.com/2928863/33579848-694a78c0-d94b-11e7-88a8-060ed7c5ea6c.png)

Debug PHP errors in the picture:

![phperror](https://user-images.githubusercontent.com/2928863/33579867-79676240-d94b-11e7-9d14-12ed119645e4.png)

**Comment by Jimmi08** [comment] 2017-12-05 07:46
Use SQL debugger, those errors are just warnings.

php 7.0.15, no problems - I tried empty record, no parent...  they are still displayed.

![image](https://user-images.githubusercontent.com/5429548/33595443-77974dc0-d998-11e7-9dbb-636d92edd972.png)

**Comment by Jimmi08** [comment] 2017-12-05 07:48
Confirm.  As soon as you leave administration and going back, categories are empty.

**Comment by tgtje** [comment] 2017-12-05 10:48
Sorry but when looking at picture i do NOT see a shift in cats > eg.. are it only PARENTS ? 
A child (which carries the downloads) is always 'out of line' eg shifted in dropdown.: Img:
![t3](https://user-images.githubusercontent.com/1811857/33603215-22adac2c-d9b2-11e7-8002-25600c41f32e.jpg)

**Comment by Jimmi08** [comment] 2017-12-05 11:16
@tgtje there is something wrong with download plugin. Not this issue. But if you delete parent category (I had one parent and one child of this parent, just names filled, no SEF), it shot down mysql server on localhost. First time I thought I did something wrong, but it happend again. Only fix was restart server. No warning that you can't delete category with children.

**Comment by tgtje** [comment] 2017-12-05 12:55
@Jimmi08 replicated the thing you describe; confirmed. Some extra testing revealed that IFF i delete the main parent) it will start deleting it (also from db) and when child present, the child is still present.
After clicking the Category link indeed the mysql server freezes.. (error shows chrashed ; dl ; core; adm log).
Starting a new but now delete the child first; then the parent> all functions... So dbase gets mixed up if child stays, but has no belonging to something else (redundant eg leftover 'kills')

**Comment by oxigeno2** [comment] 2018-01-29 12:40
Hi, so I came back to the problem. I know the problem is in hosting.
Specifically, the file e107_plugins/download/includes/admin.php from version 2.1.6
When using file (v2.1.5), the category will be loaded.

**Comment by CaMer0n** [comment] 2018-01-29 18:03
@oxigeno2 Do your have MySQL access to "CREATE ROUTINE" ?
@Deltik ;-)

**Comment by oxigeno2** [comment] 2018-01-31 05:22
Yes :+1:

**Comment by Deltik** [comment] 2018-01-31 08:50
@oxigeno2: It's not clear what your issue is from the information you've provided so far.  On the page with the issue, can you try adding `[debug=everything+]` to the end of the address bar, pressing <kbd>Enter</kbd>, and screenshotting the entire output?

[Full page screenshots on Google Chrome](https://chrome.google.com/webstore/detail/take-webpage-screenshots/mcbpblocgmgfnpjjppndjkmgjaogfceg?hl=en)
[Full page screenshots on Mozilla Firefox](https://screenshots.firefox.com/)

The screenshot may show us if the necessary MySQL queries are being run.

**Comment by oxigeno2** [comment] 2018-01-31 09:35
Errors
![fireshot capture 001 - downloads - categories - admin area __ - http___libreoffice funsite cz_e107](https://user-images.githubusercontent.com/2928863/35615296-03274f92-0672-11e8-9d27-25f1087a14e0.jpg)

OK queries
![fireshot capture 004 ok](https://user-images.githubusercontent.com/2928863/35615424-61c8a942-0672-11e8-8fc1-a1fe42b5c6c5.jpg)

**Comment by Deltik** [comment] 2018-01-31 10:21
@oxigeno2: That output pretty clearly shows that the MySQL user `'oxigen'@'88.86.12%'` does not have the `CREATE ROUTINE` permission granted to it.  The quickest fix would be to grant that permission to your user (`GRANT CREATE ROUTINE ON oxigen1511202838.* TO 'oxigen'@'88.86.12%';`).

## Additional Information

Technically, since e107 v2.1.6, the `CREATE ROUTINE` permission has been necessary to compute tree formatting for things like nested categories.

These have been the options we've considered:

* Refine the MySQL functions/routines somewhat so that they are embedded into the e107 core
* Offload the tree formatting code so that it runs in pure PHP

And these are the drawbacks to each approach:

* **MySQL functions:** The `CREATE ROUTINE` permission will be a requirement in the e107 core.  The greater the nesting depth of a row, the more SQL queries need to be run for that row.  The generated tree is a faked approximation rather than being flattened from an actual tree.
* **Pure PHP:** There is a lot of memory, MySQL bandwidth, and computational overhead (likely noticeable on large tables) because the entire table has to be read to produce a correct tree.

A pure PHP approach is available as a preview in #3016, but it only works if you display all rows (no `LIMIT`).  If you cannot grant `CREATE ROUTINE` to your MySQL user, you can try the pure PHP implementation by replacing the following files:

* `/e107_handlers/admin_ui.php` with [these contents](https://raw.githubusercontent.com/e107inc/e107/d8ba5b8a3e9dd9328b719295a10bbc7272305348/e107_handlers/admin_ui.php)
* `/e107_handlers/model_class.php` with [these contents](https://raw.githubusercontent.com/e107inc/e107/d8ba5b8a3e9dd9328b719295a10bbc7272305348/e107_handlers/model_class.php)

Both approaches have less than ideal performance because relational databases like MySQL do not have a concept of parent-child graphs.  There are more performant approaches, but unfortunately, they're more complicated and require structure changes to all tables that have parent-child relationships.

@CaMer0n favors making the MySQL tree functions a part of e107's core as a stopgap, and that's what will likely be implemented unless you or anyone has any objections, suggestions, or alternatives.

**Comment by Moc** [comment] 2018-03-05 10:24
What's the status on this one?

**Comment by Deltik** [comment] 2018-03-05 15:37
This was fixed in #3025 by implementing tree models in pure PHP.  Sorting for tree models was introduced in #3031.

Bugs caused by those changes were fixed in #3032, #3041, #3045, and #3046.

**Comment by Moc** [comment] 2018-03-05 15:56
@Deltik: perfect, thanks :+1:
Closing this issue.

**Closed** 2018-03-05 15:56 UTC
Labels: awaiting feedback, bug, testing required
