### ISSUE TITLE
New install issues

### ISSUE THREAD

**Issue by jamesonp** [e107inc/e107#1102] opened 2015-06-30 03:35 UTC
Using the latest git pull

It appears to install successfully but the database appears somewhat empty:

![Issue](http://i.imgur.com/44rPA7i.png)

Browsing the index throws these errors:

    CRITICAL ERROR:

    Line 483 /var/www/blank.com/public_html/class2.php
    Error reported as: [3]: Core settings saved - backup made active.
    CRITICAL ERROR:

    Line 485 /var/www/blank.com/public_html/class2.php
    Error reported as: [4]: No core backup found. Check that your database has valid content. If not,     please run the Reset_Core utility to rebuild your core settings. 
    After rebuilding your core please save a backup from the admin/sql screen.

**Comment by CaMer0n** [comment] 2015-06-30 17:37
I just performed a fresh install from the Github zip just now, and it installed correctly.  Are you sure you have full MYSQL permissions? Also, did you modify any of the default theme options during install? (eg. default content, default plugins etc)

**Comment by jamesonp** [comment] 2015-06-30 20:40
Full permissions on MariaDB 10.0 and did not modify anything.  Unzipped the files, gave the proper permissions, ran through the installer and got those errors.

**Comment by CaMer0n** [comment] 2015-07-02 20:52
@jamesonp You could try enabling logging to a fil during installation and see if that provides some clues. 
Just modify line 16: 

    define('MAKE_INSTALL_LOG', true);

**Comment by jamesonp** [comment] 2015-07-06 00:05
Here's the log:

    1436140452, 15-07-05 23:54:12  Stage 1 started
    1436140452, 15-07-05 23:54:12  Stage 1 completed
    1436140453, 15-07-05 23:54:13  Stage 2 started
    1436140453, 15-07-05 23:54:13  Stage 2 completed
    1436140464, 15-07-05 23:54:24  Stage 3 started
    1436140464, 15-07-05 23:54:24  Stage 3 completed
    1436140465, 15-07-05 23:54:25  Stage 3 started
    1436140465, 15-07-05 23:54:25  Stage 3 completed
    1436140466, 15-07-05 23:54:26  Stage 4 started
    1436140466, 15-07-05 23:54:26  Stage 4 completed
    1436140481, 15-07-05 23:54:41  Stage 4 started
    1436140481, 15-07-05 23:54:41  Stage 4 completed
    1436140482, 15-07-05 23:54:42  Stage 5 started
    1436140482, 15-07-05 23:54:42  Stage 5 completed
    1436140496, 15-07-05 23:54:56  Stage 4 started
    1436140496, 15-07-05 23:54:56  Stage 4 completed
    1436140497, 15-07-05 23:54:57  Stage 5 started
    1436140497, 15-07-05 23:54:57  Stage 5 completed
    1436140513, 15-07-05 23:55:13  Stage 6 started
    1436140513, 15-07-05 23:55:13  Stage 6 completed
    1436140517, 15-07-05 23:55:17  Stage 7 started
    1436140517, 15-07-05 23:55:17  Config file written successfully
    1436140517, 15-07-05 23:55:17  Stage 7 completed
    1436140518, 15-07-05 23:55:18  Stage 8 started
    1436140519, 15-07-05 23:55:19  Tables created successfully
    1436140519, 15-07-05 23:55:19  Starting configuration import
    1436140519, 15-07-05 23:55:19  Attempting to Write Core Prefs.
    1436140519, 15-07-05 23:55:19  Array
    (
        [failed] => Array
            (
                [0] => core_media_cat
                [1] => core_media_cat
                [2] => core_media_cat
                [3] => core_media_cat
                [4] => core_media_cat
                [5] => core_media_cat
                [6] => core_media_cat
                [7] => core_media_cat
                [8] => core_media_cat
                [9] => core_media_cat
                [10] => core_media_cat
                [11] => core_media_cat
                [12] => generic
                [13] => links
                [14] => links
                [15] => links
                [16] => links
                [17] => links
                [18] => links
                [19] => links
                [20] => links
                [21] => links
                [22] => menus
                [23] => menus
                [24] => menus
                [25] => menus
                [26] => menus
                [27] => menus
                [28] => menus
                [29] => menus
                [30] => menus
                [31] => menus
                [32] => menus
                [33] => menus
                [34] => menus
                [35] => menus
                [36] => menus
                [37] => menus
                [38] => menus
                [39] => menus
                [40] => menus
                [41] => menus
                [42] => menus
                [43] => menus
                [44] => menus
                [45] => news
                [46] => news_category
                [47] => userclass_classes
                [48] => userclass_classes
                [49] => userclass_classes
                [50] => userclass_classes
                [51] => userclass_classes
                [52] => userclass_classes
                [53] => userclass_classes
                [54] => userclass_classes
                [55] => userclass_classes
                [56] => userclass_classes
                [57] => userclass_classes
                [58] => userclass_classes
                [59] => userclass_classes
            )
    
    )
    
    1436140519, 15-07-05 23:55:19  Attempting to write Theme Prefs/Tables (install.xml)
    1436140519, 15-07-05 23:55:19  Array
    (
        [failed] => Array
            (
                [0] => generic
                [1] => menus
                [2] => menus
                [3] => menus
                [4] => menus
                [5] => menus
                [6] => menus
                [7] => menus
                [8] => menus
                [9] => page
                [10] => page
                [11] => page
                [12] => page
                [13] => page
                [14] => page
                [15] => page_chapters
                [16] => page_chapters
            )
    
    )
    
    1436140519, 15-07-05 23:55:19  Plugins table updated
    1436140519, 15-07-05 23:55:19  Theme-related plugin installed: featurebox
    1436140519, 15-07-05 23:55:19  Theme-related plugin installed: gallery
    1436140519, 15-07-05 23:55:19  Theme-related plugin installed: rss_menu
    1436140519, 15-07-05 23:55:19  Addon prefs saved
    1436140519, 15-07-05 23:55:19  Core URL config set to default state
    1436140519, 15-07-05 23:55:19  Core prefs set to install choices
    1436140519, 15-07-05 23:55:19  Admin user created
    1436140519, 15-07-05 23:55:19  Stage 8 completed

And the permissions for the e107 db user:

    MariaDB [(none)]> SHOW GRANTS FOR 'e107'@'localhost';
    +-------------------------------------------------------------------------------------------------------------+
    | Grants for e107@localhost                                                                                   |
    +-------------------------------------------------------------------------------------------------------------+
    | GRANT USAGE ON *.* TO 'e107'@'localhost' IDENTIFIED BY PASSWORD '*removed' |
    | GRANT ALL PRIVILEGES ON `e107`.* TO 'e107'@'localhost'                                                      |
    +-------------------------------------------------------------------------------------------------------------+
    2 rows in set (0.00 sec)

**Comment by ChiellieNL** [comment] 2015-11-06 11:30
Same issue here.
Is there a solutions/workaround yet?
Always loved to use the old version of e107, but being unable to simply do a fresh installation of this new version is annoying..

**Comment by CaMer0n** [comment] 2015-11-13 00:13
@ChiellieNL Are you using MariaDB also?

**Comment by ChiellieNL** [comment] 2015-11-13 00:15
Nope.. MySQL on Ubuntu server

**Comment by septor** [comment] 2015-11-13 10:30
I noticed a similar issue if I let the installer create the database for me. It worked out fine after I created the database manually via phpMyAdmin.

**Comment by CaMer0n** [comment] 2015-11-13 21:54
@ChiellieNL Which version of PHP and MySQL are you running?

**Comment by Moc** [comment] 2015-11-19 09:39
@jamesonp @ChiellieNL Please provide MySQL/MariaDB and PHP versions people! :) Also, what happens when you create the database manually first (e.g. using phpMyAdmin) and then entering those details in the installation procedure, instead of letting the installer create the database.

**Comment by myovchev** [comment] 2015-11-22 11:39
It is definitely related with default (non-production) Ubuntu MySQL settings. I can confirm fresh install is not creating the complete database schema since (at least) 2-3 months. Tested on Ubuntu 14.04 and 15.10 with libmysql driver and default MySQL config. I didn't have the chance to investigate, but I would suggest it's in "strict mode" direction.

**Comment by CaMer0n** [comment] 2015-11-22 16:43
@ChiellieNL or anyone else having this issue, could you please share the value of "sql-mode" in your mysql config file? ( my.cnf )

     eg.    sql-mode = "STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"

**Comment by willem010** [comment] 2015-11-28 18:23
we've had this issue today setting up a new image,
@ChiellieNL suggestion helped. 

@CaMer0n , i've been searching my.cnf , but no such var is in there?

**Comment by Moc** [comment] 2015-11-29 10:50
@willem010 In phpMyAdmin, try running this
`SELECT @@sql_mode`

**Comment by willem010** [comment] 2015-11-29 10:54
no phpmyadmin running, but in mysqlworkbench it returns an empty var. : 

![untitled](https://cloud.githubusercontent.com/assets/6122908/11456640/e43ca7c0-968f-11e5-9c65-485123dee60e.png)

**Comment by Moc** [comment] 2015-11-29 12:10
For testing, you could edit your config file and include this:
`sql-mode="NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"`
This disables the strict mode. Restart MySQL make the changes go into effect. 

Then try a fresh install to see if the original problem can be reproduced.

**Comment by Moc** [comment] 2016-03-15 17:08
What's the status on this one? Is this issue still present?

**Comment by Moc** [comment] 2016-04-05 10:41
@ChiellieNL @jamesonp  @willem010 Is this issue still present on the latest files?

**Comment by willem010** [comment] 2016-04-06 08:38
after getting it to work we left it like it is.
no new installs on this (live) server. cant tell you

**Comment by Moc** [comment] 2016-10-04 18:27
Since there have been many changes to the database handling, also during the installation process, due to adding PHP7 compatibility, this present issue is likely to be resolved. I'm closing the issue but please feel free to re-open in case the issue is still present.

**Closed by Moc** 2016-10-04 18:27 UTC
Labels: bug
