### ISSUE TITLE
Completing sign up on site results in blank screen

### ISSUE THREAD

**Issue by brwnie** [e107inc/e107#1517] opened 2016-04-10 18:26 UTC
Hi there,

When a user registers on the site and completes it, it results in a blank page.

There does not look to be any sign of a registration in users ethier, verified or unverified.

I don't see any output in Apache's error log

**Comment by CaMer0n** [comment] 2016-04-10 21:01
Login as head admin, and then go to /signup.php. Check each page/button.

**Comment by Brooniee** [comment] 2016-04-11 18:36
Says:
Unauthorized access!

After clicking submit

**Comment by CaMer0n** [comment] 2016-04-11 19:33
This will need to be troubleshooted via the chatroom. https://gitter.im/e107inc/e107

**Comment by Moc** [comment] 2016-04-11 22:26
Check the PHP session save path! :)

**Comment by Brooniee** [comment] 2016-04-12 16:35
@Moc thanks, ive checked session path is fine and writable, i'm seeing files there created by the host's user.

@CaMer0n kindly did some troubleshooting last night, not sure if he found anything further? :)

**Comment by Brooniee** [comment] 2016-04-12 20:10
@CaMer0n 
I've managed to workaround this, by tweaking settings:
I changed settings in both User Registration/Login and Signup Page Options

Signup Page Options Changed:
Email Confirmation from None to Required
Option to hide email from None to Display
Use COPPA on signup page? to Disabled
Text to display after signup form has been submitted had text, cleared it.

Registration/Login
New user verification method from E-mail Verification to No Verification (testing after changing JUST this did not work, in case it was an email issue)

**Comment by Moc** [comment] 2018-02-28 12:11
If you are still experiencing this issue, please visit us in the Gitter chatroom to have this issue debugged. Closing for now.

**Comment by CaMer0n** [comment] 2018-03-09 05:12
I recently had this issue on my localhost. I finally traced the cause, but not the fix just yet. 

If the signup page contains an error prior to the form, for example, an <img> tag src pointing to a missing image (which loads a SEF URL of the 404 Error page), then the e-token will be refreshed (due to class2 being loaded by index.php [single-entry point of SEFURLS]) and when the form is submitted the token will mismatch and throw an "Unauthorized Access" message. 

So, I believe we need to detect that a 404  error has occurred before class2.php is loaded by index.php, to make a flag which the session handler would see and prevent regenerating the token. 

see e_TOKEN_DISABLE in index.php and session_handler.php 

Any thoughts/ideas @lonalore  @Deltik @SimSync @myovchev ?

**Comment by Alex-e107nl** [comment] 2018-05-16 05:56
Same problem here, cannot find the reason, standard bootstrap3 theme does not help.. Will try the settings..
One thing, old websites are working (updated with lates git) but new ones do not, blank screen after filling in.. Hope this gets solved soon :-)

**Comment by CaMer0n** [comment] 2018-05-24 22:48
@Alex-e107nl Please check for a broken image on the signup page.. anything returning a 404.

**Comment by Alex-e107nl** [comment] 2018-07-03 14:23
Ohh there was a question.. no there where no broken images or anything that i can discover.. Used the Browniee solution for now..

**Comment by SimSync** [comment] 2018-07-03 18:30
Did you have banned ips, email addresses or domains? If yes, this should be fixed with the commit I've referenced.

**Comment by SimSync** [comment] 2018-07-06 06:49
@Alex-e107nl Could you please check if this issue is fixed?

**Comment by Alex-e107nl** [comment] 2018-07-06 08:11
Hi Achim, 
ive placed the github of today on my testserver and i could signup without any problems in a standard setting, the only thing is that i see a ** in stead of one * behind a required field... but that can be a theme thing, have to look at it later on..

Thx!

**Comment by Moc** [comment] 2019-08-27 08:00
I am closing this issue as I think the issue is fixed in the latest release. If someone is experiencing the same issue, please let us know here and I'll re-open.

**Closed by Moc** 2019-08-27 08:00 UTC
Labels: Help Wanted, bug
