### ISSUE TITLE
version 2.1.2 and problem with prefs

### ISSUE THREAD

**Issue by Jimmi08** [e107inc/e107#2152] opened 2016-12-15 07:56 UTC
My friend just installed 2.1.2 version (downloaded from e107.org),  he tried to click on some functions in admin area (to test this CMS) and he ended with this 

![image](https://cloud.githubusercontent.com/assets/5429548/21215863/0c85750e-c2a4-11e6-9055-1ec59048e182.png)

He set e_DEBUG  in config file to be able to update to github, but tools/database shows empty page. The same prefs page.

**Comment by Jimmi08** [comment] 2016-12-15 14:58
Updated to latest github. SitePrefs in database looks correct.

PHP Version 7.0.8-0ubuntu0.16.04.3

**Comment by Jimmi08** [comment] 2016-12-16 08:16
This is caused with some shortcodes. If I remove WELCOME MESSAGE, NAVIGATION and SITEDISCLAIMER shortcode from theme.php., site is displayed without errors. 

error for SITEDISCLAIMER shortcode:

`Uncaught TypeError: Argument 1 passed to e_pref::loadData() must be of the type array, string given, called in /var/www/clients/client5/web12/web/e/e107_handlers/pref_class.php on line 474 and defined in /var/www/clients/client5/web12/web/e/e107_handlers/pref_class.php:416 Stack trace: #0 /var/www/clients/client5/web12/web/e/e107_handlers/pref_class.php(474): e_pref->loadData('', false) #1 /var/www/clients/client5/web12/web/e/e107_handlers/pref_class.php(449): e_pref->_load(false) #2 /var/www/clients/client5/web12/web/e/e107_handlers/pref_class.php(847): e_pref->load() #3 /var/www/clients/client5/web12/web/e/e107_handlers/e107_class.php(909): e_core_pref->__construct('emote', true) #4 /var/www/clients/client5/web12/web/e/e107_handlers/e_parse_class.php(4867): e107::getConfig('emote') #5 /var/www/clients/client5/web12/web/e/e107_handlers/e_parse_class.php(1771): e_emotefilter->__construct() #6 /var/www/clients/client5/web12/web/e/e107_plugins/siteinfo/e_shortcode.php(54): e_parse->toHTML('Proudly powered...', in /var/www/clients/client5/web12/web/e/e107_handlers/pref_class.php on line 416`

**Comment by Jimmi08** [comment] 2016-12-16 11:48
I found the solution but not reason. 
I need to set 	 in e_parse_class.php (before it was set as TRUE)	
```
// Enable emote display
'emotes'		=> FALSE,
```

**Comment by Jimmi08** [comment] 2016-12-16 17:45
After that change I added one emoticons and saved default set. There was quick message about missing file or something like that. Then I returned e_parse_class.php back and site is working.  I suppose that somehow preferencies was updated correct way and now it works.   Closing because nobody else is able to reproduce this.

**Comment by CaMer0n** [comment] 2016-12-16 22:18
There's still a problem there which could affect others.

**Comment by tgtje** [comment] 2016-12-17 12:12
In addition preference page NO saving after submit. (issue start at http://e107help.org/2953/why-cant-save-anything-the-preferences-page-in-the-admin-area )
Description : when changing a value and submit saving popup appears (browser popup html 5 trigger?) displaying : Please fill out this field.  Now i can find **A** line that disables the popup and saving can be done (line 461 of prefs php and comment this one (disable)).That way i can save BUT it is not the cause.
Disabling this has impact on mail system..  Changes in prefs were made AFTER v 2.1.1 Prefs replacement of prefs php from this version (2.1.1 pack) give working save.
![pop](https://cloud.githubusercontent.com/assets/1811857/21286667/72f54cb2-c45a-11e6-8451-d7a939fb9731.jpg)

**Comment by CaMer0n** [comment] 2016-12-17 17:49
Have you tested using English?

**Comment by tgtje** [comment] 2016-12-18 04:00
Yes, eliminating, bom,whitespace etc.. and or misplaced writing.. all things i could think about which could influence. Idea behind is finding the things that did change in time, and be eliminating (deduction) finding something that has effect. Since this would help, but is bundled/a combination of different other files one would assume it is part of that codeline (mail using a prefs 'setting/code call') at some points interferes. I can not oversee the whole concept going on, so i can only report Is it the actual cause? i do not know, it has effect, but either position (stage of when in use) or a setting elsewhere? Those popups relate to browser behaviours regarding html 5 (and basically also bootstrap) and it is not (by search engines) related to e107 but on a general base in coding (towards html5 /bs). (the img used it a screen from dutch but equal to english in FF; where for me Chrome just has non reacting screen (at submit stage). Nit reacting > i can click other items/links etc.. just not submit as trigger to do something in which commenting that posted line 'overrides'.

**Comment by Jimmi08** [comment] 2017-03-04 19:48
@Moc Can be this closed?  For me it's solved.

**Comment by tgtje** [comment] 2017-03-05 14:38
Not seen it in a while, so probably it is handled...

**Comment by CaMer0n** [comment] 2017-03-05 15:55
Closing. Please re-open if necessary.

**Closed by CaMer0n** 2017-03-05 15:55 UTC
Labels: testing required
