### ISSUE TITLE
Compress Site Output Using gzip causes content-length header to be incorrect and website will not load on Safari

### ISSUE THREAD

**Issue by martyshep** [e107inc/e107#2638] opened 2017-05-16 12:26 UTC
I hit this before on Chrome and blamed all my infrastructure, I had to put **header('Content-length: ' . strlen($output));** in my class2.php to force chunked encoding to get my website to load in browsers. What seems to be happening is that if **Compress Site Output Using gzip** is selected in Preferences then the header-length is sent as what it would be un-compressed, so the browser is waiting for further data and in the case of Safari, shows the website for a second or so then goes to error page 'safari cannot open the page because the network connection was lost'

**Comment by martyshep** [comment] 2017-05-16 12:27
I see this raised as a PHP bug: https://bugs.php.net/bug.php?id=44164

**Comment by arunshekher** [comment] 2017-05-16 20:44
Can confirmed this. Had to turn off PHP zlib compression in admin pref. and resort to apache mod_deflate output compression.

**Comment by CaMer0n** [comment] 2017-05-16 21:33
@martyshep does my commit correct the issue for you?

**Comment by martyshep** [comment] 2017-05-17 08:14
@CaMer0n Thank you Sir, awesome quick response. One would think you are paid for this :)

The issue of the page not loading because the header length is now resolved with latest commit. When I set **Compress Site Output Using gzip = ON** the website loads fine in all browsers. 

However, when I check the page size in the browser, it is actually the same size regardless of the setting for Compress Site Output Using gzip = ON or OFF?  I do use mod_deflate in my .htaccess anyway.

**Comment by CaMer0n** [comment] 2017-05-17 16:33
@martyshep I'm happy it worked out! So if you load your site with "Inspect Element" and the "Network" tab enabled. (in FF) the "Transferred" and "Size" column have the same value? (For the html) ?

**Comment by martyshep** [comment] 2017-05-17 21:04
@CaMer0n Yes it would appear so, the size is same with or without Compress Site Output Using gzip = ON or OFF. Screenshot show green with Compress ON, Yellow with Compress OFF
![html size](https://cloud.githubusercontent.com/assets/15772899/26176091/dab982a0-3b4c-11e7-99ec-1c9d5690fa09.jpg)

**Comment by CaMer0n** [comment] 2017-05-24 19:39
@martyshep Maybe mod_deflate was running? If you check the headers for the page it should say if it was compressed or not.

**Comment by martyshep** [comment] 2017-05-25 08:11
@CaMer0n Yes mod_deflate is running as it is in my .htaccess: 
### Gzip Compression Module
<ifmodule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/text text/html text/plain text/xml text/css text/javascript application/x-javascript application/javascript application/xml text/xml application/rss+xml
</ifmodule>

And yes it is showing as compressed regardless of the E107_Admin>Preferences>Advanced>Compress site output ON or OFF

**Comment by CaMer0n** [comment] 2017-05-25 21:23
okay great. Working as intended. Thanks.

**Closed by CaMer0n** 2017-05-25 21:23 UTC
Labels: bug
