### ISSUE TITLE
Users able to verify email and sign in without admin approval when admin approval is set

### ISSUE THREAD

**Issue by dimante** [e107inc/e107#3069] opened 2018-03-08 20:41 UTC
![image](https://user-images.githubusercontent.com/4084331/37175275-a8bf049e-22de-11e8-814d-ac83ff096ce0.png)

With the settings above users are immediately able to log in without admin approval.. Latest Git.

-D-

**Comment by CaMer0n** [comment] 2018-03-09 00:06
@dimante is e107 sending an email during signup? (with your settings)

**Comment by dimante** [comment] 2018-03-09 00:25
Yes, the email is functioning, the people are verifying the account then it
is going active instead of waiting for admin approval...

Best Regards,

John Gates, CISSP

*Let’s Connect!*

<https://twitter.com/johngatesIII>   <http://www.linkedin.com/in/JohnGates>

**Comment by SimSync** [comment] 2018-07-03 14:00
Is this issue still alive with current github version?
I'm unable to reproduce this issue ...?!?

**Comment by Moc** [comment] 2019-02-01 15:09
I cannot reproduce this. If I try to login I get this message:

![image](https://user-images.githubusercontent.com/577978/52130843-99657580-263b-11e9-83b4-228804e2c357.png)

It does need to be tweaked in case there admin verification set, so the LAN resembles that (rather than 'email sent').

**Comment by Moc** [comment] 2019-02-01 15:20
Closing this issue as I assume it has been fixed. 

@dimante If you are still experiencing the issue, please let us know.

**Closed by Moc** 2019-02-01 15:20 UTC
Labels: bug, testing required
