### ISSUE TITLE
[Bug]: user_ban_flood IPV6 address not valid (truncated)

### ISSUE THREAD

**Issue by BlastFM** [e107inc/e107#5231] opened 2024-04-07 14:42 UTC
### What e107 version are you using?

v2.3.3, Latest Github version (just updated)

### Bug description

The user_ban_flood feature in e107 does not produce a valid IPV6 address.

Example: 0000:0000:0000:0000:0000:ffff:b5d6:ad57

I believe this IPV6 address is truncated, possibly caused by mysql varchar(character count) on banlist_ip.

From what I remember when I looked at this previously, there are about two characters truncated, an IPV6 address has 32 characters, not 30.

### How to reproduce

This happens whenever there is a user_ban_flood or bad login details occur on the website, and the offending IPV6 address is emailed to the website admin email address.

### Expected behavior

I would expect it to email a valid IPV6 address, which is verifiable by looking it up in a IPV6 whois.

### What browser(s) are you seeing the problem on?

Chrome / Brave

### PHP Version

7.0.33

**Comment by Moc** [comment] 2024-04-07 14:45
Duplicate of https://github.com/e107inc/e107/issues/3612

Fixed here https://github.com/e107inc/e107/commit/05727b8b52e98893b70d0086adaabbacb619d95d and will be part of the 2.4.0 release.

**Closed by Moc** 2024-04-07 14:45 UTC
Labels: status: duplicate
