### ISSUE TITLE
User settings

### ISSUE THREAD

**Issue by mcpeace-maw** [e107inc/e107#1285] opened 2015-12-29 15:36 UTC
If you go to user settings and try to change the avatar, when you click on the default avatar image to change the avatar, an empty space is expanding under it and no avatar images. Checked with core bootstrap theme and is the same.

**Comment by mcpeace-maw** [comment] 2015-12-29 16:35
Strange thing, after some time I opened again admin area and a notification ask for database update. After update, user setting avatar it works OK, I see the avatars for e107_images/avatars folder now. So I think it is works. Maybe someone will check also.

**Comment by Moc** [comment] 2015-12-29 21:07
https://github.com/e107inc/e107/issues/543

**Comment by pierre0042** [comment] 2016-02-17 23:17
I have the same problem with avatar on user registration.
Nothing happens when you click on the image.

See :
![e107-register](https://cloud.githubusercontent.com/assets/4124597/13128294/fcb89f8c-d5d4-11e5-9278-b6b17bb44690.png)

**Comment by pierre0042** [comment] 2016-02-17 23:25
Seems a duplicate of https://github.com/e107inc/e107/issues/1191

**Comment by mcpeace-maw** [comment] 2016-02-18 16:58
@pierre0042  It is working like this: first go to admin-area/users/options/Allow members to upload an avatar? = Yes (check yes). After that if you go in user-settings and click on avatar you will see the button to upload an avatar. When you check yes, you allow just members to upload an avatar, unregistered users in user registration page don't have an upload avatar button when they click on avatar. Here are 2 solutions, to make an option (just for registration page)) to let unregistered users to upload an avatar or to remove the avatar from registration page (it is useless now) and allow just members to upload an avatar in user-settings page.

**Comment by pierre0042** [comment] 2016-02-18 17:04
The option "Allow members to upload an avatar?" is already set to "Yes".

I see that it works for an existing user to upload an avatar in /usersettings.php

But it was working in v1 at the registration step...

**Comment by Moc** [comment] 2016-02-18 17:08
@pierre0042 I agree, this needs enhancement. 

Listed as bug/enhancement: Fix avatar upload on registration and/or remove from signup page when avatar upload option is disabled

**Comment by mcpeace-maw** [comment] 2016-02-18 17:17
@Moc maybe it is not a bad idea to have 3 options with avatars: allow avatar upload for members, allow avatar upload for unregistered users and admin option to upload avatars in Media Manager and let new users or/and members to use them.

**Comment by Moc** [comment] 2016-02-18 17:31
@mcpeace-maw 
The first two are already present: 
- Preferences > signup page options 
- Users > Options > Allow members to upload an avatar?

The third one is possible through directly uploading avatars into the e107_media/hash/avatars/default folder. I think there is no interface available in the admin area to do this, so this could be an addition.

**Closed** 2016-02-25 20:53 UTC
Labels: bug, enhancement
