### ISSUE TITLE
Option to Disable div class panel-heading

### ISSUE THREAD

**Issue by BigBoiJefe** [e107inc/e107#3295] opened 2018-07-20 01:29 UTC
I know this might sound like a crazy idea, however, I would love it if there were a way to disable the following div tag on specific pages.

`<div class="panel-heading"></div>`

This is mainly an aesthetic enhancement request.  I have a custom page called Upgrade, I don't want any page heading because the design that I have already has it.  

See the before image here
![2018-07-19_182602](https://user-images.githubusercontent.com/25377269/42978369-5b4e7436-8b81-11e8-89d4-8fdf7e2b6eca.png)

If I remove the `<div class="panel-heading"></div>` element completely, i have a much cleaner page, see image here
![2018-07-19_182623](https://user-images.githubusercontent.com/25377269/42978380-6bdf0ab8-8b81-11e8-9980-dea1eecd902d.png)

I don't know if this is possible, but I have to ask.  It should be noted that there are some pages like the user login and user signup pages that the panel-heading is a necessity.

Thanks.

**Comment by CaMer0n** [comment] 2018-07-20 18:39
`div.panel-heading {display: none } `

**Comment by Jimmi08** [comment] 2018-07-24 16:32
if you use tablerender(), you should use third parameter for style without this heading.

**Comment by BigBoiJefe** [comment] 2018-07-24 16:35
Thanks all for your responses.  Jimmi08 can you explain?

**Comment by Jimmi08** [comment] 2018-07-24 16:49
Insert your using of tablerender() in your custom page - what is outputing your code 
and insert how your tablerender() function looks in theme.php 
I have no idea what you are doing now.

**Comment by BigBoiJefe** [comment] 2018-07-25 22:08
This is what my custom page is:

```
<?php
require_once("../class2.php");
require_once(HEADERF);

if (!USER) {
    header("location:".e_BASE."index.php");
    exit;
}

if($pref['user_tracking'] != "session"){
        session_start();
}


//if(check_class('Premium Member')) {
//      $caption = "Premium Membership Status";
//      $text = "Your Premium Membership is greatly appreciated!  Thanks for your support.<br />";
//} else {
// Set BluePay parameters


//$caption = "Upgrade to Premium Membership";
$text  = "<img src=\"types.png\"></img>";
$text .= "<div>";
$text .= "<script src=\"https://gumroad.com/js/gumroad.js\"></script>\n";
$text .= "<a class=\"gumroad-button\" href=\"https://gum.co/yVeJyT?wanted=true\">Upgrade Now!</a>\n";
$text .= "</div>";

$caption = $tp->toHtml($caption);
$text = $tp->toHtml($text);

$ns->tablerender($caption, $text);
require_once(FOOTERF);
?>
```

**Comment by Jimmi08** [comment] 2018-07-26 17:59
This:
`$ns->tablerender($caption, $text);`
- add third parameter f.e. 'nocaption', 'nopanel' etc

`$ns->tablerender($caption, $text, 'nocaption');`

And then add it to tablerender() function in theme.php (or check if there is not needed style already)
it's parameter $id -  some theme do $style=$id;  - you need to check your one.

(see welcome message... or examples in bootstrap3 theme)

**Comment by CaMer0n** [comment] 2018-07-28 23:52
Closing as it's not a bug, but feel free to continue the discussion here.

**Closed by CaMer0n** 2018-07-28 23:52 UTC
