### ISSUE TITLE
Clean install + php 5.3 = errors

### ISSUE THREAD

**Issue by willem010** [e107inc/e107#864] opened 2015-02-06 08:38 UTC
When installing a clean latest git (yesterday's version) i got a lot of 500 errors
stuff like ejslib. messages etc.. scripts returned err 500 .. 
jquery refused to load in frontend, as well as other scripts in backend.

when i changed to php 5.6 all errors were gone, so it's php version related.
what should be the lowest version to work?

in the recent past 5.3 was ok?

**Comment by CaMer0n** [comment] 2015-02-06 09:12
Strange! I believe Error 500 is usually a server configuration issue.

**Comment by willem010** [comment] 2015-02-06 09:42
it's a new provider for me, never used this one before..
php 5.3 is the default over there.. so thats why i noticed.
anyway,

it seems to me the e_jslib.php (and other files) use php version specific functions?
that's one of the files that returned an err500.. 
(and in backside it was a pm script with the same issue) 

using php 5.6 .. no issues.
i can switch back this night, so see what other files have an issue.

**Comment by CaMer0n** [comment] 2015-02-06 15:55
Perhaps the Apache logs will provide some more info on the cause?

**Comment by willem010** [comment] 2015-02-06 16:19
I'll switch it back to 5.3 this night to see what's going on there.
i will report the findings later on.

what i can see in the acces log, 
e_jslib.php
wysiwyg.php
theme.php
page.php
sitedown.php
admin/plugin.php
featurebox/adminconfig.php
index.php

all show up with err500 (until i changed the php version.)

i have another - identical - clean setup coming up on the same server, different domain.
will report on that i a few days

**Comment by willem010** [comment] 2015-02-06 16:43
and i forgot to mention, but for this site, (like most of my providers, )
apache stuff, both config and logs, are not available..
same for php.ini... all i have is a selector for php and sql versions..

(the error log here doesnt even report 500's .. only 404's there.. lol )
so, can't help you with apache logs.
but i will report anything i can to help you guys out.

(for me, just selecting php5.6 did the trick.. ;) )

**Comment by CaMer0n** [comment] 2015-04-05 07:45
If you rename .htaccess to something else, does the issue stop occurring?

**Comment by willem010** [comment] 2015-04-06 07:20
i had to change the htacces files anyway, the server didnt like some of the options.
but like i mentioned before, this problem reaaly got solved when i set the server to use php 5.5
when i set it to 5.3, its not working for this server... just like i reported earlier.

funny tho : 
same code is working ok on another server running 5.3, at another hosting company versions set identical, just different platform .. 
my findings using the hosting company names : 
hosting2go.nl just doesnt like it on 5.3, needs 5.5 and changes to the htacces (5.4 untested), 
zyma.com has no issue on the htacces,  code works 90% on 5.5, ok on 5.4 and 5.3,
(i will look into this, some more later on, zyma has tons of logs, the issues here are minor..) 
digitalocean.com has no problems on phpversion at all.. 100% ok. 
lol..dont we love the "standards ,,"  ). 
 
the second install i mentioned went without a hitch
i did edit the htacces according to the servers wishes before uploading it tho.. .

there still seem to be issues - probably module related. some hosting companies allow this, but not that. i know some comapnies do not allow the use of curl, at some you're not allowed to edit the htacces yourself (and you will need a -payed- helpdesk person to edit it for you.. ..)  etc.
it's a nightmare!.  

for me the issue is solved,
just keep it in mind on other bug reports.

**Comment by CaMer0n** [comment] 2015-04-07 06:45
Thanks @willem010. I'll close it and keep an eye out for similar issues.

**Closed by CaMer0n** 2015-04-07 06:45 UTC
Labels: awaiting feedback
